// Deutsch. Der Schlüssel ist der englische Satz, so wie er im Code steht.
//
// Regeln dieser Tabelle: schlichte Sprache, keine Werbewörter, keine
// Ausrufezeichen. Anrede in der Sie-Form, wo eine Person angesprochen werden
// muss, sonst neutral und unpersönlich; nie "du". Ticker (SKR, SOL), Seeker,
// Seed Vault, Solana Mobile, SKR Eyes, Solscan und .skr-Namen bleiben so, wie
// sie sind. Fachwörter aus der Community bleiben: Stake, staken, Rent (die
// Solana-Kontogebühr, nicht "Miete"), Blockhash, Lamports, Airdrop. Ausstieg
// steht für unstake, Abkühlphase für cooldown, Auszahlung für withdraw,
// Freigabe für unlock. Keine Gedankenstriche, stattdessen Komma oder Punkt.
// Die Platzhalter in geschweiften Klammern kommen schon formatiert an; sie
// dürfen verschoben, aber nicht verändert werden.
//
// Deutsch ist rund ein Drittel länger als Englisch, darum sind die Beschriftungen
// von Chips und Schaltflächen bewusst kürzer als die wörtliche Übersetzung.

export const de: Record<string, string> = {
  'Sixteen today?': 'Heute die Sechzehn?',
  '16 parts of 1 SKR, one approval. A small habit that keeps your stake moving.': '16 Teile von 1 SKR, eine Freigabe. Eine kleine Gewohnheit, die Ihren Stake in Bewegung hält.',
  'A daily nudge for the Sixteen': 'Ein täglicher Anstoß für die Sechzehn',
  'Once a day, around six in the evening, a gentle reminder to keep your stake moving. Set on the phone itself, nothing is sent anywhere.': 'Einmal am Tag, gegen sechs Uhr abends, eine sanfte Erinnerung, den Stake in Bewegung zu halten. Wird auf dem Telefon selbst eingerichtet, nichts wird irgendwohin gesendet.',
  'Earned on staking': 'Durch Staking verdient',
  'An estimate from the share price at your last stake or unstake. Rewards banked before that move are folded into your position and not counted here.': 'Eine Schätzung anhand des Anteilspreises bei Ihrem letzten Stake oder Ausstieg. Belohnungen, die vor diesem Schritt verbucht wurden, stecken schon in Ihrer Position und werden hier nicht mitgezählt.',
  'All': 'Alle',
  'Stakes': 'Stakes',
  'Exits': 'Ausstiege',
  'Withdrew': 'Auszahlungen',
  'Vault': 'Tresor',
  'over the last 7 days': 'in den letzten 7 Tagen',
  'over the last 30 days': 'in den letzten 30 Tagen',
  '{percent}% of all SKR is staked': '{percent} % aller SKR sind gestakt',
  'over the last 24 hours': 'in den letzten 24 Stunden',
  'net': 'netto',
  'wallets': 'Wallets',
  // Tabs und Frische-Anzeige
  'Flow': 'Fluss',
  'Me': 'Ich',
  'Queue': 'Warteschlange',
  'Alerts': 'Hinweise',
  'fresh': 'aktuell',
  'aging': 'altert',
  'stale': 'veraltet',
  'unavailable': 'keine Daten',
  'syncing': 'wird abgeglichen',
  'every number has a receipt': 'jede Zahl hat einen Beleg',

  // Tresor (die Szene)
  'Waiting for a finalized answer': 'Warten auf eine finalisierte Antwort',
  'Reading the vault': 'Tresor wird gelesen',
  'Network unavailable': 'Kein Netz',
  'Last 24 hours': 'Letzte 24 Stunden',
  'Last 7 days': 'Letzte 7 Tage',
  'Last 30 days': 'Letzte 30 Tage',
  '24h': '24 h',
  'staked': 'gestakt',
  'in': 'rein',
  'asked out': 'zum Ausstieg',
  'staked minus requested out': 'gestakt minus beantragte Ausstiege',
  'history covers {days}d': 'Verlauf über {days} Tage',
  'In cooldown': 'In der Abkühlphase',
  '{count} positions waiting out the 48 hours': '{count} Positionen sitzen ihre 48 Stunden ab',
  'Ready to exit': 'Bereit zum Ausstieg',
  'Cooldown finished, not yet withdrawn': 'Abkühlphase beendet, noch nicht ausgezahlt',
  'When the queue matures': 'Wann die Warteschlange fällig wird',
  'ready': 'bereit',
  'cooling down': 'kühlt ab',
  'ready to withdraw': 'bereit zur Auszahlung',
  'Motion': 'Bewegung',
  'The vault stands still.': 'Der Tresor steht still.',
  'One gentle frame a second.': 'Ein ruhiges Bild pro Sekunde.',
  'Live while you watch. Calm after 90 seconds without a touch.': 'Live, solange Sie hinsehen. Ruhig nach 90 Sekunden ohne Berührung.',
  'Receipt': 'Beleg',
  'Open on Solscan': 'Auf Solscan öffnen',

  // Warteschlange
  'Exits in flight, soonest first': 'Laufende Ausstiege, die nächsten zuerst',
  '{count} shown': '{count} angezeigt',
  'Show all {count}': 'Alle {count} zeigen',
  'Show fewer': 'Weniger zeigen',
  'Nothing is queued to leave right now.': 'Gerade wartet nichts auf den Ausstieg.',

  // Fluss
  'Live from the vault': 'Live aus dem Tresor',
  'Reconnecting': 'Verbindung wird neu aufgebaut',
  'BUZZ ON': 'VIBRATION AN',
  'BUZZ OFF': 'VIBRATION AUS',
  'SOUND ON': 'TON AN',
  'SOUND OFF': 'TON AUS',
  'Biggest seen today': 'Größte Bewegung heute',
  'Biggest stake today': 'Größter Stake heute',
  'Biggest exit today': 'Größter Ausstieg heute',
  'Biggest withdrawal today': 'Größte Auszahlung heute',
  'Last big move': 'Letzte große Bewegung',
  '{age} ago': 'vor {age}',
  'slot {slot}': 'Slot {slot}',
  'amount unavailable': 'Betrag nicht verfügbar',
  'withdrew': 'ausgezahlt',
  'cancelled exit': 'Ausstieg abgebrochen',
  'stake': 'Stake',
  'unstake': 'Ausstieg',
  'withdraw': 'Auszahlung',
  'Fold the older large moves': 'Ältere große Bewegungen einklappen',
  '1 more large move': '1 weitere große Bewegung',
  '{count} more large moves': '{count} weitere große Bewegungen',
  '{count} landed while you watched': '{count} kamen an, während Sie zusahen',
  'Watching the chain': 'Chain wird beobachtet',
  'ALL': 'ALLE',
  'only {amount} SKR and up': 'nur ab {amount} SKR',
  'everything, dust included': 'alles, Staub inklusive',
  'Waiting for the next finalized event of this size.': 'Warten auf das nächste finalisierte Ereignis dieser Größe.',

  // Ich: Profil und Karte
  'Leaving': 'Im Ausstieg',
  '1 position in cooldown': '1 Position in der Abkühlphase',
  '{count} positions in cooldown': '{count} Positionen in der Abkühlphase',
  'Ready now': 'Jetzt bereit',
  'Next unlock': 'Nächste Freigabe',
  'Cooldown finished': 'Abkühlphase beendet',
  'Until this position is free': 'Bis diese Position frei ist',
  'Nothing queued': 'Nichts in der Warteschlange',
  'Your weight in the vault': 'Ihr Gewicht im Tresor',
  'First stake {days} days ago, read from the oldest signature on your position account.': 'Erster Stake vor {days} Tagen, gelesen aus der ältesten Signatur auf Ihrem Positionskonto.',
  'Held at least {days} days. Your position has a long signature history, so the walk back is still going.': 'Mindestens {days} Tage gehalten. Ihre Position hat eine lange Signaturhistorie, der Rückweg läuft noch.',
  'Reading the age of your position from the chain…': 'Alter Ihrer Position wird von der Chain gelesen…',
  'Stake SKR': 'SKR staken',
  'Drawing your card…': 'Ihre Karte wird gezeichnet…',
  'Share your card': 'Karte teilen',
  'Alerts armed': 'Hinweise aktiv',
  'Wake me at unlock': 'Bei Freigabe wecken',
  'Refresh': 'Aktualisieren',
  'Disconnect': 'Trennen',
  'This address holds no SKR position right now.': 'Diese Adresse hält gerade keine SKR-Position.',
  'This wallet holds no SKR position yet. The first stake opens one; the position account costs a little rent once.': 'Diese Wallet hält noch keine SKR-Position. Der erste Stake eröffnet eine; das Positionskonto kostet einmalig etwas Rent.',
  'This position is being looked at, not signed for. Connect the wallet that holds it to stake from it.': 'Diese Position wird nur angesehen, nicht signiert. Verbinden Sie die Wallet, die sie hält, um von ihr aus zu staken.',
  'Connect the wallet that holds your stake, or paste any public address. Nothing is signed.': 'Verbinden Sie die Wallet mit Ihrem Stake oder fügen Sie eine beliebige öffentliche Adresse ein. Es wird nichts signiert.',
  'Connect Solana Mobile': 'Solana Mobile verbinden',
  'OR': 'ODER',
  'Paste a Solana address': 'Solana-Adresse einfügen',
  'Look up': 'Nachsehen',
  'WEIGHT': 'GEWICHT',
  'POSITIONS': 'POSITIONEN',
  'READ FROM': 'GELESEN VON',
  '1 unlock alert armed on this phone.': '1 Freigabe-Hinweis auf diesem Telefon aktiv.',
  '{count} unlock alerts armed on this phone.': '{count} Freigabe-Hinweise auf diesem Telefon aktiv.',
  'Nothing left to wait for — the cooldown is already over.': 'Nichts mehr abzuwarten, die Abkühlphase ist schon vorbei.',
  'Caption copied. Paste it next to the picture.': 'Text kopiert. Fügen Sie ihn neben dem Bild ein.',
  'This phone would not take the caption — type it yourself.': 'Dieses Telefon hat den Text nicht angenommen. Tippen Sie ihn selbst ein.',
  'Your SKR staker card': 'Ihre SKR-Staker-Karte',
  'This phone has nothing to share with.': 'Dieses Telefon hat keine App zum Teilen.',
  'Hide my name on the card': 'Meinen Namen auf der Karte verbergen',
  'Hide my amount on the card': 'Meinen Betrag auf der Karte verbergen',
  'The eye in the ring closes and the card says A Seeker.': 'Das Auge im Ring schließt sich, und auf der Karte steht A Seeker.',
  'Days, since and one-of stay; the position line goes.': 'Tage, Startdatum und "eine von" bleiben; die Positionszeile fällt weg.',
  'An exact amount next to a start date is close to a fingerprint. Your choice, said plainly.': 'Ein genauer Betrag neben einem Startdatum ist fast ein Fingerabdruck. Ihre Entscheidung, offen gesagt.',

  // Die täglichen Sechzehn
  'Sixteen': 'Sechzehn',
  'The daily sixteen': 'Die täglichen Sechzehn',
  '16 parts of 1 SKR, one approval. A small daily habit that keeps your position moving.': '16 Teile von 1 SKR, eine Freigabe. Eine kleine tägliche Gewohnheit, die Ihre Position in Bewegung hält.',

  // Trinkgeld
  'Support SKR Eyes': 'SKR Eyes unterstützen',
  'Send a tip': 'Trinkgeld geben',
  'A tip in SKR': 'Ein Trinkgeld in SKR',
  'How much': 'Wie viel',
  'Any amount you like. Goes to {name}, the wallet behind this app.': 'Jeder Betrag, ganz wie Sie mögen. Geht an {name}, die Wallet hinter dieser App.',
  'Send {amount} SKR to {name}': '{amount} SKR an {name} senden',
  '{amount} SKR on its way to {name}': '{amount} SKR unterwegs zu {name}',
  'Thank you': 'Danke',
  'Done': 'Fertig',
  'Landing on chain…': 'Landet auf der Chain…',
  'Your wallet signs and sends it. The app only fetches a blockhash before and reads the status after.': 'Ihre Wallet signiert und sendet. Die App holt vorher nur einen Blockhash und liest danach den Status.',
  'A tip changes nothing about your position and nothing about any airdrop. It is a thank you, not a fee.': 'Ein Trinkgeld ändert nichts an Ihrer Position und nichts an irgendeinem Airdrop. Es ist ein Dankeschön, keine Gebühr.',
  'Free and open source, built by one Seeker. Tips in SKR go to kosa.skr and are staked right away, all of them.': 'Kostenlos und quelloffen, gebaut von einem Seeker-Besitzer. Trinkgelder in SKR gehen an kosa.skr und werden sofort gestakt, alle.',
  'This app is free, open source, and built by one Seeker. If it saved you a moment, a tip is welcome. Every SKR that arrives is staked right away, all of it.': 'Diese App ist kostenlos, quelloffen und von einem Seeker-Besitzer gebaut. Wenn sie Ihnen einen Moment gespart hat, ist ein Trinkgeld willkommen. Jeder SKR, der ankommt, wird sofort gestakt, vollständig.',
  'This is {name} itself. A tip to your own wallet moves nothing; try from another wallet.': 'Das ist {name} selbst. Ein Trinkgeld an die eigene Wallet bewegt nichts; versuchen Sie es von einer anderen Wallet.',
  'The chain rejected the transfer.': 'Die Chain hat die Überweisung abgelehnt.',
  'The wallet declined. Nothing was sent.': 'Die Wallet hat abgelehnt. Es wurde nichts gesendet.',
  'The wallet returned no signature.': 'Die Wallet hat keine Signatur zurückgegeben.',
  'SKR has six decimal places. Shorten the amount.': 'SKR hat sechs Nachkommastellen. Kürzen Sie den Betrag.',

  // Fehler, die eine Person wirklich zu sehen bekommt
  'The finalized snapshot is still warming up. Try again in a moment.': 'Der finalisierte Schnappschuss wird noch aufgebaut. Versuchen Sie es gleich noch einmal.',
  'This position could not be read': 'Diese Position konnte nicht gelesen werden',
  'The wallet request was cancelled': 'Die Wallet-Anfrage wurde abgebrochen',
  'The wallet did not return an account.': 'Die Wallet hat kein Konto zurückgegeben.',
  'Alerts could not be scheduled': 'Hinweise konnten nicht geplant werden',
  'The card is not ready yet': 'Die Karte ist noch nicht fertig',
  'The card could not be drawn': 'Die Karte konnte nicht gezeichnet werden',
  'the chain returned no signatures': 'die Chain hat keine Signaturen zurückgegeben',
  'age lookup failed': 'Altersabfrage fehlgeschlagen',
  'SKR Eyes API returned {status}': 'Die SKR Eyes API antwortete mit {status}',
  'The age service answered {status}': 'Der Altersdienst antwortete mit {status}',
  'The app was closed while the wallet had this stake. Check your position before staking again, then clear this.': 'Die App wurde geschlossen, während die Wallet diesen Stake in Arbeit hatte. Prüfen Sie Ihre Position, bevor Sie erneut staken, und räumen Sie das dann weg.',
  'The wallet that answered is not the one on screen. Connect the wallet that holds this position, then stake. Nothing was sent.': 'Die Wallet, die geantwortet hat, ist nicht die auf dem Bildschirm. Verbinden Sie die Wallet, die diese Position hält, und staken Sie dann. Es wurde nichts gesendet.',

  // Hinweise-Bildschirm
  'Notifications allowed': 'Benachrichtigungen erlaubt',
  'Notifications off': 'Benachrichtigungen aus',
  'Alerts are scheduled on the phone itself. Nothing about you leaves the device.': 'Hinweise werden auf dem Telefon selbst geplant. Nichts über Sie verlässt das Gerät.',
  'Allow notifications and this app can wake you exactly when your cooldown ends.': 'Erlauben Sie Benachrichtigungen, dann kann diese App Sie genau dann wecken, wenn Ihre Abkühlphase endet.',
  'Allow notifications': 'Benachrichtigungen erlauben',
  'Open settings': 'Einstellungen öffnen',
  'This phone can now wake you.': 'Dieses Telefon kann Sie jetzt wecken.',
  'Android will not ask again. Turn notifications on for SKR Eyes in the system settings.': 'Android fragt nicht noch einmal. Schalten Sie Benachrichtigungen für SKR Eyes in den Systemeinstellungen ein.',
  'Android is holding notifications back for this app.': 'Android hält Benachrichtigungen dieser App zurück.',
  'Android did not answer the permission request. Try again, or turn notifications on in the system settings.': 'Android hat auf die Berechtigungsanfrage nicht geantwortet. Versuchen Sie es noch einmal oder schalten Sie Benachrichtigungen in den Systemeinstellungen ein.',
  'This phone would not open its settings screen.': 'Dieses Telefon hat seine Einstellungen nicht geöffnet.',
  'Wake me at my unlock': 'Bei meiner Freigabe wecken',
  'Connect your wallet on the Me screen and this switch becomes live.': 'Verbinden Sie Ihre Wallet im Tab Ich, dann wird dieser Schalter aktiv.',
  'One hour before, and again the moment the cooldown ends. Scheduled by this phone from the exact on-chain time.': 'Eine Stunde vorher und noch einmal in dem Moment, in dem die Abkühlphase endet. Geplant von diesem Telefon nach der exakten On-Chain-Zeit.',
  'Nothing of yours is unlocking, so there is nothing to wake you for yet.': 'Nichts von Ihnen wird freigegeben, also gibt es noch nichts, wofür Sie geweckt werden müssten.',
  'Large moves, heard and felt': 'Große Bewegungen, hörbar und spürbar',
  'From 100K SKR only: a stake rings like an old phone, an exit lands with a low boom, a withdrawal closes a door. On every screen while the app is open, each with a short buzz.': 'Erst ab 100K SKR: ein Stake klingelt wie ein altes Telefon, ein Ausstieg landet mit einem tiefen Wumms, eine Auszahlung schließt eine Tür. Auf jedem Bildschirm, solange die App offen ist, jeweils mit einem kurzen Vibrieren.',
  "Other people's moves do not wake the phone while the app is closed. Only your own unlock does.": 'Die Bewegungen anderer wecken das Telefon nicht, solange die App geschlossen ist. Nur die eigene Freigabe tut das.',
  'What counts as large': 'Was als groß zählt',
  'Built-in thresholds behind the bell and the boom, until the server publishes its own.': 'Eingebaute Schwellen hinter Glocke und Wumms, bis der Server eigene veröffentlicht.',
  'These come from the server, move with real traffic, and drive the bell and the boom.': 'Diese kommen vom Server, bewegen sich mit dem echten Verkehr und steuern Glocke und Wumms.',
  'Send a test notification': 'Testbenachrichtigung senden',
  'A test notification will arrive in a few seconds.': 'Eine Testbenachrichtigung kommt in ein paar Sekunden.',
  'The test notification could not be scheduled': 'Die Testbenachrichtigung konnte nicht geplant werden',
  '1 reminder set on this phone for your unlock.': '1 Erinnerung auf diesem Telefon für Ihre Freigabe gesetzt.',
  '{count} reminders set on this phone for your unlock.': '{count} Erinnerungen auf diesem Telefon für Ihre Freigabe gesetzt.',
  'The reminders for your unlock were cancelled.': 'Die Erinnerungen für Ihre Freigabe wurden aufgehoben.',
  'The alert could not be changed.': 'Der Hinweis konnte nicht geändert werden.',
  'Language': 'Sprache',
  'The app follows your phone until you choose here. The card you share stays in English, so it reads the same to everyone who sees it.': 'Die App folgt Ihrem Telefon, bis Sie hier wählen. Die Karte, die Sie teilen, bleibt auf Englisch, damit sie für alle gleich lesbar ist.',

  // Die Benachrichtigungen selbst
  'This wallet has no pending SKR unlock.': 'Diese Wallet hat keine ausstehende SKR-Freigabe.',
  'SKR unlocks in 1 hour': 'SKR wird in 1 Stunde freigegeben',
  'Your pending SKR is approaching its withdrawable time.': 'Ihre wartenden SKR sind bald auszahlbar.',
  'Your SKR is now withdrawable': 'Ihre SKR sind jetzt auszahlbar',
  'Open SKR Eyes to verify the finalized position and evidence.': 'Öffnen Sie SKR Eyes, um die finalisierte Position und die Belege zu prüfen.',
  'SKR Eyes alerts are ready': 'Die Hinweise von SKR Eyes sind bereit',
  'Test complete. Real unlock alerts will use finalized on-chain time.': 'Test abgeschlossen. Echte Freigabe-Hinweise nutzen die finalisierte On-Chain-Zeit.',

  // Stake-Fenster
  'Add to your position': 'Zur Position hinzufügen',
  'Amount per transaction': 'Betrag pro Transaktion',
  'SKR has six decimal places. Shorten the amount — the extra digits cannot be staked.': 'SKR hat sechs Nachkommastellen. Kürzen Sie den Betrag, die überzähligen Stellen lassen sich nicht staken.',
  'A single transaction cannot stake less than 1 SKR.': 'Eine einzelne Transaktion kann nicht weniger als 1 SKR staken.',
  'This is what one transaction stakes. The total is this amount times the count below.': 'So viel stakt eine Transaktion. Die Summe ist dieser Betrag mal die Anzahl unten.',
  'How many transactions': 'Wie viele Transaktionen',
  'One transaction, one wallet approval.': 'Eine Transaktion, eine Freigabe in der Wallet.',
  '{count} identical transactions from one approval, sent one after another. Each one is a separate on-chain stake.': '{count} identische Transaktionen aus einer Freigabe, nacheinander gesendet. Jede ist ein eigener Stake auf der Chain.',
  'This needs {needed} SKR and you hold {held}. ': 'Dafür braucht es {needed} SKR, Sie halten {held}. ',
  'At this amount you can send 1 part.': 'Bei diesem Betrag können Sie 1 Teil senden.',
  'At this amount you can send {count} parts.': 'Bei diesem Betrag können Sie {count} Teile senden.',
  'Lower the amount to stake what you have.': 'Senken Sie den Betrag, um zu staken, was Sie haben.',
  'You hold {held} SKR.': 'Sie halten {held} SKR.',
  'Before you sign': 'Vor dem Signieren',
  'sent as': 'gesendet als',
  'you stake in total': 'Sie staken insgesamt',
  'position account rent': 'Rent für das Positionskonto',
  'already paid': 'bereits bezahlt',
  '{sol} SOL, once': '{sol} SOL, einmalig',
  'Your position account already exists, so only the network fee applies — a few thousand lamports per transaction.': 'Ihr Positionskonto existiert bereits, also fällt nur die Netzwerkgebühr an, ein paar tausend Lamports pro Transaktion.',
  'The first stake creates your position account and its rent stays with the account. Network fees are a few thousand lamports per transaction.': 'Der erste Stake legt Ihr Positionskonto an, und die Rent bleibt beim Konto. Die Netzwerkgebühr beträgt ein paar tausend Lamports pro Transaktion.',
  'Working…': 'Läuft…',
  'At least 1 SKR per transaction': 'Mindestens 1 SKR pro Transaktion',
  'Sign and stake {amount} SKR': '{amount} SKR signieren und staken',
  'Sign and stake': 'Signieren und staken',
  'All parts landed': 'Alle Teile angekommen',
  'Stopped': 'Gestoppt',
  'Approve in your wallet': 'In der Wallet freigeben',
  'Preparing transactions': 'Transaktionen werden vorbereitet',
  'A run from before': 'Ein Durchlauf von vorhin',
  'Landing on chain': 'Landet auf der Chain',
  'pending': 'ausstehend',
  'sending': 'wird gesendet',
  'sent': 'gesendet',
  'confirmed': 'bestätigt',
  'unknown': 'unbekannt',
  'failed': 'fehlgeschlagen',
  'We do not know yet': 'Noch nicht bekannt',
  'What happened': 'Was passiert ist',
  'Ask the chain again': 'Chain erneut fragen',
  'Stake again': 'Erneut staken',
  'Discard and start over': 'Verwerfen und neu beginnen',
  'Start over': 'Neu beginnen',
  'Close': 'Schließen',
};
