// Español. La clave es la frase inglesa tal como está en el código.
//
// Reglas de esta tabla: lenguaje llano, sin palabras de marketing ni signos de
// exclamación, tuteo. Los tickers (SKR, SOL), el nombre de la cartera
// (Seed Vault) y el nombre de la app quedan en su forma original. Los números
// llegan ya formateados: las llaves se mueven, nunca se cambian.
//
// Una frase en español ocupa cerca de un tercio más que en inglés, así que las
// etiquetas de las fichas y los botones van más cortas que la traducción
// literal.

export const es: Record<string, string> = {
  'over the last 7 days': 'en los últimos 7 días',
  'over the last 30 days': 'en los últimos 30 días',
  '{percent}% of all SKR is staked': 'el {percent}% de todo el SKR está en stake',
  'over the last 24 hours': 'en las últimas 24 horas',
  'net': 'neto',
  'wallets': 'carteras',
  // Pestañas e indicador de frescura
  'Pulse': 'Pulso',
  'Flow': 'Flujo',
  'Me': 'Yo',
  'Queue': 'Cola',
  'Alerts': 'Avisos',
  'fresh': 'al día',
  'aging': 'envejece',
  'stale': 'caducado',
  'unavailable': 'sin datos',
  'syncing': 'sincroniza',
  'every number has a receipt': 'cada número tiene su comprobante',

  // Pulso
  'Waiting for a finalized answer': 'Esperando una respuesta confirmada',
  'Reading the vault': 'Leyendo la bóveda',
  'Network unavailable': 'Sin red',
  'Last 24 hours': 'Últimas 24 horas',
  'Last 7 days': 'Últimos 7 días',
  'Last 30 days': 'Últimos 30 días',
  'staked': 'en stake',
  'asked out': 'pidió salir',
  'history covers {days}d': 'historial de {days} d',
  'In cooldown': 'Enfriando',
  '{count} positions waiting out the 48 hours': '{count} posiciones esperando sus 48 horas',
  'Ready to exit': 'Listo para salir',
  'Cooldown finished, not yet withdrawn': 'Enfriamiento terminado, aún sin retirar',
  'When the queue matures': 'Cuándo vence la cola',
  'ready': 'listo',

  // Cola
  'Ready to withdraw': 'Listo para retirar',
  '{amount} SKR is still cooling down across {count} positions': 'Aún hay {amount} SKR enfriando en {count} posiciones',
  'Reading the queue': 'Leyendo la cola',
  'Time to maturity': 'Tiempo hasta el vencimiento',
  'Exits in flight, soonest first': 'Salidas en curso, las más próximas primero',
  '{count} shown': '{count} en pantalla',
  'Nothing is queued to leave right now.': 'Ahora mismo no hay nada en cola para salir.',

  // Flujo
  'Live from the vault': 'En directo desde la bóveda',
  'Reconnecting': 'Reconectando',
  'BUZZ ON': 'VIBRA SÍ',
  'BUZZ OFF': 'VIBRA NO',
  'SOUND ON': 'SONIDO SÍ',
  'SOUND OFF': 'SONIDO NO',
  'Biggest seen today': 'Lo más grande de hoy',
  'Last big move': 'Último movimiento grande',
  '{age} ago': 'hace {age}',
  'slot {slot}': 'slot {slot}',
  'amount unavailable': 'importe no disponible',
  'withdrew': 'retiró',
  'cancelled exit': 'canceló la salida',
  'stake': 'stake',
  'unstake': 'salida',
  'withdraw': 'retiro',
  'Fold the older large moves': 'Plegar los movimientos grandes anteriores',
  '1 more large move': '1 movimiento grande más',
  '{count} more large moves': '{count} movimientos grandes más',
  '{count} landed while you watched': '{count} llegaron mientras mirabas',
  'Watching the chain': 'Mirando la cadena',
  'While you were away': 'Mientras no estabas',
  'One large move landed': 'Llegó 1 movimiento grande',
  '{count} large moves landed': 'Llegaron {count} movimientos grandes',
  ', the biggest {amount} SKR {verb}': ', el mayor de {amount} SKR {verb}',
  'ALL': 'TODO',
  'only {amount} SKR and up': 'solo desde {amount} SKR',
  'everything, dust included': 'todo, polvo incluido',
  'Waiting for the next finalized event of this size.': 'Esperando el próximo evento confirmado de este tamaño.',

  // Yo — perfil y tarjeta
  'Leaving': 'Saliendo',
  '{count} position(s) in cooldown': '{count} posición(es) enfriando',
  'Ready now': 'Listo ya',
  'Next unlock': 'Próximo desbloqueo',
  'Cooldown finished': 'Enfriamiento terminado',
  'Until this position is free': 'Hasta que esta posición quede libre',
  'Nothing queued': 'Nada en cola',
  'Your weight in the vault': 'Tu peso en la bóveda',
  'First stake {days} days ago, read from the oldest signature on your position account.': 'Primer stake hace {days} días, leído de la firma más antigua de tu cuenta de posición.',
  'Held at least {days} days. Your position has a long signature history, so the walk back is still going.': 'Al menos {days} días. Tu posición tiene un historial de firmas largo, así que el recorrido hacia atrás sigue en marcha.',
  'Reading the age of your position from the chain…': 'Leyendo en la cadena la edad de tu posición…',
  'Stake SKR': 'Hacer stake de SKR',
  'Drawing your card…': 'Dibujando tu tarjeta…',
  'Share your card': 'Comparte tu tarjeta',
  'Alerts armed': 'Avisos puestos',
  'Wake me at unlock': 'Despiértame al desbloqueo',
  'Refresh': 'Actualizar',
  'Disconnect': 'Desconectar',
  'This address holds no SKR position right now.': 'Esta dirección no tiene ninguna posición de SKR ahora mismo.',
  'Connect the wallet that holds your stake, or paste any public address. Nothing is signed.': 'Conecta la cartera que tiene tu stake, o pega cualquier dirección pública. No se firma nada.',
  'Connect Solana Mobile': 'Conectar Solana Mobile',
  'OR': 'O',
  'Paste a Solana address': 'Pega una dirección de Solana',
  'Look up': 'Buscar',
  'WEIGHT': 'PESO',
  'POSITIONS': 'POSICIONES',
  'READ FROM': 'LEÍDO DE',
  'Connect the wallet that holds your stake to fill this card in.': 'Conecta la cartera que tiene tu stake y la tarjeta se rellenará.',
  '1 unlock alert armed on this phone.': '1 aviso de desbloqueo puesto en este teléfono.',
  '{count} unlock alerts armed on this phone.': '{count} avisos de desbloqueo puestos en este teléfono.',
  'Nothing left to wait for — the cooldown is already over.': 'No queda nada que esperar: el enfriamiento ya terminó.',
  'Caption copied. Paste it next to the picture.': 'Texto copiado. Pégalo junto a la imagen.',
  'This phone would not take the caption — type it yourself.': 'Este teléfono no aceptó el texto: escríbelo tú.',
  'Your SKR staker card': 'Tu tarjeta de staker de SKR',
  'This phone has nothing to share with.': 'Este teléfono no tiene con qué compartir.',

  // Errores que la persona llega a ver
  'The finalized snapshot is still warming up. Try again in a moment.': 'La instantánea confirmada todavía se está preparando. Prueba en un momento.',
  'This position could not be read': 'No se pudo leer esta posición',
  'The wallet request was cancelled': 'Se canceló la petición a la cartera',
  'The wallet did not return an account.': 'La cartera no devolvió ninguna cuenta.',
  'Alerts could not be scheduled': 'No se pudieron programar los avisos',
  'The card is not ready yet': 'La tarjeta aún no está lista',
  'The card could not be drawn': 'No se pudo dibujar la tarjeta',
  'the chain returned no signatures': 'la cadena no devolvió firmas',
  'age lookup failed': 'falló la consulta de la edad',
  'SKR Eyes API returned {status}': 'La API de SKR Eyes respondió {status}',
  'The age service answered {status}': 'El servicio de edad respondió {status}',

  // Pantalla de avisos
  'Notifications allowed': 'Notificaciones permitidas',
  'Notifications off': 'Notificaciones desactivadas',
  'Alerts are scheduled on the phone itself. Nothing about you leaves the device.': 'Los avisos los programa el propio teléfono. Nada tuyo sale del dispositivo.',
  'Allow notifications and this app can wake you exactly when your cooldown ends.': 'Permite las notificaciones y la app podrá despertarte justo cuando termine tu enfriamiento.',
  'Allow notifications': 'Permitir notificaciones',
  'Open settings': 'Abrir ajustes',
  'This phone can now wake you.': 'Ahora este teléfono puede despertarte.',
  'Android will not ask again. Turn notifications on for SKR Eyes in the system settings.': 'Android no volverá a preguntar. Activa las notificaciones de SKR Eyes en los ajustes del sistema.',
  'Android is holding notifications back for this app.': 'Android está reteniendo las notificaciones de esta app.',
  'Android did not answer the permission request. Try again, or turn notifications on in the system settings.': 'Android no respondió a la petición de permiso. Inténtalo otra vez o activa las notificaciones en los ajustes del sistema.',
  'This phone would not open its settings screen.': 'Este teléfono no abrió su pantalla de ajustes.',
  'Wake me at my unlock': 'Despiértame en mi desbloqueo',
  'Connect your wallet on the Me screen and this switch becomes live.': 'Conecta tu cartera en la pestaña Yo y este interruptor se activará.',
  'One hour before, and again the moment the cooldown ends. Scheduled by this phone from the exact on-chain time.': 'Una hora antes y otra vez en el momento en que termina el enfriamiento. Lo programa este teléfono con la hora exacta de la cadena.',
  'Nothing of yours is unlocking, so there is nothing to wake you for yet.': 'No tienes nada desbloqueándose, así que todavía no hay por qué despertarte.',
  'Large moves while you were away': 'Movimientos grandes mientras no estabas',
  'Anything above the threshold below is summed up at the top of Flow when you come back to it, and lands with a chime and a buzz while you are watching.': 'Todo lo que supere el umbral de abajo se resume arriba en Flujo cuando vuelvas, y mientras miras llega con un sonido y una vibración.',
  "Waking the phone for someone else's large move while the app is closed needs a background check that Android schedules on its own terms. That is the next version — promising it here before it exists would be the same lie this screen just removed.": 'Despertar el teléfono por el movimiento grande de otra persona con la app cerrada exige una comprobación en segundo plano que Android programa según sus propias reglas. Eso es la próxima versión: prometerlo aquí antes de que exista sería la misma mentira que esta pantalla acaba de quitar.',
  'What counts as large in Flow': 'Qué cuenta como grande en Flujo',
  'Built-in thresholds, used by the chime and the buzz on the Flow screen, until the server publishes its own.': 'Umbrales incorporados: rigen el sonido y la vibración de Flujo hasta que el servidor publique los suyos.',
  'These come from the server, move with real traffic, and drive the chime and the buzz on the Flow screen.': 'Estos vienen del servidor, se mueven con el tráfico real y mandan sobre el sonido y la vibración de Flujo.',
  'Send a test notification': 'Enviar una notificación de prueba',
  'A test notification will arrive in a few seconds.': 'La notificación de prueba llegará en unos segundos.',
  'The test notification could not be scheduled': 'No se pudo programar la notificación de prueba',
  '1 reminder set on this phone for your unlock.': '1 recordatorio puesto en este teléfono para tu desbloqueo.',
  '{count} reminders set on this phone for your unlock.': '{count} recordatorios puestos en este teléfono para tu desbloqueo.',
  'The reminders for your unlock were cancelled.': 'Se cancelaron los recordatorios de tu desbloqueo.',
  'The alert could not be changed.': 'No se pudo cambiar el aviso.',
  'Language': 'Idioma',
  'The app follows your phone until you choose here. The card you share stays in English, so it reads the same to everyone who sees it.': 'La app sigue el idioma del teléfono hasta que elijas aquí. La tarjeta que compartes se queda en inglés, para que la lea igual todo el que la vea.',

  // Las notificaciones mismas
  'This wallet has no pending SKR unlock.': 'Esta cartera no tiene ningún desbloqueo de SKR pendiente.',
  'SKR unlocks in 1 hour': 'SKR se desbloquea en 1 hora',
  'Your pending SKR is approaching its withdrawable time.': 'Tus SKR pendientes se acercan a su hora de retirada.',
  'Your SKR is now withdrawable': 'Ya puedes retirar tus SKR',
  'Open SKR Eyes to verify the finalized position and evidence.': 'Abre SKR Eyes para comprobar la posición confirmada y sus pruebas.',
  'SKR Eyes alerts are ready': 'Los avisos de SKR Eyes están listos',
  'Test complete. Real unlock alerts will use finalized on-chain time.': 'Prueba terminada. Los avisos reales usarán la hora confirmada de la cadena.',

  // Ventana de stake
  'Add to your position': 'Añadir a tu posición',
  'Amount per transaction': 'Importe por transacción',
  'SKR has six decimal places. Shorten the amount — the extra digits cannot be staked.': 'SKR tiene seis decimales. Acorta el importe: los dígitos de más no se pueden poner en stake.',
  'A single transaction cannot stake less than 1 SKR.': 'Una sola transacción no puede poner en stake menos de 1 SKR.',
  'This is what one transaction stakes. The total is this amount times the count below.': 'Esto es lo que pone en stake una transacción. El total es este importe por el número de abajo.',
  'How many transactions': 'Cuántas transacciones',
  'One transaction, one wallet approval.': 'Una transacción, una confirmación en la cartera.',
  '{count} identical transactions from one approval, sent one after another. Each one is a separate on-chain stake.': '{count} transacciones idénticas con una sola confirmación, enviadas una tras otra. Cada una es un stake independiente en la cadena.',
  'This needs {needed} SKR and you hold {held}. ': 'Hacen falta {needed} SKR y tú tienes {held}. ',
  'At this amount you can send 1 part.': 'Con este importe puedes enviar 1 parte.',
  'At this amount you can send {count} parts.': 'Con este importe puedes enviar {count} partes.',
  'Lower the amount to stake what you have.': 'Baja el importe para poner en stake lo que tienes.',
  'You hold {held} SKR.': 'Tienes {held} SKR.',
  'Before you sign': 'Antes de firmar',
  'sent as': 'se envía como',
  'you stake in total': 'pones en stake en total',
  'position account rent': 'renta de la cuenta de posición',
  'already paid': 'ya pagada',
  '{sol} SOL, once': '{sol} SOL, una vez',
  'Your position account already exists, so only the network fee applies — a few thousand lamports per transaction.': 'Tu cuenta de posición ya existe, así que solo pagas la comisión de red: unos miles de lamports por transacción.',
  'The first stake creates your position account and its rent stays with the account. Network fees are a few thousand lamports per transaction.': 'El primer stake crea tu cuenta de posición y su renta se queda en esa cuenta. La comisión de red son unos miles de lamports por transacción.',
  'Working…': 'Trabajando…',
  'At least 1 SKR per transaction': 'Mínimo 1 SKR por transacción',
  'Sign and stake {amount} SKR': 'Firmar y poner en stake {amount} SKR',
  'Sign and stake': 'Firmar y poner en stake',
  'All parts landed': 'Todas las partes entraron',
  'Stopped': 'Detenido',
  'Approve in your wallet': 'Confirma en tu cartera',
  'Preparing transactions': 'Preparando transacciones',
  'A run from before': 'Un envío de antes',
  'Landing on chain': 'Entrando en la cadena',
  'pending': 'pendiente',
  'sending': 'enviando',
  'sent': 'enviada',
  'confirmed': 'confirmada',
  'unknown': 'desconocido',
  'failed': 'falló',
  'We do not know yet': 'Todavía no lo sabemos',
  'What happened': 'Qué pasó',
  'Ask the chain again': 'Preguntar otra vez a la cadena',
  'Stake again': 'Hacer stake otra vez',
  'Discard and start over': 'Descartar y empezar de nuevo',
  'Start over': 'Empezar de nuevo',
  'Close': 'Cerrar',
};
