// Español. La clave es la frase inglesa tal como está en el código.
//
// Reglas de esta tabla: lenguaje llano, sin palabras de marketing ni signos de
// exclamación, tuteo. Los tickers (SKR, SOL), el nombre de la cartera
// (Seed Vault) y el nombre de la app quedan en su forma original. Los números
// llegan ya formateados: las llaves se mueven, nunca se cambian.
//
// Una frase en español ocupa cerca de un tercio más que en inglés, así que las
// etiquetas de las fichas y los botones van más cortas que la traducción
// literal.

export const es: Record<string, string> = {
  'Vault': 'Bóveda',
  'over the last 7 days': 'en los últimos 7 días',
  'over the last 30 days': 'en los últimos 30 días',
  '{percent}% of all SKR is staked': 'el {percent}% de todo el SKR está en stake',
  'over the last 24 hours': 'en las últimas 24 horas',
  'net': 'neto',
  'wallets': 'carteras',
  // Pestañas e indicador de frescura
  'Flow': 'Flujo',
  'Me': 'Yo',
  'Queue': 'Cola',
  'Alerts': 'Avisos',
  'fresh': 'al día',
  'aging': 'con retraso',
  'stale': 'caducado',
  'unavailable': 'sin datos',
  'syncing': 'sincronizando',
  'every number has a receipt': 'cada número tiene su comprobante',

  // Pulso (la bóveda)
  'Waiting for a finalized answer': 'Esperando una respuesta confirmada',
  'Reading the vault': 'Leyendo la bóveda',
  'Network unavailable': 'Sin red',
  'Last 24 hours': 'Últimas 24 horas',
  'Last 7 days': 'Últimos 7 días',
  'Last 30 days': 'Últimos 30 días',
  '24h': '24 h',
  'staked': 'en stake',
  'in': 'entró',
  'asked out': 'pidió salir',
  'staked minus requested out': 'stake menos salidas pedidas',
  'history covers {days}d': 'historial de {days} d',
  'In cooldown': 'En enfriamiento',
  '{count} positions waiting out the 48 hours': '{count} posiciones esperando sus 48 horas',
  'Ready to exit': 'Listo para salir',
  'Cooldown finished, not yet withdrawn': 'Enfriamiento terminado, aún sin retirar',
  'When the queue matures': 'Cuándo vence la cola',
  'ready': 'listo',
  'cooling down': 'en enfriamiento',
  'ready to withdraw': 'listo para retirar',
  'Motion': 'Animación',
  'The vault stands still.': 'La bóveda se queda quieta.',
  'One gentle frame a second.': 'Un cuadro suave por segundo.',
  'Live while you watch. Calm after 90 seconds without a touch.': 'En vivo mientras miras. En calma tras 90 segundos sin tocar la pantalla.',
  'Receipt': 'Comprobante',
  'Open on Solscan': 'Abrir en Solscan',

  // Cola
  'Exits in flight, soonest first': 'Salidas en curso, las más próximas primero',
  '{count} shown': '{count} en pantalla',
  'Show all {count}': 'Ver todo ({count})',
  'Show fewer': 'Ver menos',
  'Nothing is queued to leave right now.': 'Ahora mismo no hay nada en cola para salir.',

  // Flujo
  'Live from the vault': 'En vivo desde la bóveda',
  'Reconnecting': 'Reconectando',
  'BUZZ ON': 'VIBRACIÓN',
  'BUZZ OFF': 'SIN VIBRACIÓN',
  'SOUND ON': 'SONIDO',
  'SOUND OFF': 'SIN SONIDO',
  'Biggest seen today': 'Lo más grande de hoy',
  'Biggest stake today': 'Mayor stake de hoy',
  'Biggest exit today': 'Mayor salida de hoy',
  'Biggest withdrawal today': 'Mayor retiro de hoy',
  'Last big move': 'Último movimiento grande',
  '{age} ago': 'hace {age}',
  'slot {slot}': 'slot {slot}',
  'amount unavailable': 'importe no disponible',
  'withdrew': 'retiró',
  'cancelled exit': 'canceló la salida',
  'stake': 'stake',
  'unstake': 'salida',
  'withdraw': 'retiro',
  'Fold the older large moves': 'Ocultar los movimientos grandes anteriores',
  '1 more large move': '1 movimiento grande más',
  '{count} more large moves': '{count} movimientos grandes más',
  '{count} landed while you watched': '{count} llegaron mientras mirabas',
  'Watching the chain': 'Observando la cadena',
  'ALL': 'TODO',
  'only {amount} SKR and up': 'solo desde {amount} SKR',
  'everything, dust included': 'todo, polvo incluido',
  'Waiting for the next finalized event of this size.': 'Esperando el próximo evento confirmado de este tamaño.',

  // Yo: perfil y tarjeta
  'Leaving': 'Saliendo',
  '1 position in cooldown': '1 posición en enfriamiento',
  '{count} positions in cooldown': '{count} posiciones en enfriamiento',
  'Ready now': 'Listo ahora',
  'Next unlock': 'Próximo desbloqueo',
  'Cooldown finished': 'Enfriamiento terminado',
  'Until this position is free': 'Hasta que esta posición quede libre',
  'Nothing queued': 'Nada en cola',
  'Your weight in the vault': 'Tu peso en la bóveda',
  'First stake {days} days ago, read from the oldest signature on your position account.': 'Primer stake hace {days} días, leído de la firma más antigua de tu cuenta de posición.',
  'Held at least {days} days. Your position has a long signature history, so the walk back is still going.': 'Al menos {days} días en stake. Tu posición tiene un historial de firmas largo, así que la lectura hacia atrás sigue en marcha.',
  'Reading the age of your position from the chain…': 'Leyendo en la cadena la edad de tu posición…',
  'Stake SKR': 'Hacer stake de SKR',
  'Drawing your card…': 'Dibujando tu tarjeta…',
  'Share your card': 'Compartir tu tarjeta',
  'Alerts armed': 'Avisos activos',
  'Wake me at unlock': 'Avísame al desbloqueo',
  'Refresh': 'Actualizar',
  'Disconnect': 'Desconectar',
  'This address holds no SKR position right now.': 'Esta dirección no tiene ninguna posición de SKR ahora mismo.',
  'This wallet holds no SKR position yet. The first stake opens one; the position account costs a little rent once.': 'Esta cartera aún no tiene ninguna posición de SKR. El primer stake abre una; la cuenta de posición paga una pequeña renta una sola vez.',
  'This position is being looked at, not signed for. Connect the wallet that holds it to stake from it.': 'Esta posición solo se está consultando, no se firma con ella. Conecta la cartera que la tiene para hacer stake desde ella.',
  'Connect the wallet that holds your stake, or paste any public address. Nothing is signed.': 'Conecta la cartera que tiene tu stake, o pega cualquier dirección pública. No se firma nada.',
  'Connect Solana Mobile': 'Conectar Solana Mobile',
  'OR': 'O',
  'Paste a Solana address': 'Pega una dirección de Solana',
  'Look up': 'Buscar',
  'WEIGHT': 'PESO',
  'POSITIONS': 'POSICIONES',
  'READ FROM': 'LEÍDO DE',
  '1 unlock alert armed on this phone.': '1 aviso de desbloqueo activo en este teléfono.',
  '{count} unlock alerts armed on this phone.': '{count} avisos de desbloqueo activos en este teléfono.',
  'Nothing left to wait for — the cooldown is already over.': 'No queda nada que esperar: el enfriamiento ya terminó.',
  'Caption copied. Paste it next to the picture.': 'Texto copiado. Pégalo junto a la imagen.',
  'This phone would not take the caption — type it yourself.': 'Este teléfono no aceptó el texto: escríbelo tú.',
  'Your SKR staker card': 'Tu tarjeta de staker de SKR',
  'This phone has nothing to share with.': 'Este teléfono no tiene con qué compartir.',
  'Hide my name on the card': 'Ocultar mi nombre en la tarjeta',
  'Hide my amount on the card': 'Ocultar mi importe en la tarjeta',
  'The eye in the ring closes and the card says A Seeker.': 'El ojo del anillo se cierra y la tarjeta dice "A Seeker".',
  'Days, since and one-of stay; the position line goes.': 'Se quedan los días, la fecha de inicio y el "una de"; la línea de la posición se va.',
  'An exact amount next to a start date is close to a fingerprint. Your choice, said plainly.': 'Un importe exacto junto a una fecha de inicio es casi una huella digital. Tú decides, dicho sin rodeos.',

  // Los dieciséis diarios
  'Sixteen': 'Dieciséis',
  'The daily sixteen': 'Los dieciséis diarios',
  '16 parts of 1 SKR, one approval. A small daily habit that keeps your position moving.': '16 partes de 1 SKR, una sola aprobación. Un pequeño hábito diario que mantiene tu posición en movimiento.',

  // Propina
  'Support SKR Eyes': 'Apoya a SKR Eyes',
  'Send a tip': 'Dar propina',
  'A tip in SKR': 'Una propina en SKR',
  'How much': 'Cuánto',
  'Any amount you like. Goes to {name}, the wallet behind this app.': 'El importe que quieras. Va a {name}, la cartera detrás de esta app.',
  'Send {amount} SKR to {name}': 'Enviar {amount} SKR a {name}',
  '{amount} SKR on its way to {name}': '{amount} SKR en camino a {name}',
  'Thank you': 'Gracias',
  'Done': 'Listo',
  'Landing on chain…': 'Llegando a la cadena…',
  'Your wallet signs and sends it. The app only fetches a blockhash before and reads the status after.': 'Tu cartera lo firma y lo envía. La app solo obtiene un blockhash antes y lee el estado después.',
  'A tip changes nothing about your position and nothing about any airdrop. It is a thank you, not a fee.': 'Una propina no cambia nada en tu posición ni en ningún airdrop. Es un agradecimiento, no una comisión.',
  'Free and open source, built by one Seeker. Tips in SKR go to kosa.skr and are staked right away, all of them.': 'Gratis y de código abierto, hecha por un Seeker. Las propinas en SKR van a kosa.skr y se ponen en stake de inmediato, todas.',
  'This app is free, open source, and built by one Seeker. If it saved you a moment, a tip is welcome. Every SKR that arrives is staked right away, all of it.': 'Esta app es gratis, de código abierto y hecha por un Seeker. Si te ahorró un momento, una propina es bienvenida. Cada SKR que llega se pone en stake de inmediato, todo.',
  'This is {name} itself. A tip to your own wallet moves nothing; try from another wallet.': 'Esta es la cartera {name}. Una propina a tu propia cartera no mueve nada; prueba desde otra.',
  'The chain rejected the transfer.': 'La cadena rechazó la transferencia.',
  'The wallet declined. Nothing was sent.': 'La cartera rechazó la operación. No se envió nada.',
  'The wallet returned no signature.': 'La cartera no devolvió ninguna firma.',
  'SKR has six decimal places. Shorten the amount.': 'SKR tiene seis decimales. Acorta el importe.',

  // Errores que la persona llega a ver
  'The finalized snapshot is still warming up. Try again in a moment.': 'La instantánea confirmada todavía se está preparando. Inténtalo en un momento.',
  'This position could not be read': 'No se pudo leer esta posición',
  'The wallet request was cancelled': 'Se canceló la solicitud a la cartera',
  'The wallet did not return an account.': 'La cartera no devolvió ninguna cuenta.',
  'Alerts could not be scheduled': 'No se pudieron programar los avisos',
  'The card is not ready yet': 'La tarjeta aún no está lista',
  'The card could not be drawn': 'No se pudo dibujar la tarjeta',
  'the chain returned no signatures': 'la cadena no devolvió firmas',
  'age lookup failed': 'falló la consulta de la edad',
  'SKR Eyes API returned {status}': 'La API de SKR Eyes respondió {status}',
  'The age service answered {status}': 'El servicio de edad respondió {status}',
  'The app was closed while the wallet had this stake. Check your position before staking again, then clear this.': 'La app se cerró mientras la cartera tenía este stake en curso. Revisa tu posición antes de volver a hacer stake y luego borra esto.',
  'The wallet that answered is not the one on screen. Connect the wallet that holds this position, then stake. Nothing was sent.': 'La cartera que respondió no es la que está en pantalla. Conecta la cartera que tiene esta posición y luego haz stake. No se envió nada.',

  // Pantalla de avisos
  'Notifications allowed': 'Notificaciones permitidas',
  'Notifications off': 'Notificaciones desactivadas',
  'Alerts are scheduled on the phone itself. Nothing about you leaves the device.': 'Los avisos los programa el propio teléfono. Nada tuyo sale del dispositivo.',
  'Allow notifications and this app can wake you exactly when your cooldown ends.': 'Permite las notificaciones y la app podrá avisarte justo cuando termine tu enfriamiento.',
  'Allow notifications': 'Permitir notificaciones',
  'Open settings': 'Abrir la configuración',
  'This phone can now wake you.': 'Ahora este teléfono puede avisarte.',
  'Android will not ask again. Turn notifications on for SKR Eyes in the system settings.': 'Android no volverá a preguntar. Activa las notificaciones de SKR Eyes en la configuración del sistema.',
  'Android is holding notifications back for this app.': 'Android está reteniendo las notificaciones de esta app.',
  'Android did not answer the permission request. Try again, or turn notifications on in the system settings.': 'Android no respondió a la solicitud de permiso. Inténtalo otra vez o activa las notificaciones en la configuración del sistema.',
  'This phone would not open its settings screen.': 'Este teléfono no abrió su pantalla de configuración.',
  'Wake me at my unlock': 'Avísame en mi desbloqueo',
  'Connect your wallet on the Me screen and this switch becomes live.': 'Conecta tu cartera en la pestaña Yo y este interruptor se activará.',
  'One hour before, and again the moment the cooldown ends. Scheduled by this phone from the exact on-chain time.': 'Una hora antes y otra vez en el momento en que termina el enfriamiento. Lo programa este teléfono con la hora exacta de la cadena.',
  'Nothing of yours is unlocking, so there is nothing to wake you for yet.': 'No tienes nada por desbloquear, así que todavía no hay de qué avisarte.',
  'Large moves, heard and felt': 'Movimientos grandes, para oír y sentir',
  'A stake of 1K SKR or more rings like a glass coin, a stake of 100K rings the vault bell, an exit of 100K lands with a low boom. On every screen while the app is open, each with a short buzz.': 'Un stake de 1K SKR o más suena como una moneda de cristal, un stake de 100K hace sonar la campana de la bóveda y una salida de 100K cae con un golpe grave. En todas las pantallas mientras la app está abierta, cada uno con una vibración corta.',
  "Other people's moves do not wake the phone while the app is closed. Only your own unlock does.": 'Los movimientos de otras personas no despiertan el teléfono con la app cerrada. Solo tu propio desbloqueo lo hace.',
  'What counts as large': 'Qué cuenta como grande',
  'Built-in thresholds behind the bell and the boom, until the server publishes its own.': 'Umbrales incorporados detrás de la campana y el golpe, hasta que el servidor publique los suyos.',
  'These come from the server, move with real traffic, and drive the bell and the boom.': 'Estos vienen del servidor, se mueven con el tráfico real y mandan sobre la campana y el golpe.',
  'Send a test notification': 'Enviar una notificación de prueba',
  'A test notification will arrive in a few seconds.': 'La notificación de prueba llegará en unos segundos.',
  'The test notification could not be scheduled': 'No se pudo programar la notificación de prueba',
  '1 reminder set on this phone for your unlock.': '1 recordatorio programado en este teléfono para tu desbloqueo.',
  '{count} reminders set on this phone for your unlock.': '{count} recordatorios programados en este teléfono para tu desbloqueo.',
  'The reminders for your unlock were cancelled.': 'Se cancelaron los recordatorios de tu desbloqueo.',
  'The alert could not be changed.': 'No se pudo cambiar el aviso.',
  'Language': 'Idioma',
  'The app follows your phone until you choose here. The card you share stays in English, so it reads the same to everyone who sees it.': 'La app sigue el idioma del teléfono hasta que elijas aquí. La tarjeta que compartes se queda en inglés, para que la lea igual todo el que la vea.',

  // Las notificaciones mismas
  'This wallet has no pending SKR unlock.': 'Esta cartera no tiene ningún desbloqueo de SKR pendiente.',
  'SKR unlocks in 1 hour': 'SKR se desbloquea en 1 hora',
  'Your pending SKR is approaching its withdrawable time.': 'Tu SKR pendiente ya casi se puede retirar.',
  'Your SKR is now withdrawable': 'Ya puedes retirar tu SKR',
  'Open SKR Eyes to verify the finalized position and evidence.': 'Abre SKR Eyes para comprobar la posición confirmada y sus pruebas.',
  'SKR Eyes alerts are ready': 'Los avisos de SKR Eyes están listos',
  'Test complete. Real unlock alerts will use finalized on-chain time.': 'Prueba terminada. Los avisos reales usarán la hora confirmada de la cadena.',

  // Ventana de stake
  'Add to your position': 'Añadir a tu posición',
  'Amount per transaction': 'Importe por transacción',
  'SKR has six decimal places. Shorten the amount — the extra digits cannot be staked.': 'SKR tiene seis decimales. Acorta el importe: los dígitos de más no se pueden poner en stake.',
  'A single transaction cannot stake less than 1 SKR.': 'Una sola transacción no puede poner en stake menos de 1 SKR.',
  'This is what one transaction stakes. The total is this amount times the count below.': 'Esto es lo que pone en stake una transacción. El total es este importe por el número de abajo.',
  'How many transactions': 'Cuántas transacciones',
  'One transaction, one wallet approval.': 'Una transacción, una aprobación en la cartera.',
  '{count} identical transactions from one approval, sent one after another. Each one is a separate on-chain stake.': '{count} transacciones idénticas con una sola aprobación, enviadas una tras otra. Cada una es un stake independiente en la cadena.',
  'This needs {needed} SKR and you hold {held}. ': 'Hacen falta {needed} SKR y tú tienes {held}. ',
  'At this amount you can send 1 part.': 'Con este importe puedes enviar 1 parte.',
  'At this amount you can send {count} parts.': 'Con este importe puedes enviar {count} partes.',
  'Lower the amount to stake what you have.': 'Baja el importe para poner en stake lo que tienes.',
  'You hold {held} SKR.': 'Tienes {held} SKR.',
  'Before you sign': 'Antes de firmar',
  'sent as': 'se envía como',
  'you stake in total': 'pones en stake en total',
  'position account rent': 'renta de la cuenta de posición',
  'already paid': 'ya pagada',
  '{sol} SOL, once': '{sol} SOL, una vez',
  'Your position account already exists, so only the network fee applies — a few thousand lamports per transaction.': 'Tu cuenta de posición ya existe, así que solo pagas la comisión de red: unos miles de lamports por transacción.',
  'The first stake creates your position account and its rent stays with the account. Network fees are a few thousand lamports per transaction.': 'El primer stake crea tu cuenta de posición y su renta se queda en esa cuenta. La comisión de red son unos miles de lamports por transacción.',
  'Working…': 'Procesando…',
  'At least 1 SKR per transaction': 'Mínimo 1 SKR por transacción',
  'Sign and stake {amount} SKR': 'Firmar y poner en stake {amount} SKR',
  'Sign and stake': 'Firmar y poner en stake',
  'All parts landed': 'Todas las partes llegaron',
  'Stopped': 'Detenido',
  'Approve in your wallet': 'Aprueba en tu cartera',
  'Preparing transactions': 'Preparando transacciones',
  'A run from before': 'Un envío anterior',
  'Landing on chain': 'Llegando a la cadena',
  'pending': 'pendiente',
  'sending': 'enviando',
  'sent': 'enviada',
  'confirmed': 'confirmada',
  'unknown': 'desconocido',
  'failed': 'falló',
  'We do not know yet': 'Todavía no lo sabemos',
  'What happened': 'Qué pasó',
  'Ask the chain again': 'Consultar la cadena otra vez',
  'Stake again': 'Hacer stake otra vez',
  'Discard and start over': 'Descartar y empezar de nuevo',
  'Start over': 'Empezar de nuevo',
  'Close': 'Cerrar',
};
