// Bahasa Indonesia. Kuncinya adalah kalimat bahasa Inggris di dalam kode.
//
// Aturan tabel ini: bahasa sederhana, tanpa kata pemasaran, tanpa tanda seru,
// sapaan "kamu". Kode token (SKR, SOL), nama dompet (Seed Vault), dan nama
// aplikasi tetap apa adanya. Angka sudah diformat sebelum masuk: kurung kurawal
// boleh dipindah, tidak boleh diganti.

export const id: Record<string, string> = {
  // Tab dan tanda kesegaran data
  'Pulse': 'Denyut',
  'Flow': 'Aliran',
  'Me': 'Saya',
  'Queue': 'Antrean',
  'Alerts': 'Pengingat',
  'fresh': 'terbaru',
  'aging': 'menua',
  'stale': 'basi',
  'unavailable': 'tidak ada',
  'syncing': 'menyelaraskan',
  'every number has a receipt': 'setiap angka punya buktinya',

  // Denyut
  'Staked of total supply': 'Di-stake dari total pasokan',
  '{percent}% of the {supply} SKR total supply · {positions} positions': '{percent}% dari total pasokan {supply} SKR · {positions} posisi',
  'Waiting for a finalized answer': 'Menunggu jawaban yang sudah final',
  'Reading the vault': 'Membaca brankas',
  'Network unavailable': 'Jaringan tidak tersedia',
  'Last 24 hours': '24 jam terakhir',
  'Last 7 days': '7 hari terakhir',
  'Last 30 days': '30 hari terakhir',
  '{amount} staked': '{amount} di-stake',
  '{amount} asked out': '{amount} minta keluar',
  'staked': 'di-stake',
  'asked out': 'minta keluar',
  '{count} wallets': '{count} dompet',
  'one bar per hour': 'satu batang per jam',
  '{range} as one total · daily bars need a server pass': '{range} sebagai satu total · batang harian dihitung server',
  '{sign}{amount} net': 'bersih {sign}{amount}',
  'history covers {days}d': 'riwayat {days} hari',
  'In cooldown': 'Masa tunggu',
  '{count} positions waiting out the 48 hours': '{count} posisi sedang menunggu 48 jamnya',
  'Ready to exit': 'Siap keluar',
  'Cooldown finished, not yet withdrawn': 'Masa tunggu selesai, belum ditarik',
  'When the queue matures': 'Kapan antrean jatuh tempo',
  'ready': 'siap',

  // Antrean
  'Ready to withdraw': 'Siap ditarik',
  '{amount} SKR is still cooling down across {count} positions': 'Masih ada {amount} SKR dalam masa tunggu di {count} posisi',
  'Reading the queue': 'Membaca antrean',
  'Time to maturity': 'Waktu sampai jatuh tempo',
  'Exits in flight, soonest first': 'Penarikan yang sedang berjalan, terdekat di atas',
  '{count} shown': '{count} ditampilkan',
  'Nothing is queued to leave right now.': 'Saat ini tidak ada yang mengantre untuk keluar.',

  // Aliran
  'Live from the vault': 'Langsung dari brankas',
  'Reconnecting': 'Menyambung ulang',
  'BUZZ ON': 'GETAR NYALA',
  'BUZZ OFF': 'GETAR MATI',
  'SOUND ON': 'SUARA NYALA',
  'SOUND OFF': 'SUARA MATI',
  'Biggest seen today': 'Terbesar hari ini',
  'Last big move': 'Pergerakan besar terakhir',
  '{age} ago': '{age} lalu',
  'slot {slot}': 'slot {slot}',
  'amount unavailable': 'jumlah tidak terbaca',
  'withdrew': 'menarik',
  'cancelled exit': 'membatalkan keluar',
  'stake': 'stake',
  'unstake': 'keluar',
  'withdraw': 'tarik',
  'Fold the older large moves': 'Lipat pergerakan besar yang lama',
  '1 more large move': '1 pergerakan besar lagi',
  '{count} more large moves': '{count} pergerakan besar lagi',
  '{count} landed while you watched': '{count} masuk selagi kamu menonton',
  'Watching the chain': 'Mengawasi rantai',
  'While you were away': 'Selagi kamu pergi',
  'One large move landed': '1 pergerakan besar masuk',
  '{count} large moves landed': '{count} pergerakan besar masuk',
  ', the biggest {amount} SKR {verb}': ', yang terbesar {amount} SKR {verb}',
  'ALL': 'SEMUA',
  'only {amount} SKR and up': 'hanya {amount} SKR ke atas',
  'everything, dust included': 'semuanya, termasuk yang receh',
  'Waiting for the next finalized event of this size.': 'Menunggu transaksi final berikutnya sebesar ini.',

  // Saya — profil dan kartu
  'Leaving': 'Keluar',
  '{count} position(s) in cooldown': '{count} posisi dalam masa tunggu',
  'Ready now': 'Siap sekarang',
  'Next unlock': 'Pembukaan berikutnya',
  'Cooldown finished': 'Masa tunggu selesai',
  'Until this position is free': 'Sampai posisi ini bebas',
  'Nothing queued': 'Tidak ada antrean',
  'Your weight in the vault': 'Bobotmu di dalam brankas',
  'First stake {days} days ago, read from the oldest signature on your position account.': 'Stake pertama {days} hari lalu, dibaca dari tanda tangan tertua di akun posisimu.',
  'Held at least {days} days. Your position has a long signature history, so the walk back is still going.': 'Setidaknya {days} hari. Posisimu punya riwayat tanda tangan yang panjang, jadi penelusuran mundur masih berjalan.',
  'Reading the age of your position from the chain…': 'Membaca umur posisimu dari rantai…',
  'Stake SKR': 'Stake SKR',
  'Drawing your card…': 'Menggambar kartumu…',
  'Share your card': 'Bagikan kartumu',
  'Alerts armed': 'Pengingat aktif',
  'Wake me at unlock': 'Bangunkan saat terbuka',
  'Refresh': 'Segarkan',
  'Disconnect': 'Putuskan',
  'This address holds no SKR position right now.': 'Alamat ini sekarang tidak punya posisi SKR.',
  'Connect the wallet that holds your stake, or paste any public address. Nothing is signed.': 'Sambungkan dompet yang menyimpan stake-mu, atau tempel alamat publik mana pun. Tidak ada yang ditandatangani.',
  'Connect Solana Mobile': 'Sambungkan Solana Mobile',
  'OR': 'ATAU',
  'Paste a Solana address': 'Tempel alamat Solana',
  'Look up': 'Cari',
  'WEIGHT': 'BOBOT',
  'POSITIONS': 'POSISI',
  'READ FROM': 'DIBACA DARI',
  'Connect the wallet that holds your stake to fill this card in.': 'Sambungkan dompet yang menyimpan stake-mu supaya kartu ini terisi.',
  '1 unlock alert armed on this phone.': '1 pengingat pembukaan dipasang di ponsel ini.',
  '{count} unlock alerts armed on this phone.': '{count} pengingat pembukaan dipasang di ponsel ini.',
  'Nothing left to wait for — the cooldown is already over.': 'Tidak ada lagi yang ditunggu, masa tunggu sudah selesai.',
  'Caption copied. Paste it next to the picture.': 'Teks sudah disalin. Tempel di sebelah gambar.',
  'This phone would not take the caption — type it yourself.': 'Ponsel ini tidak menerima teksnya, ketik sendiri ya.',
  'Your SKR staker card': 'Kartu staker SKR-mu',
  'This phone has nothing to share with.': 'Ponsel ini tidak punya aplikasi untuk berbagi.',

  // Kesalahan yang benar-benar dilihat orang
  'The finalized snapshot is still warming up. Try again in a moment.': 'Rekaman final masih disiapkan. Coba lagi sebentar.',
  'This position could not be read': 'Posisi ini tidak bisa dibaca',
  'The wallet request was cancelled': 'Permintaan ke dompet dibatalkan',
  'The wallet did not return an account.': 'Dompet tidak mengembalikan akun.',
  'Alerts could not be scheduled': 'Pengingat tidak bisa dipasang',
  'The card is not ready yet': 'Kartunya belum siap',
  'The card could not be drawn': 'Kartunya tidak bisa digambar',
  'the chain returned no signatures': 'rantai tidak mengembalikan tanda tangan',
  'age lookup failed': 'pencarian umur gagal',
  'SKR Eyes API returned {status}': 'API SKR Eyes menjawab {status}',
  'The age service answered {status}': 'Layanan umur menjawab {status}',

  // Layar pengingat
  'Notifications allowed': 'Notifikasi diizinkan',
  'Notifications off': 'Notifikasi mati',
  'Alerts are scheduled on the phone itself. Nothing about you leaves the device.': 'Pengingat dipasang oleh ponsel itu sendiri. Tidak ada data tentangmu yang keluar dari perangkat.',
  'Allow notifications and this app can wake you exactly when your cooldown ends.': 'Izinkan notifikasi supaya aplikasi bisa membangunkanmu tepat saat masa tunggumu berakhir.',
  'Allow notifications': 'Izinkan notifikasi',
  'Open settings': 'Buka pengaturan',
  'This phone can now wake you.': 'Sekarang ponsel ini bisa membangunkanmu.',
  'Android will not ask again. Turn notifications on for SKR Eyes in the system settings.': 'Android tidak akan bertanya lagi. Nyalakan notifikasi SKR Eyes di pengaturan sistem.',
  'Android is holding notifications back for this app.': 'Android sedang menahan notifikasi aplikasi ini.',
  'Android did not answer the permission request. Try again, or turn notifications on in the system settings.': 'Android tidak menjawab permintaan izin. Coba lagi, atau nyalakan notifikasi di pengaturan sistem.',
  'This phone would not open its settings screen.': 'Ponsel ini tidak mau membuka layar pengaturannya.',
  'Wake me at my unlock': 'Bangunkan saat punyaku terbuka',
  'Connect your wallet on the Me screen and this switch becomes live.': 'Sambungkan dompetmu di tab Saya supaya sakelar ini aktif.',
  'One hour before, and again the moment the cooldown ends. Scheduled by this phone from the exact on-chain time.': 'Satu jam sebelumnya, lalu sekali lagi tepat saat masa tunggu berakhir. Dipasang oleh ponsel ini memakai waktu persis dari rantai.',
  'Nothing of yours is unlocking, so there is nothing to wake you for yet.': 'Tidak ada milikmu yang sedang terbuka, jadi belum ada alasan membangunkanmu.',
  'Large moves while you were away': 'Pergerakan besar selagi kamu pergi',
  'Anything above the threshold below is summed up at the top of Flow when you come back to it, and lands with a chime and a buzz while you are watching.': 'Semua yang melewati ambang di bawah akan diringkas di bagian atas tab Aliran saat kamu kembali, dan datang dengan bunyi serta getaran selagi kamu menonton.',
  "Waking the phone for someone else's large move while the app is closed needs a background check that Android schedules on its own terms. That is the next version — promising it here before it exists would be the same lie this screen just removed.": 'Membangunkan ponsel karena pergerakan besar orang lain saat aplikasi tertutup butuh pemeriksaan latar belakang yang jadwalnya ditentukan Android sendiri. Itu urusan versi berikutnya: menjanjikannya di sini sebelum ada sama saja dengan kebohongan yang baru saja dihapus dari layar ini.',
  'What counts as large in Flow': 'Apa yang dihitung besar di tab Aliran',
  'Built-in thresholds, used by the chime and the buzz on the Flow screen, until the server publishes its own.': 'Ambang bawaan, dipakai untuk bunyi dan getaran di layar Aliran, sampai server menerbitkan ambangnya sendiri.',
  'These come from the server, move with real traffic, and drive the chime and the buzz on the Flow screen.': 'Ambang ini datang dari server, bergerak mengikuti lalu lintas sebenarnya, dan mengatur bunyi serta getaran di layar Aliran.',
  'Send a test notification': 'Kirim notifikasi percobaan',
  'A test notification will arrive in a few seconds.': 'Notifikasi percobaan akan datang dalam beberapa detik.',
  'The test notification could not be scheduled': 'Notifikasi percobaan tidak bisa dipasang',
  '1 reminder set on this phone for your unlock.': '1 pengingat dipasang di ponsel ini untuk pembukaanmu.',
  '{count} reminders set on this phone for your unlock.': '{count} pengingat dipasang di ponsel ini untuk pembukaanmu.',
  'The reminders for your unlock were cancelled.': 'Pengingat pembukaanmu dibatalkan.',
  'The alert could not be changed.': 'Pengingat tidak bisa diubah.',
  'Language': 'Bahasa',
  'The app follows your phone until you choose here. The card you share stays in English, so it reads the same to everyone who sees it.': 'Aplikasi mengikuti bahasa ponsel sampai kamu memilih di sini. Kartu yang kamu bagikan tetap berbahasa Inggris, supaya semua orang yang melihatnya membaca hal yang sama.',

  // Notifikasinya sendiri
  'This wallet has no pending SKR unlock.': 'Dompet ini tidak punya SKR yang menunggu dibuka.',
  'SKR unlocks in 1 hour': 'SKR terbuka dalam 1 jam',
  'Your pending SKR is approaching its withdrawable time.': 'SKR-mu yang menunggu sudah mendekati waktu bisa ditarik.',
  'Your SKR is now withdrawable': 'SKR-mu sekarang bisa ditarik',
  'Open SKR Eyes to verify the finalized position and evidence.': 'Buka SKR Eyes untuk memeriksa posisi final dan buktinya.',
  'SKR Eyes alerts are ready': 'Pengingat SKR Eyes sudah siap',
  'Test complete. Real unlock alerts will use finalized on-chain time.': 'Percobaan selesai. Pengingat sungguhan akan memakai waktu final dari rantai.',

  // Jendela stake
  'Add to your position': 'Tambahkan ke posisimu',
  'Amount per transaction': 'Jumlah per transaksi',
  'SKR has six decimal places. Shorten the amount — the extra digits cannot be staked.': 'SKR punya enam angka di belakang koma. Pendekkan jumlahnya, angka lebihnya tidak bisa di-stake.',
  'A single transaction cannot stake less than 1 SKR.': 'Satu transaksi tidak bisa men-stake kurang dari 1 SKR.',
  'This is what one transaction stakes. The total is this amount times the count below.': 'Ini yang di-stake oleh satu transaksi. Totalnya jumlah ini dikali angka di bawah.',
  'How many transactions': 'Berapa transaksi',
  'One transaction, one wallet approval.': 'Satu transaksi, satu persetujuan di dompet.',
  '{count} identical transactions from one approval, sent one after another. Each one is a separate on-chain stake.': '{count} transaksi yang sama dari satu persetujuan, dikirim satu per satu. Masing-masing adalah stake tersendiri di rantai.',
  'This needs {needed} SKR and you hold {held}. ': 'Ini butuh {needed} SKR sedangkan kamu punya {held}. ',
  'At this amount you can send 1 part.': 'Dengan jumlah ini kamu bisa mengirim 1 bagian.',
  'At this amount you can send {count} parts.': 'Dengan jumlah ini kamu bisa mengirim {count} bagian.',
  'Lower the amount to stake what you have.': 'Turunkan jumlahnya supaya sesuai yang kamu punya.',
  'You hold {held} SKR.': 'Kamu punya {held} SKR.',
  'Before you sign': 'Sebelum kamu tanda tangan',
  'sent as': 'dikirim sebagai',
  'you stake in total': 'total yang kamu stake',
  'position account rent': 'sewa akun posisi',
  'already paid': 'sudah dibayar',
  '{sol} SOL, once': '{sol} SOL, sekali saja',
  'Your position account already exists, so only the network fee applies — a few thousand lamports per transaction.': 'Akun posisimu sudah ada, jadi yang dikenakan hanya biaya jaringan: beberapa ribu lamport per transaksi.',
  'The first stake creates your position account and its rent stays with the account. Network fees are a few thousand lamports per transaction.': 'Stake pertama membuat akun posisimu dan sewanya tetap ada di akun itu. Biaya jaringan beberapa ribu lamport per transaksi.',
  'Working…': 'Sedang bekerja…',
  'At least 1 SKR per transaction': 'Minimal 1 SKR per transaksi',
  'Sign and stake {amount} SKR': 'Tanda tangani dan stake {amount} SKR',
  'Sign and stake': 'Tanda tangani dan stake',
  'All parts landed': 'Semua bagian sudah masuk',
  'Stopped': 'Dihentikan',
  'Approve in your wallet': 'Setujui di dompetmu',
  'Preparing transactions': 'Menyiapkan transaksi',
  'A run from before': 'Kiriman dari sebelumnya',
  'Landing on chain': 'Sedang masuk ke rantai',
  'pending': 'menunggu',
  'sending': 'mengirim',
  'sent': 'terkirim',
  'confirmed': 'terkonfirmasi',
  'unknown': 'tidak diketahui',
  'failed': 'gagal',
  'We do not know yet': 'Kami belum tahu',
  'What happened': 'Apa yang terjadi',
  'Ask the chain again': 'Tanya rantai sekali lagi',
  'Stake again': 'Stake lagi',
  'Discard and start over': 'Buang dan mulai dari awal',
  'Start over': 'Mulai dari awal',
  'Close': 'Tutup',
};
