// 日本語。キーはコードに書かれている英語の文そのものです。
//
// この表の決まり: 素直なですます調、宣伝文句なし、感嘆符なし。ティッカー
// (SKR, SOL)、ウォレット名 (Seed Vault)、アプリ名はそのまま残します。数値は
// 整形済みで届くので、波かっこは位置を動かすだけで中身は変えません。

export const ja: Record<string, string> = {
  // タブと鮮度バッジ
  'Pulse': '脈',
  'Flow': '流れ',
  'Me': '自分',
  'Queue': '待ち行列',
  'Alerts': '通知',
  'fresh': '最新',
  'aging': 'やや古い',
  'stale': '古い',
  'unavailable': '取得不可',
  'syncing': '同期中',
  'every number has a receipt': 'すべての数字に裏づけがあります',

  // 脈
  'Staked of total supply': '総発行量のうちステーク済み',
  '{percent}% of the {supply} SKR total supply · {positions} positions': '総発行量 {supply} SKR の {percent}% · {positions} ポジション',
  'Waiting for a finalized answer': '確定した答えを待っています',
  'Reading the vault': '金庫を読んでいます',
  'Network unavailable': 'ネットワークに接続できません',
  'Last 24 hours': '直近 24 時間',
  'Last 7 days': '直近 7 日',
  'Last 30 days': '直近 30 日',
  '{amount} staked': '{amount} をステーク',
  '{amount} asked out': '{amount} が退出申請',
  'staked': 'ステーク',
  'asked out': '退出申請',
  '{count} wallets': 'ウォレット {count} 件',
  'one bar per hour': '1 時間に 1 本',
  '{range} as one total · daily bars need a server pass': '{range}をまとめて 1 本に · 日ごとの棒はサーバー側の計算が必要です',
  '{sign}{amount} net': '差引 {sign}{amount}',
  'history covers {days}d': '履歴は {days} 日分',
  'In cooldown': '冷却中',
  '{count} positions waiting out the 48 hours': '{count} 件のポジションが 48 時間を待っています',
  'Ready to exit': '退出できます',
  'Cooldown finished, not yet withdrawn': '冷却は終了、まだ引き出していません',
  'When the queue matures': '待ち行列が満了する時期',
  'ready': '可能',

  // 待ち行列
  'Ready to withdraw': '引き出せます',
  '{amount} SKR is still cooling down across {count} positions': 'まだ {count} 件のポジションで {amount} SKR が冷却中です',
  'Reading the queue': '待ち行列を読んでいます',
  'Time to maturity': '満了までの時間',
  'Exits in flight, soonest first': '進行中の退出、近い順',
  '{count} shown': '{count} 件表示',
  'Nothing is queued to leave right now.': 'いま退出待ちのものはありません。',

  // 流れ
  'Live from the vault': '金庫からの実況',
  'Reconnecting': '再接続しています',
  'BUZZ ON': '振動オン',
  'BUZZ OFF': '振動オフ',
  'SOUND ON': '音オン',
  'SOUND OFF': '音オフ',
  'Biggest seen today': '今日いちばん大きい取引',
  'Last big move': '直近の大きな動き',
  '{age} ago': '{age}前',
  'slot {slot}': 'スロット {slot}',
  'amount unavailable': '金額を取得できません',
  'withdrew': '引き出し',
  'cancelled exit': '退出を取り消し',
  'stake': 'ステーク',
  'unstake': '退出',
  'withdraw': '引き出し',
  'Fold the older large moves': '古い大きな動きをたたむ',
  '1 more large move': '大きな動きがあと 1 件',
  '{count} more large moves': '大きな動きがあと {count} 件',
  '{count} landed while you watched': '見ている間に {count} 件届きました',
  'Watching the chain': 'チェーンを見ています',
  'While you were away': '離れている間に',
  'One large move landed': '大きな動きが 1 件ありました',
  '{count} large moves landed': '大きな動きが {count} 件ありました',
  ', the biggest {amount} SKR {verb}': '、最大は {amount} SKR の{verb}',
  'ALL': 'すべて',
  'only {amount} SKR and up': '{amount} SKR 以上のみ',
  'everything, dust included': '少額も含めてすべて',
  'Waiting for the next finalized event of this size.': 'この規模で次に確定する取引を待っています。',

  // 自分 — プロフィールとカード
  'Leaving': '退出中',
  '{count} position(s) in cooldown': '{count} 件のポジションが冷却中',
  'Ready now': 'いま可能',
  'Next unlock': '次の解除',
  'Cooldown finished': '冷却が終わりました',
  'Until this position is free': 'このポジションが自由になるまで',
  'Nothing queued': '待ちはありません',
  'Your weight in the vault': '金庫の中での自分の比率',
  'First stake {days} days ago, read from the oldest signature on your position account.': '最初のステークは {days} 日前。ポジション口座のいちばん古い署名から読み取りました。',
  'Held at least {days} days. Your position has a long signature history, so the walk back is still going.': '少なくとも {days} 日保有。ポジションの署名履歴が長いため、さかのぼりはまだ続いています。',
  'Reading the age of your position from the chain…': 'チェーンからポジションの経過日数を読んでいます…',
  'Stake SKR': 'SKR をステークする',
  'Drawing your card…': 'カードを描いています…',
  'Share your card': 'カードを共有する',
  'Alerts armed': '通知を設定しました',
  'Wake me at unlock': '解除時に知らせる',
  'Refresh': '更新',
  'Disconnect': '接続を解除',
  'This address holds no SKR position right now.': 'このアドレスには現在 SKR のポジションがありません。',
  'Connect the wallet that holds your stake, or paste any public address. Nothing is signed.': 'ステークを持つウォレットを接続するか、任意の公開アドレスを貼り付けてください。署名は一切しません。',
  'Connect Solana Mobile': 'Solana Mobile を接続',
  'OR': 'または',
  'Paste a Solana address': 'Solana のアドレスを貼り付け',
  'Look up': '照会',
  'WEIGHT': '比率',
  'POSITIONS': 'ポジション',
  'READ FROM': '取得元',
  'Connect the wallet that holds your stake to fill this card in.': 'ステークを持つウォレットを接続すると、このカードが埋まります。',
  '1 unlock alert armed on this phone.': 'この端末に解除の通知を 1 件設定しました。',
  '{count} unlock alerts armed on this phone.': 'この端末に解除の通知を {count} 件設定しました。',
  'Nothing left to wait for — the cooldown is already over.': '待つものはありません。冷却はすでに終わっています。',
  'Caption copied. Paste it next to the picture.': '文面をコピーしました。画像のとなりに貼り付けてください。',
  'This phone would not take the caption — type it yourself.': 'この端末が文面を受け取れませんでした。ご自身で入力してください。',
  'Your SKR staker card': 'あなたの SKR ステーカーカード',
  'This phone has nothing to share with.': 'この端末には共有できるアプリがありません。',

  // 実際に目にするエラー
  'The finalized snapshot is still warming up. Try again in a moment.': '確定版の集計をまだ準備しています。少し待ってからお試しください。',
  'This position could not be read': 'このポジションを読み取れませんでした',
  'The wallet request was cancelled': 'ウォレットへの要求は取り消されました',
  'The wallet did not return an account.': 'ウォレットが口座を返しませんでした。',
  'Alerts could not be scheduled': '通知を設定できませんでした',
  'The card is not ready yet': 'カードはまだ準備できていません',
  'The card could not be drawn': 'カードを描けませんでした',
  'the chain returned no signatures': 'チェーンが署名を返しませんでした',
  'age lookup failed': '経過日数の照会に失敗しました',
  'SKR Eyes API returned {status}': 'SKR Eyes の API が {status} を返しました',
  'The age service answered {status}': '経過日数のサービスが {status} を返しました',

  // 通知の画面
  'Notifications allowed': '通知は許可されています',
  'Notifications off': '通知はオフです',
  'Alerts are scheduled on the phone itself. Nothing about you leaves the device.': '通知は端末自身が予約します。あなたに関する情報が端末の外に出ることはありません。',
  'Allow notifications and this app can wake you exactly when your cooldown ends.': '通知を許可すると、冷却が終わるちょうどその時にお知らせできます。',
  'Allow notifications': '通知を許可',
  'Open settings': '設定を開く',
  'This phone can now wake you.': 'この端末からお知らせできるようになりました。',
  'Android will not ask again. Turn notifications on for SKR Eyes in the system settings.': 'Android はもう確認してきません。システム設定で SKR Eyes の通知をオンにしてください。',
  'Android is holding notifications back for this app.': 'Android がこのアプリの通知を止めています。',
  'Android did not answer the permission request. Try again, or turn notifications on in the system settings.': 'Android が権限の要求に応答しませんでした。もう一度試すか、システム設定で通知をオンにしてください。',
  'This phone would not open its settings screen.': 'この端末が設定画面を開けませんでした。',
  'Wake me at my unlock': '自分の解除時に知らせる',
  'Connect your wallet on the Me screen and this switch becomes live.': '「自分」タブでウォレットを接続すると、このスイッチが使えるようになります。',
  'One hour before, and again the moment the cooldown ends. Scheduled by this phone from the exact on-chain time.': '1 時間前に一度、冷却が終わる瞬間にもう一度。チェーン上の正確な時刻をもとに、この端末が予約します。',
  'Nothing of yours is unlocking, so there is nothing to wake you for yet.': '解除されるものがないので、いまお知らせする用事はありません。',
  'Large moves while you were away': '離れている間の大きな動き',
  'Anything above the threshold below is summed up at the top of Flow when you come back to it, and lands with a chime and a buzz while you are watching.': '下のしきい値を超えたものは、「流れ」に戻ったとき画面の上にまとめて表示されます。見ている間は音と振動とともに届きます。',
  "Waking the phone for someone else's large move while the app is closed needs a background check that Android schedules on its own terms. That is the next version — promising it here before it exists would be the same lie this screen just removed.": 'アプリを閉じたまま他人の大きな動きで端末を起こすには、Android が自分の都合で予定するバックグラウンド確認が要ります。それは次のバージョンの話です。できていないうちにここで約束するのは、この画面がいま取り除いたばかりの嘘と同じことになります。',
  'What counts as large in Flow': '「流れ」で何を大きいとみなすか',
  'Built-in thresholds, used by the chime and the buzz on the Flow screen, until the server publishes its own.': '内蔵のしきい値です。サーバーが独自の値を公開するまで、「流れ」の音と振動はこれで決まります。',
  'These come from the server, move with real traffic, and drive the chime and the buzz on the Flow screen.': 'この値はサーバーから届き、実際の取引量に合わせて動き、「流れ」の音と振動を決めます。',
  'Send a test notification': 'テスト通知を送る',
  'A test notification will arrive in a few seconds.': 'テスト通知が数秒後に届きます。',
  'The test notification could not be scheduled': 'テスト通知を予約できませんでした',
  '1 reminder set on this phone for your unlock.': '解除に合わせて、この端末に通知を 1 件設定しました。',
  '{count} reminders set on this phone for your unlock.': '解除に合わせて、この端末に通知を {count} 件設定しました。',
  'The reminders for your unlock were cancelled.': '解除の通知を取り消しました。',
  'The alert could not be changed.': '通知を変更できませんでした。',
  'Language': '言語',
  'The app follows your phone until you choose here. The card you share stays in English, so it reads the same to everyone who sees it.': 'ここで選ぶまで、アプリは端末の言語に従います。共有するカードは英語のままなので、見る人みんなが同じように読めます。',

  // 通知そのもの
  'This wallet has no pending SKR unlock.': 'このウォレットには解除待ちの SKR がありません。',
  'SKR unlocks in 1 hour': '1 時間後に SKR が解除されます',
  'Your pending SKR is approaching its withdrawable time.': '待機中の SKR が引き出せる時刻に近づいています。',
  'Your SKR is now withdrawable': 'SKR を引き出せるようになりました',
  'Open SKR Eyes to verify the finalized position and evidence.': 'SKR Eyes を開いて、確定したポジションと裏づけを確認してください。',
  'SKR Eyes alerts are ready': 'SKR Eyes の通知の準備ができました',
  'Test complete. Real unlock alerts will use finalized on-chain time.': 'テストは完了です。本番の通知はチェーン上で確定した時刻を使います。',

  // ステーク画面
  'Add to your position': '自分のポジションに追加',
  'Amount per transaction': '1 回あたりの金額',
  'SKR has six decimal places. Shorten the amount — the extra digits cannot be staked.': 'SKR の小数は 6 桁までです。金額を短くしてください。あふれた桁はステークできません。',
  'A single transaction cannot stake less than 1 SKR.': '1 回の取引で 1 SKR 未満はステークできません。',
  'This is what one transaction stakes. The total is this amount times the count below.': 'これは 1 回の取引でステークする額です。合計はこの額に下の回数を掛けたものです。',
  'How many transactions': '取引の回数',
  'One transaction, one wallet approval.': '取引 1 回、ウォレットでの承認 1 回。',
  '{count} identical transactions from one approval, sent one after another. Each one is a separate on-chain stake.': '1 回の承認で同じ取引を {count} 件、続けて送ります。どれもチェーン上では別々のステークです。',
  'This needs {needed} SKR and you hold {held}. ': 'これには {needed} SKR が必要ですが、残高は {held} です。',
  'At this amount you can send 1 part.': 'この金額なら 1 件送れます。',
  'At this amount you can send {count} parts.': 'この金額なら {count} 件送れます。',
  'Lower the amount to stake what you have.': '残高に合わせて金額を下げてください。',
  'You hold {held} SKR.': '残高は {held} SKR です。',
  'Before you sign': '署名する前に',
  'sent as': '送り方',
  'you stake in total': '合計ステーク額',
  'position account rent': 'ポジション口座の維持費',
  'already paid': '支払い済み',
  '{sol} SOL, once': '{sol} SOL、一度だけ',
  'Your position account already exists, so only the network fee applies — a few thousand lamports per transaction.': 'ポジション口座はすでにあるので、かかるのはネットワーク手数料だけです。1 回あたり数千ランポートです。',
  'The first stake creates your position account and its rent stays with the account. Network fees are a few thousand lamports per transaction.': '最初のステークでポジション口座がつくられ、その維持費は口座に残ります。ネットワーク手数料は 1 回あたり数千ランポートです。',
  'Working…': '処理中…',
  'At least 1 SKR per transaction': '1 回につき最低 1 SKR',
  'Sign and stake {amount} SKR': '署名して {amount} SKR をステーク',
  'Sign and stake': '署名してステーク',
  'All parts landed': 'すべてチェーンに載りました',
  'Stopped': '停止しました',
  'Approve in your wallet': 'ウォレットで承認してください',
  'Preparing transactions': '取引を準備しています',
  'A run from before': '前回の途中の処理',
  'Landing on chain': 'チェーンに載せています',
  'pending': '待機',
  'sending': '送信中',
  'sent': '送信済み',
  'confirmed': '確定',
  'unknown': '不明',
  'failed': '失敗',
  'We do not know yet': 'まだ分かりません',
  'What happened': '何が起きたか',
  'Ask the chain again': 'チェーンにもう一度尋ねる',
  'Stake again': 'もう一度ステークする',
  'Discard and start over': '破棄してやり直す',
  'Start over': 'やり直す',
  'Close': '閉じる',
};
