// 日本語。キーはコードに書かれている英語の文そのものです。
//
// この表の決まり: 素直なですます調、宣伝文句なし、感嘆符なし。ティッカー
// (SKR, SOL)、ウォレット名 (Seed Vault)、アプリ名、Solscan、.skr 名はそのまま
// 残します。数値は整形済みで届くので、波かっこは位置を動かすだけで中身は
// 変えません。

export const ja: Record<string, string> = {
  'Vault': '金庫',
  'over the last 7 days': '直近 7 日',
  'over the last 30 days': '直近 30 日',
  '{percent}% of all SKR is staked': '全 SKR の {percent}% がステーク中',
  'over the last 24 hours': '直近 24 時間',
  'net': '差引',
  'staked minus requested out': 'ステークから退出申請を引いた値',
  'wallets': 'ウォレット',
  'in': '流入',
  '24h': '24h',
  // タブと鮮度バッジ
  'Pulse': '鼓動',
  'Flow': '流れ',
  'Me': '自分',
  'Queue': '待ち行列',
  'Alerts': '通知',
  'fresh': '最新',
  'aging': 'やや古い',
  'stale': '古い',
  'unavailable': '取得不可',
  'syncing': '同期中',
  'every number has a receipt': 'すべての数字に裏づけがあります',

  // 金庫の場面
  'Waiting for a finalized answer': '確定した答えを待っています',
  'Reading the vault': '金庫を読んでいます',
  'Network unavailable': 'ネットワークに接続できません',
  'Last 24 hours': '直近 24 時間',
  'Last 7 days': '直近 7 日',
  'Last 30 days': '直近 30 日',
  'staked': 'ステーク',
  'asked out': '退出申請',
  'history covers {days}d': '履歴は {days} 日分',
  'In cooldown': 'クールダウン中',
  '{count} positions waiting out the 48 hours': '{count} 件のポジションが 48 時間を待っています',
  'Ready to exit': '退出できます',
  'Cooldown finished, not yet withdrawn': 'クールダウンは終了、まだ引き出していません',
  'When the queue matures': '待ち行列が満了する時期',
  'ready': '引き出し可',
  'ready to withdraw': '引き出し可能',
  'cooling down': 'クールダウン中',
  'Motion': '動き',
  'The vault stands still.': '金庫は止まったままです。',
  'One gentle frame a second.': '1 秒に 1 コマ、ゆっくり動きます。',
  'Live while you watch. Calm after 90 seconds without a touch.': '見ている間はライブ。90 秒触れないと静かになります。',
  'Receipt': '裏づけ',
  'Open on Solscan': 'Solscan で開く',

  // 待ち行列
  'Ready to withdraw': '引き出せます',
  '{amount} SKR is still cooling down across {count} positions': 'まだ {count} 件のポジションで {amount} SKR がクールダウン中です',
  'Reading the queue': '待ち行列を読んでいます',
  'Time to maturity': '満了までの時間',
  'Exits in flight, soonest first': '進行中の退出、近い順',
  '{count} shown': '{count} 件表示',
  'Show all {count}': '{count} 件すべて表示',
  'Show fewer': '折りたたむ',
  'Nothing is queued to leave right now.': 'いま退出待ちのものはありません。',

  // 流れ
  'Live from the vault': '金庫からの実況',
  'Reconnecting': '再接続しています',
  'BUZZ ON': '振動オン',
  'BUZZ OFF': '振動オフ',
  'SOUND ON': '音オン',
  'SOUND OFF': '音オフ',
  'Biggest seen today': '今日最大の動き',
  'Biggest stake today': '今日最大のステーク',
  'Biggest exit today': '今日最大の退出',
  'Biggest withdrawal today': '今日最大の引き出し',
  'Last big move': '直近の大きな動き',
  '{age} ago': '{age}前',
  'slot {slot}': 'スロット {slot}',
  'amount unavailable': '金額を取得できません',
  'withdrew': '引き出し',
  'cancelled exit': '退出を取り消し',
  'stake': 'ステーク',
  'unstake': '退出',
  'withdraw': '引き出し',
  'Fold the older large moves': '以前の大きな動きをたたむ',
  '1 more large move': '大きな動きがあと 1 件',
  '{count} more large moves': '大きな動きがあと {count} 件',
  '{count} landed while you watched': '見ている間に {count} 件届きました',
  'Watching the chain': 'チェーンを見ています',
  'ALL': 'すべて',
  'only {amount} SKR and up': '{amount} SKR 以上のみ',
  'everything, dust included': '少額も含めてすべて',
  'Waiting for the next finalized event of this size.': 'この規模で次に確定する取引を待っています。',

  // 自分、プロフィールとカード
  'Leaving': '退出中',
  '1 position in cooldown': '1 件のポジションがクールダウン中',
  '{count} positions in cooldown': '{count} 件のポジションがクールダウン中',
  'Ready now': 'いま引き出せます',
  'Next unlock': '次の解除',
  'Cooldown finished': 'クールダウンが終わりました',
  'Until this position is free': 'このポジションが解除されるまで',
  'Nothing queued': '待機中のものはありません',
  'Your weight in the vault': '金庫の中での自分の比率',
  'First stake {days} days ago, read from the oldest signature on your position account.': '最初のステークは {days} 日前。ポジションアカウントのいちばん古い署名から読み取りました。',
  'Held at least {days} days. Your position has a long signature history, so the walk back is still going.': '少なくとも {days} 日保有。ポジションの署名履歴が長いため、さかのぼりはまだ続いています。',
  'Reading the age of your position from the chain…': 'チェーンからポジションの経過日数を読んでいます…',
  'Stake SKR': 'SKR をステークする',
  'Drawing your card…': 'カードを描いています…',
  'Share your card': 'カードを共有する',
  'Hide my name on the card': 'カードで名前を隠す',
  'Hide my amount on the card': 'カードで金額を隠す',
  'The eye in the ring closes and the card says A Seeker.': 'リングの中の目が閉じ、カードには「A Seeker」と表示されます。',
  'Days, since and one-of stay; the position line goes.': '日数、開始日、何件中の 1 件かは残り、ポジションの行だけ消えます。',
  'An exact amount next to a start date is close to a fingerprint. Your choice, said plainly.': '正確な金額と開始日が並ぶと、ほとんど指紋のようなものです。はっきり言えば、決めるのはあなたです。',
  'Alerts armed': '通知設定済み',
  'Wake me at unlock': '解除時に知らせる',
  'Refresh': '更新',
  'Disconnect': '切断',
  'This address holds no SKR position right now.': 'このアドレスには現在 SKR のポジションがありません。',
  'This wallet holds no SKR position yet. The first stake opens one; the position account costs a little rent once.': 'このウォレットにはまだ SKR のポジションがありません。最初のステークで開設され、ポジションアカウントのレントが一度だけ少しかかります。',
  'This position is being looked at, not signed for. Connect the wallet that holds it to stake from it.': 'このポジションは閲覧しているだけで、署名はできません。ここからステークするには、これを持つウォレットを接続してください。',
  'The wallet that answered is not the one on screen. Connect the wallet that holds this position, then stake. Nothing was sent.': '応答したウォレットは画面のものと違います。このポジションを持つウォレットを接続してからステークしてください。何も送られていません。',
  'The app was closed while the wallet had this stake. Check your position before staking again, then clear this.': 'このステークの途中でアプリが閉じられました。もう一度ステークする前にポジションを確認し、それからこれを消してください。',
  'Connect the wallet that holds your stake, or paste any public address. Nothing is signed.': 'ステークを持つウォレットを接続するか、任意の公開アドレスを貼り付けてください。署名は一切しません。',
  'Connect Solana Mobile': 'Solana Mobile を接続',
  'OR': 'または',
  'Paste a Solana address': 'Solana のアドレスを貼り付け',
  'Look up': '照会',
  'WEIGHT': '比率',
  'POSITIONS': 'ポジション',
  'READ FROM': '取得元',
  '1 unlock alert armed on this phone.': 'この端末に解除の通知を 1 件設定しました。',
  '{count} unlock alerts armed on this phone.': 'この端末に解除の通知を {count} 件設定しました。',
  'Nothing left to wait for — the cooldown is already over.': '待つものはありません。クールダウンはすでに終わっています。',
  'Caption copied. Paste it next to the picture.': '文面をコピーしました。画像のとなりに貼り付けてください。',
  'This phone would not take the caption — type it yourself.': 'この端末が文面を受け取れませんでした。ご自身で入力してください。',
  'Your SKR staker card': 'あなたの SKR ステーカーカード',
  'This phone has nothing to share with.': 'この端末には共有できるアプリがありません。',

  // 毎日の 16 分割
  'Sixteen': '16 分割',
  'The daily sixteen': '毎日の 16 分割',
  '16 parts of 1 SKR, one approval. A small daily habit that keeps your position moving.': '1 SKR を 16 に分けて、承認は 1 回。ポジションを動かし続ける小さな毎日の習慣です。',

  // チップ
  'Support SKR Eyes': 'SKR Eyes を支援する',
  'Send a tip': 'チップを送る',
  'A tip in SKR': 'SKR でチップ',
  'How much': '金額',
  'Any amount you like. Goes to {name}, the wallet behind this app.': '金額は自由です。このアプリを作ったウォレット {name} に届きます。',
  'Send {amount} SKR to {name}': '{name} に {amount} SKR を送る',
  '{amount} SKR on its way to {name}': '{amount} SKR を {name} に送っています',
  'Thank you': 'ありがとうございます',
  'Done': '完了',
  'Landing on chain…': 'チェーンに載せています…',
  'Your wallet signs and sends it. The app only fetches a blockhash before and reads the status after.': '署名して送るのはあなたのウォレットです。アプリは前にブロックハッシュを取得し、後に状態を読むだけです。',
  'A tip changes nothing about your position and nothing about any airdrop. It is a thank you, not a fee.': 'チップはポジションにもエアドロップにも何の影響もありません。手数料ではなく、感謝の気持ちです。',
  'Free and open source, built by one Seeker. Tips in SKR go to kosa.skr and are staked right away, all of them.': '無料でオープンソース、ひとりの Seeker が作りました。SKR のチップは kosa.skr に届き、すべてすぐにステークされます。',
  'This app is free, open source, and built by one Seeker. If it saved you a moment, a tip is welcome. Every SKR that arrives is staked right away, all of it.': 'このアプリは無料でオープンソース、ひとりの Seeker が作りました。少しでも役に立ったなら、チップを歓迎します。届いた SKR はすべてすぐにステークされます。',
  'This is {name} itself. A tip to your own wallet moves nothing; try from another wallet.': 'これは {name} 自身です。自分のウォレットへのチップでは何も動きません。別のウォレットからお試しください。',
  'The chain rejected the transfer.': 'チェーンが送金を拒否しました。',
  'The wallet declined. Nothing was sent.': 'ウォレットが拒否しました。何も送られていません。',
  'The wallet returned no signature.': 'ウォレットが署名を返しませんでした。',
  'SKR has six decimal places. Shorten the amount.': 'SKR の小数は 6 桁までです。金額を短くしてください。',

  // 実際に目にするエラー
  'The finalized snapshot is still warming up. Try again in a moment.': '確定版の集計をまだ準備しています。少し待ってからお試しください。',
  'This position could not be read': 'このポジションを読み取れませんでした',
  'The wallet request was cancelled': 'ウォレットへの要求は取り消されました',
  'The wallet did not return an account.': 'ウォレットがアカウントを返しませんでした。',
  'Alerts could not be scheduled': '通知を設定できませんでした',
  'The card is not ready yet': 'カードはまだ準備できていません',
  'The card could not be drawn': 'カードを描けませんでした',
  'the chain returned no signatures': 'チェーンが署名を返しませんでした',
  'age lookup failed': '経過日数の照会に失敗しました',
  'SKR Eyes API returned {status}': 'SKR Eyes の API が {status} を返しました',
  'The age service answered {status}': '経過日数のサービスが {status} を返しました',

  // 通知の画面
  'Notifications allowed': '通知は許可されています',
  'Notifications off': '通知はオフです',
  'Alerts are scheduled on the phone itself. Nothing about you leaves the device.': '通知は端末自身が予約します。あなたに関する情報が端末の外に出ることはありません。',
  'Allow notifications and this app can wake you exactly when your cooldown ends.': '通知を許可すると、クールダウンが終わるちょうどその時にお知らせできます。',
  'Allow notifications': '通知を許可',
  'Open settings': '設定を開く',
  'This phone can now wake you.': 'この端末からお知らせできるようになりました。',
  'Android will not ask again. Turn notifications on for SKR Eyes in the system settings.': 'Android はもう確認してきません。システム設定で SKR Eyes の通知をオンにしてください。',
  'Android is holding notifications back for this app.': 'Android がこのアプリの通知を止めています。',
  'Android did not answer the permission request. Try again, or turn notifications on in the system settings.': 'Android が権限の要求に応答しませんでした。もう一度試すか、システム設定で通知をオンにしてください。',
  'This phone would not open its settings screen.': 'この端末が設定画面を開けませんでした。',
  'Wake me at my unlock': '自分の解除時に知らせる',
  'Connect your wallet on the Me screen and this switch becomes live.': '「自分」タブでウォレットを接続すると、このスイッチが使えるようになります。',
  'One hour before, and again the moment the cooldown ends. Scheduled by this phone from the exact on-chain time.': '1 時間前に一度、クールダウンが終わる瞬間にもう一度。チェーン上の正確な時刻をもとに、この端末が予約します。',
  'Nothing of yours is unlocking, so there is nothing to wake you for yet.': '解除されるものがないので、いまお知らせする用事はありません。',
  'Large moves, heard and felt': '大きな動きを音と振動で',
  'A stake of 1K SKR or more rings like a glass coin, a stake of 100K rings the vault bell, an exit of 100K lands with a low boom. On every screen while the app is open, each with a short buzz.': '1K SKR 以上のステークはガラスのコインのように鳴り、100K のステークは金庫の鐘を鳴らし、100K の退出は低い音で響きます。アプリを開いている間はどの画面でも、それぞれ短い振動つきです。',
  "Other people's moves do not wake the phone while the app is closed. Only your own unlock does.": 'アプリを閉じている間は、他の人の動きで端末は起きません。起こすのは自分の解除だけです。',
  'What counts as large': '何を大きいとみなすか',
  'Built-in thresholds behind the bell and the boom, until the server publishes its own.': '鐘と低い音を鳴らす内蔵のしきい値です。サーバーが独自の値を公開するまで使います。',
  'These come from the server, move with real traffic, and drive the bell and the boom.': 'この値はサーバーから届き、実際の取引量に合わせて動き、鐘と低い音を鳴らします。',
  'Send a test notification': 'テスト通知を送る',
  'A test notification will arrive in a few seconds.': 'テスト通知が数秒後に届きます。',
  'The test notification could not be scheduled': 'テスト通知を予約できませんでした',
  '1 reminder set on this phone for your unlock.': '解除に合わせて、この端末に通知を 1 件設定しました。',
  '{count} reminders set on this phone for your unlock.': '解除に合わせて、この端末に通知を {count} 件設定しました。',
  'The reminders for your unlock were cancelled.': '解除の通知を取り消しました。',
  'The alert could not be changed.': '通知を変更できませんでした。',
  'Language': '言語',
  'The app follows your phone until you choose here. The card you share stays in English, so it reads the same to everyone who sees it.': 'ここで選ぶまで、アプリは端末の言語に従います。共有するカードは英語のままなので、見る人みんなが同じように読めます。',

  // 通知そのもの
  'This wallet has no pending SKR unlock.': 'このウォレットには解除待ちの SKR がありません。',
  'SKR unlocks in 1 hour': '1 時間後に SKR が解除されます',
  'Your pending SKR is approaching its withdrawable time.': '待機中の SKR が引き出せる時刻に近づいています。',
  'Your SKR is now withdrawable': 'SKR を引き出せるようになりました',
  'Open SKR Eyes to verify the finalized position and evidence.': 'SKR Eyes を開いて、確定したポジションと裏づけを確認してください。',
  'SKR Eyes alerts are ready': 'SKR Eyes の通知の準備ができました',
  'Test complete. Real unlock alerts will use finalized on-chain time.': 'テストは完了です。本番の通知はチェーン上で確定した時刻を使います。',

  // ステーク画面
  'Add to your position': '自分のポジションに追加',
  'Amount per transaction': '1 回あたりの金額',
  'SKR has six decimal places. Shorten the amount — the extra digits cannot be staked.': 'SKR の小数は 6 桁までです。金額を短くしてください。あふれた桁はステークできません。',
  'A single transaction cannot stake less than 1 SKR.': '1 回の取引で 1 SKR 未満はステークできません。',
  'This is what one transaction stakes. The total is this amount times the count below.': 'これは 1 回の取引でステークする額です。合計はこの額に下の回数を掛けたものです。',
  'How many transactions': '取引の回数',
  'One transaction, one wallet approval.': '取引 1 回、ウォレットでの承認 1 回。',
  '{count} identical transactions from one approval, sent one after another. Each one is a separate on-chain stake.': '1 回の承認で同じ取引を {count} 件、続けて送ります。どれもチェーン上では別々のステークです。',
  'This needs {needed} SKR and you hold {held}. ': 'これには {needed} SKR が必要ですが、残高は {held} です。',
  'At this amount you can send 1 part.': 'この金額なら 1 件送れます。',
  'At this amount you can send {count} parts.': 'この金額なら {count} 件送れます。',
  'Lower the amount to stake what you have.': '残高に合わせて金額を下げてください。',
  'You hold {held} SKR.': '残高は {held} SKR です。',
  'Before you sign': '署名する前に',
  'sent as': '送り方',
  'you stake in total': '合計ステーク額',
  'position account rent': 'ポジションアカウントのレント',
  'already paid': '支払い済み',
  '{sol} SOL, once': '{sol} SOL、一度だけ',
  'Your position account already exists, so only the network fee applies — a few thousand lamports per transaction.': 'ポジションアカウントはすでにあるので、かかるのはネットワーク手数料だけです。1 回あたり数千ランポートです。',
  'The first stake creates your position account and its rent stays with the account. Network fees are a few thousand lamports per transaction.': '最初のステークでポジションアカウントがつくられ、そのレントはアカウントに残ります。ネットワーク手数料は 1 回あたり数千ランポートです。',
  'Working…': '処理中…',
  'At least 1 SKR per transaction': '1 回につき最低 1 SKR',
  'Sign and stake {amount} SKR': '署名して {amount} SKR をステーク',
  'Sign and stake': '署名してステーク',
  'All parts landed': 'すべてチェーンに載りました',
  'Stopped': '停止しました',
  'Approve in your wallet': 'ウォレットで承認してください',
  'Preparing transactions': '取引を準備しています',
  'A run from before': '前回の途中の処理',
  'Landing on chain': 'チェーンに載せています',
  'pending': '待機',
  'sending': '送信中',
  'sent': '送信済み',
  'confirmed': '確定',
  'unknown': '不明',
  'failed': '失敗',
  'We do not know yet': 'まだ分かりません',
  'What happened': '何が起きたか',
  'Ask the chain again': 'チェーンにもう一度尋ねる',
  'Stake again': 'もう一度ステークする',
  'Discard and start over': '破棄してやり直す',
  'Start over': 'やり直す',
  'Close': '閉じる',
};
