// 한국어. 키는 코드에 들어 있는 영어 문장 그 자체입니다.
//
// 이 표의 규칙: 담백한 존댓말(설명은 ~습니다, 안내는 ~세요), 광고 문구 없음,
// 느낌표 없음. 토큰 기호(SKR, SOL), 지갑 이름(Seed Vault), 앱 이름은 원래
// 표기 그대로 둡니다. 숫자는 이미 서식이 갖춰진 채로 들어오므로 중괄호는
// 위치만 옮기고 이름은 바꾸지 않습니다. 용어: 스테이킹 / 언스테이킹(나가기
// 신청) / 대기(48시간 쿨다운) / 해제(대기가 끝나 출금 가능해짐) / 출금.

export const ko: Record<string, string> = {
  'Vault': '금고',
  'over the last 7 days': '최근 7일',
  'over the last 30 days': '최근 30일',
  '{percent}% of all SKR is staked': '전체 SKR의 {percent}%가 스테이킹 중',
  'over the last 24 hours': '최근 24시간',
  'net': '순증감',
  'wallets': '지갑',
  // 탭과 최신성 배지
  'Pulse': '맥박',
  'Flow': '흐름',
  'Me': '내 정보',
  'Queue': '대기열',
  'Alerts': '알림',
  'fresh': '최신',
  'aging': '조금 지남',
  'stale': '오래됨',
  'unavailable': '없음',
  'syncing': '동기화 중',
  'every number has a receipt': '모든 숫자에는 근거가 있습니다',

  // 금고 장면
  'Waiting for a finalized answer': '확정된 응답을 기다리는 중',
  'Reading the vault': '금고를 읽는 중',
  'Network unavailable': '네트워크에 연결할 수 없음',
  'Last 24 hours': '최근 24시간',
  'Last 7 days': '최근 7일',
  'Last 30 days': '최근 30일',
  '24h': '24h',
  'staked': '스테이킹',
  'in': '들어옴',
  'asked out': '언스테이킹 신청',
  'staked minus requested out': '스테이킹에서 언스테이킹 신청을 뺀 값',
  'history covers {days}d': '기록 {days}일치',
  'In cooldown': '대기 중',
  'cooling down': '대기 중',
  '{count} positions waiting out the 48 hours': '{count}개 포지션이 48시간을 채우는 중',
  'Ready to exit': '나갈 준비 완료',
  'Cooldown finished, not yet withdrawn': '대기 끝, 아직 출금 전',
  'When the queue matures': '대기열이 언제 풀리는지',
  'ready': '준비됨',
  'ready to withdraw': '출금 가능',
  'Motion': '모션',
  'The vault stands still.': '금고가 멈춰 있습니다.',
  'One gentle frame a second.': '초당 한 프레임, 잔잔하게.',
  'Live while you watch. Calm after 90 seconds without a touch.': '보는 동안은 실시간. 90초 동안 손대지 않으면 잔잔하게.',
  'Receipt': '영수증',
  'Open on Solscan': 'Solscan에서 열기',

  // 대기열
  'Ready to withdraw': '출금 가능',
  '{amount} SKR is still cooling down across {count} positions': '{count}개 포지션에서 아직 {amount} SKR이 대기 중',
  'Reading the queue': '대기열을 읽는 중',
  'Time to maturity': '풀릴 때까지',
  'Exits in flight, soonest first': '진행 중인 언스테이킹, 가까운 순',
  '{count} shown': '{count}개 표시',
  'Show all {count}': '{count}개 모두 보기',
  'Show fewer': '줄이기',
  'Nothing is queued to leave right now.': '지금은 나가려고 대기 중인 항목이 없습니다.',

  // 흐름
  'Live from the vault': '금고에서 실시간으로',
  'Reconnecting': '다시 연결하는 중',
  'BUZZ ON': '진동 켬',
  'BUZZ OFF': '진동 끔',
  'SOUND ON': '소리 켬',
  'SOUND OFF': '소리 끔',
  'Biggest seen today': '오늘 가장 큰 건',
  'Biggest stake today': '오늘 가장 큰 스테이킹',
  'Biggest exit today': '오늘 가장 큰 언스테이킹',
  'Biggest withdrawal today': '오늘 가장 큰 출금',
  'Last big move': '마지막 큰 움직임',
  '{age} ago': '{age} 전',
  'slot {slot}': '슬롯 {slot}',
  'amount unavailable': '금액을 읽을 수 없음',
  'withdrew': '출금함',
  'cancelled exit': '언스테이킹 취소',
  'stake': '스테이킹',
  'unstake': '언스테이킹',
  'withdraw': '출금',
  'Fold the older large moves': '이전 큰 움직임 접기',
  '1 more large move': '큰 움직임 1건 더',
  '{count} more large moves': '큰 움직임 {count}건 더',
  '{count} landed while you watched': '보는 동안 {count}건이 들어왔습니다',
  'Watching the chain': '체인을 지켜보는 중',
  'ALL': '전체',
  'only {amount} SKR and up': '{amount} SKR 이상만',
  'everything, dust included': '소액까지 전부',
  'Waiting for the next finalized event of this size.': '이 규모의 다음 확정 거래를 기다리는 중입니다.',

  // 내 정보, 프로필과 카드
  'Leaving': '나가는 중',
  '1 position in cooldown': '포지션 1개가 대기 중',
  '{count} positions in cooldown': '포지션 {count}개가 대기 중',
  'Ready now': '지금 가능',
  'Next unlock': '다음 해제',
  'Cooldown finished': '대기가 끝났습니다',
  'Until this position is free': '이 포지션이 풀릴 때까지',
  'Nothing queued': '대기 중인 항목 없음',
  'Your weight in the vault': '금고에서 차지하는 비중',
  'First stake {days} days ago, read from the oldest signature on your position account.': '첫 스테이킹은 {days}일 전, 포지션 계정의 가장 오래된 서명에서 읽었습니다.',
  'Held at least {days} days. Your position has a long signature history, so the walk back is still going.': '최소 {days}일 보유. 포지션의 서명 기록이 길어 거슬러 올라가는 작업이 아직 진행 중입니다.',
  'Reading the age of your position from the chain…': '체인에서 포지션 보유 기간을 읽는 중…',
  'Stake SKR': 'SKR 스테이킹',
  'Drawing your card…': '카드를 그리는 중…',
  'Share your card': '카드 공유하기',
  'Alerts armed': '알림 설정됨',
  'Wake me at unlock': '해제될 때 깨우기',
  'Refresh': '새로고침',
  'Disconnect': '연결 해제',
  'This address holds no SKR position right now.': '이 주소에는 지금 SKR 포지션이 없습니다.',
  'This wallet holds no SKR position yet. The first stake opens one; the position account costs a little rent once.': '이 지갑에는 아직 SKR 포지션이 없습니다. 첫 스테이킹이 포지션을 열고, 포지션 계정 렌트가 한 번 조금 듭니다.',
  'This position is being looked at, not signed for. Connect the wallet that holds it to stake from it.': '이 포지션은 조회만 하는 중이라 서명할 수 없습니다. 여기에서 스테이킹하려면 이 포지션을 보유한 지갑을 연결하세요.',
  'Connect the wallet that holds your stake, or paste any public address. Nothing is signed.': '스테이킹을 보유한 지갑을 연결하거나, 아무 공개 주소나 붙여 넣으세요. 서명은 하지 않습니다.',
  'Connect Solana Mobile': 'Solana Mobile 연결',
  'OR': '또는',
  'Paste a Solana address': 'Solana 주소를 붙여 넣으세요',
  'Look up': '조회',
  'WEIGHT': '비중',
  'POSITIONS': '포지션',
  'READ FROM': '출처',
  '1 unlock alert armed on this phone.': '이 휴대폰에 해제 알림 1개를 설정했습니다.',
  '{count} unlock alerts armed on this phone.': '이 휴대폰에 해제 알림 {count}개를 설정했습니다.',
  'Nothing left to wait for — the cooldown is already over.': '더 기다릴 것이 없습니다. 대기 시간은 이미 끝났습니다.',
  'Caption copied. Paste it next to the picture.': '문구를 복사했습니다. 사진 옆에 붙여 넣으세요.',
  'This phone would not take the caption — type it yourself.': '이 휴대폰이 문구를 받지 못했습니다. 직접 입력해 주세요.',
  'Your SKR staker card': '내 SKR 스테이커 카드',
  'This phone has nothing to share with.': '이 휴대폰에는 공유할 앱이 없습니다.',
  'Hide my name on the card': '카드에서 내 이름 숨기기',
  'The eye in the ring closes and the card says A Seeker.': '고리 안의 눈이 감기고 카드에는 A Seeker라고만 표시됩니다.',
  'Hide my amount on the card': '카드에서 내 금액 숨기기',
  'Days, since and one-of stay; the position line goes.': '일수, 시작일, 몇 번째인지는 남고 포지션 금액 줄만 빠집니다.',
  'An exact amount next to a start date is close to a fingerprint. Your choice, said plainly.': '정확한 금액이 시작 날짜 옆에 놓이면 지문에 가깝습니다. 어떻게 할지는 직접 정하세요. 있는 그대로 말씀드립니다.',

  // 매일 열여섯
  'Sixteen': '열여섯',
  'The daily sixteen': '매일 열여섯',
  '16 parts of 1 SKR, one approval. A small daily habit that keeps your position moving.': '1 SKR을 16조각으로, 승인은 한 번. 포지션을 계속 움직이게 하는 작은 하루 습관입니다.',

  // 후원(팁) 창
  'Support SKR Eyes': 'SKR Eyes 후원하기',
  'Send a tip': '팁 보내기',
  'A tip in SKR': 'SKR 팁',
  'How much': '금액',
  'Any amount you like. Goes to {name}, the wallet behind this app.': '원하는 만큼이면 됩니다. 이 앱을 만든 지갑인 {name} 앞으로 갑니다.',
  'Send {amount} SKR to {name}': '{name}에게 {amount} SKR 보내기',
  '{amount} SKR on its way to {name}': '{amount} SKR이 {name}에게 가는 중',
  'Thank you': '고맙습니다',
  'Done': '완료',
  'Landing on chain…': '체인에 올라가는 중…',
  'Your wallet signs and sends it. The app only fetches a blockhash before and reads the status after.': '서명과 전송은 지갑이 합니다. 앱은 보내기 전에 블록해시를 받아 오고, 보낸 뒤에 상태를 읽을 뿐입니다.',
  'A tip changes nothing about your position and nothing about any airdrop. It is a thank you, not a fee.': '팁은 포지션에도, 어떤 에어드롭에도 아무 영향이 없습니다. 수수료가 아니라 고마움의 표시입니다.',
  'Free and open source, built by one Seeker. Tips in SKR go to kosa.skr and are staked right away, all of them.': '무료 오픈소스이고, Seeker 한 사람이 만들었습니다. SKR 팁은 kosa.skr로 가서 전부 바로 스테이킹됩니다.',
  'This app is free, open source, and built by one Seeker. If it saved you a moment, a tip is welcome. Every SKR that arrives is staked right away, all of it.': '이 앱은 무료 오픈소스이고, Seeker 한 사람이 만들었습니다. 덕분에 시간을 조금이라도 아꼈다면 팁은 언제든 환영입니다. 들어오는 SKR은 전부 바로 스테이킹됩니다.',
  'This is {name} itself. A tip to your own wallet moves nothing; try from another wallet.': '여기가 바로 {name}입니다. 자기 지갑에 보내는 팁은 아무것도 옮기지 않습니다. 다른 지갑에서 시도해 보세요.',
  'The chain rejected the transfer.': '체인이 전송을 거부했습니다.',
  'The wallet declined. Nothing was sent.': '지갑이 거절했습니다. 아무것도 보내지 않았습니다.',
  'The wallet returned no signature.': '지갑이 서명을 반환하지 않았습니다.',
  'SKR has six decimal places. Shorten the amount.': 'SKR은 소수점 여섯 자리까지입니다. 금액을 줄여 주세요.',

  // 사용자가 실제로 보게 되는 오류
  'The finalized snapshot is still warming up. Try again in a moment.': '확정된 스냅샷을 아직 준비하는 중입니다. 잠시 후 다시 시도해 주세요.',
  'This position could not be read': '이 포지션을 읽을 수 없습니다',
  'The wallet request was cancelled': '지갑 요청이 취소되었습니다',
  'The wallet did not return an account.': '지갑이 계정을 반환하지 않았습니다.',
  'The wallet that answered is not the one on screen. Connect the wallet that holds this position, then stake. Nothing was sent.': '응답한 지갑이 화면에 있는 지갑과 다릅니다. 이 포지션을 보유한 지갑을 연결한 뒤 스테이킹하세요. 아무것도 보내지 않았습니다.',
  'The app was closed while the wallet had this stake. Check your position before staking again, then clear this.': '지갑이 이 스테이킹을 처리하는 도중 앱이 닫혔습니다. 다시 스테이킹하기 전에 포지션을 확인한 다음 이 표시를 지우세요.',
  'Alerts could not be scheduled': '알림을 설정하지 못했습니다',
  'The card is not ready yet': '카드가 아직 준비되지 않았습니다',
  'The card could not be drawn': '카드를 그리지 못했습니다',
  'the chain returned no signatures': '체인이 서명을 반환하지 않았습니다',
  'age lookup failed': '보유 기간 조회에 실패했습니다',
  'SKR Eyes API returned {status}': 'SKR Eyes API가 {status}을(를) 반환했습니다',
  'The age service answered {status}': '보유 기간 서비스가 {status}을(를) 응답했습니다',

  // 알림 화면
  'Notifications allowed': '알림 허용됨',
  'Notifications off': '알림 꺼짐',
  'Alerts are scheduled on the phone itself. Nothing about you leaves the device.': '알림은 휴대폰이 스스로 예약합니다. 내 정보는 어떤 것도 기기 밖으로 나가지 않습니다.',
  'Allow notifications and this app can wake you exactly when your cooldown ends.': '알림을 허용하면 대기 시간이 끝나는 바로 그 순간에 깨워 드릴 수 있습니다.',
  'Allow notifications': '알림 허용',
  'Open settings': '설정 열기',
  'This phone can now wake you.': '이제 이 휴대폰이 깨워 줄 수 있습니다.',
  'Android will not ask again. Turn notifications on for SKR Eyes in the system settings.': 'Android는 다시 묻지 않습니다. 시스템 설정에서 SKR Eyes의 알림을 켜 주세요.',
  'Android is holding notifications back for this app.': 'Android가 이 앱의 알림을 막고 있습니다.',
  'Android did not answer the permission request. Try again, or turn notifications on in the system settings.': 'Android가 권한 요청에 응답하지 않았습니다. 다시 시도하거나 시스템 설정에서 알림을 켜 주세요.',
  'This phone would not open its settings screen.': '이 휴대폰이 설정 화면을 열지 못했습니다.',
  'Wake me at my unlock': '내 해제 시간에 깨우기',
  'Connect your wallet on the Me screen and this switch becomes live.': '내 정보 탭에서 지갑을 연결하면 이 스위치가 작동합니다.',
  'One hour before, and again the moment the cooldown ends. Scheduled by this phone from the exact on-chain time.': '한 시간 전에 한 번, 대기가 끝나는 순간에 다시 한 번. 체인의 정확한 시각을 기준으로 이 휴대폰이 예약합니다.',
  'Nothing of yours is unlocking, so there is nothing to wake you for yet.': '해제되는 것이 없어서 아직 깨울 이유가 없습니다.',
  'Large moves, heard and felt': '큰 움직임을 소리와 진동으로',
  'A stake of 1K SKR or more rings like a glass coin, a stake of 100K rings the vault bell, an exit of 100K lands with a low boom. On every screen while the app is open, each with a short buzz.': '1K SKR 이상 스테이킹은 유리 동전 소리로, 100K 스테이킹은 금고 종소리로, 100K 언스테이킹은 낮은 울림으로 도착합니다. 앱이 열려 있는 동안 어느 화면에서든, 짧은 진동과 함께요.',
  "Other people's moves do not wake the phone while the app is closed. Only your own unlock does.": '앱이 닫혀 있을 때 다른 사람의 움직임은 휴대폰을 깨우지 않습니다. 내 해제만 깨웁니다.',
  'What counts as large': '무엇이 큰 건인지',
  'Built-in thresholds behind the bell and the boom, until the server publishes its own.': '종소리와 울림의 내장 기준값입니다. 서버가 자체 기준을 내놓기 전까지 씁니다.',
  'These come from the server, move with real traffic, and drive the bell and the boom.': '이 값은 서버에서 오고 실제 거래량에 따라 움직이며, 종소리와 울림을 결정합니다.',
  'Send a test notification': '테스트 알림 보내기',
  'A test notification will arrive in a few seconds.': '테스트 알림이 몇 초 안에 도착합니다.',
  'The test notification could not be scheduled': '테스트 알림을 예약하지 못했습니다',
  '1 reminder set on this phone for your unlock.': '해제 시각에 맞춰 이 휴대폰에 알림 1개를 설정했습니다.',
  '{count} reminders set on this phone for your unlock.': '해제 시각에 맞춰 이 휴대폰에 알림 {count}개를 설정했습니다.',
  'The reminders for your unlock were cancelled.': '해제 알림을 취소했습니다.',
  'The alert could not be changed.': '알림을 변경하지 못했습니다.',
  'Language': '언어',
  'The app follows your phone until you choose here. The card you share stays in English, so it reads the same to everyone who sees it.': '여기서 고르기 전까지 앱은 휴대폰 언어를 따릅니다. 공유하는 카드는 계속 영어로 남아, 보는 사람 모두가 같은 내용을 읽게 됩니다.',

  // 알림 문구 자체
  'This wallet has no pending SKR unlock.': '이 지갑에는 해제를 기다리는 SKR이 없습니다.',
  'SKR unlocks in 1 hour': '1시간 뒤 SKR이 해제됩니다',
  'Your pending SKR is approaching its withdrawable time.': '대기 중인 SKR의 출금 가능 시각이 다가옵니다.',
  'Your SKR is now withdrawable': '이제 SKR을 출금할 수 있습니다',
  'Open SKR Eyes to verify the finalized position and evidence.': 'SKR Eyes를 열어 확정된 포지션과 근거를 확인하세요.',
  'SKR Eyes alerts are ready': 'SKR Eyes 알림이 준비되었습니다',
  'Test complete. Real unlock alerts will use finalized on-chain time.': '테스트를 마쳤습니다. 실제 알림은 체인에서 확정된 시각을 씁니다.',

  // 스테이킹 창
  'Add to your position': '내 포지션에 추가',
  'Amount per transaction': '거래 한 건당 금액',
  'SKR has six decimal places. Shorten the amount — the extra digits cannot be staked.': 'SKR은 소수점 여섯 자리까지입니다. 금액을 줄여 주세요. 넘는 자리는 스테이킹할 수 없습니다.',
  'A single transaction cannot stake less than 1 SKR.': '거래 한 건으로 1 SKR 미만은 스테이킹할 수 없습니다.',
  'This is what one transaction stakes. The total is this amount times the count below.': '거래 한 건이 스테이킹하는 금액입니다. 합계는 이 금액에 아래 횟수를 곱한 값입니다.',
  'How many transactions': '거래 횟수',
  'One transaction, one wallet approval.': '거래 한 건, 지갑 승인 한 번.',
  '{count} identical transactions from one approval, sent one after another. Each one is a separate on-chain stake.': '한 번의 승인으로 같은 거래 {count}건을 차례로 보냅니다. 각각이 체인상의 별개 스테이킹입니다.',
  'This needs {needed} SKR and you hold {held}. ': '{needed} SKR이 필요한데 보유량은 {held}입니다. ',
  'At this amount you can send 1 part.': '이 금액이면 1건을 보낼 수 있습니다.',
  'At this amount you can send {count} parts.': '이 금액이면 {count}건을 보낼 수 있습니다.',
  'Lower the amount to stake what you have.': '보유한 만큼 스테이킹하려면 금액을 낮추세요.',
  'You hold {held} SKR.': '보유량은 {held} SKR입니다.',
  'Before you sign': '서명하기 전에',
  'sent as': '전송 방식',
  'you stake in total': '총 스테이킹 금액',
  'position account rent': '포지션 계정 렌트',
  'already paid': '이미 냈습니다',
  '{sol} SOL, once': '{sol} SOL, 한 번만',
  'Your position account already exists, so only the network fee applies — a few thousand lamports per transaction.': '포지션 계정이 이미 있어서 네트워크 수수료만 듭니다. 거래당 수천 램포트입니다.',
  'The first stake creates your position account and its rent stays with the account. Network fees are a few thousand lamports per transaction.': '첫 스테이킹이 포지션 계정을 만들고, 렌트는 그 계정에 남습니다. 네트워크 수수료는 거래당 수천 램포트입니다.',
  'Working…': '처리 중…',
  'At least 1 SKR per transaction': '거래당 최소 1 SKR',
  'Sign and stake {amount} SKR': '서명하고 {amount} SKR 스테이킹',
  'Sign and stake': '서명하고 스테이킹',
  'All parts landed': '모든 건이 체인에 올라갔습니다',
  'Stopped': '중단됨',
  'Approve in your wallet': '지갑에서 승인하세요',
  'Preparing transactions': '거래를 준비하는 중',
  'A run from before': '이전에 하던 작업',
  'Landing on chain': '체인에 올라가는 중',
  'pending': '대기',
  'sending': '전송 중',
  'sent': '전송됨',
  'confirmed': '확정됨',
  'unknown': '알 수 없음',
  'failed': '실패',
  'We do not know yet': '아직 알 수 없습니다',
  'What happened': '무슨 일이 있었는지',
  'Ask the chain again': '체인에 다시 물어보기',
  'Stake again': '다시 스테이킹',
  'Discard and start over': '버리고 처음부터',
  'Start over': '처음부터',
  'Close': '닫기',
};
