// Português (do Brasil). A chave é a frase em inglês tal como está no código.
//
// Regras desta tabela: linguagem simples, sem palavras de marketing nem pontos
// de exclamação, tratamento por "você". Os tickers (SKR, SOL), o nome da
// carteira (Seed Vault), Seeker, Solscan e o nome do app ficam como estão.
// Os números chegam já formatados: os marcadores mudam de lugar, nunca de nome.
// "Cooldown" vira "espera", "stake" fica stake, "withdraw" vira saque.
//
// Em português a frase fica cerca de um terço mais longa que em inglês, então
// os rótulos de cartão e de botão são mais curtos que a tradução literal.

export const pt: Record<string, string> = {
  'Earned on staking': 'Ganho com o stake',
  'An estimate from the share price at your last stake or unstake. Rewards banked before that move are folded into your position and not counted here.': 'Estimativa pelo preço da cota no seu último stake ou saída. As recompensas acumuladas antes desse movimento já estão na posição e não entram aqui.',
  'All': 'Tudo',
  'Stakes': 'Stakes',
  'Exits': 'Saídas',
  'Withdrew': 'Saques',
  'Vault': 'Cofre',
  'over the last 7 days': 'nos últimos 7 dias',
  'over the last 30 days': 'nos últimos 30 dias',
  '{percent}% of all SKR is staked': '{percent}% de todo o SKR está em stake',
  'over the last 24 hours': 'nas últimas 24 horas',
  'net': 'líquido',
  'wallets': 'carteiras',
  'in': 'entrou',
  'staked minus requested out': 'stake menos saída pedida',
  '24h': '24h',
  // Abas e selo de atualidade
  'Flow': 'Fluxo',
  'Me': 'Eu',
  'Queue': 'Fila',
  'Alerts': 'Avisos',
  'fresh': 'em dia',
  'aging': 'envelhecendo',
  'stale': 'defasado',
  'unavailable': 'sem dados',
  'syncing': 'sincronizando',
  'every number has a receipt': 'todo número tem comprovante',

  // Cofre
  'Waiting for a finalized answer': 'Esperando uma resposta confirmada',
  'Reading the vault': 'Lendo o cofre',
  'Network unavailable': 'Sem rede',
  'Last 24 hours': 'Últimas 24 horas',
  'Last 7 days': 'Últimos 7 dias',
  'Last 30 days': 'Últimos 30 dias',
  'staked': 'em stake',
  'asked out': 'pediu saída',
  'history covers {days}d': 'histórico de {days}d',
  'In cooldown': 'Em espera',
  '{count} positions waiting out the 48 hours': '{count} posições cumprindo as 48 horas',
  'Ready to exit': 'Pronto para sair',
  'Cooldown finished, not yet withdrawn': 'Espera concluída, ainda não sacado',
  'When the queue matures': 'Quando a fila vence',
  'ready': 'pronto',
  'ready to withdraw': 'pronto para sacar',
  'cooling down': 'em espera',

  // Animação da cena e comprovante
  'Motion': 'Animação',
  'The vault stands still.': 'O cofre fica parado.',
  'One gentle frame a second.': 'Um quadro suave por segundo.',
  'Live while you watch. Calm after 90 seconds without a touch.': 'Ao vivo enquanto você olha. Calmo depois de 90 segundos sem toque.',
  'Receipt': 'Comprovante',
  'Open on Solscan': 'Abrir no Solscan',

  // Fila
  'Exits in flight, soonest first': 'Saídas em andamento, as mais próximas primeiro',
  '{count} shown': '{count} na tela',
  'Nothing is queued to leave right now.': 'Agora não há nada na fila para sair.',
  'Show all {count}': 'Mostrar todas as {count}',
  'Show fewer': 'Mostrar menos',

  // Fluxo
  'Live from the vault': 'Ao vivo do cofre',
  'Reconnecting': 'Reconectando',
  'BUZZ ON': 'VIBRAÇÃO ON',
  'BUZZ OFF': 'VIBRAÇÃO OFF',
  'SOUND ON': 'SOM ON',
  'SOUND OFF': 'SOM OFF',
  'Biggest seen today': 'Maior de hoje',
  'Biggest stake today': 'Maior stake de hoje',
  'Biggest exit today': 'Maior saída de hoje',
  'Biggest withdrawal today': 'Maior saque de hoje',
  'Last big move': 'Último grande movimento',
  '{age} ago': 'há {age}',
  'slot {slot}': 'slot {slot}',
  'amount unavailable': 'valor indisponível',
  'withdrew': 'sacou',
  'cancelled exit': 'cancelou a saída',
  'stake': 'stake',
  'unstake': 'saída',
  'withdraw': 'saque',
  'Fold the older large moves': 'Recolher os grandes movimentos anteriores',
  '1 more large move': 'mais 1 grande movimento',
  '{count} more large moves': 'mais {count} grandes movimentos',
  '{count} landed while you watched': '{count} chegaram enquanto você olhava',
  'Watching the chain': 'De olho na rede',
  'ALL': 'TUDO',
  'only {amount} SKR and up': 'só de {amount} SKR para cima',
  'everything, dust included': 'tudo, inclusive as migalhas',
  'Waiting for the next finalized event of this size.': 'Esperando o próximo evento confirmado desse tamanho.',

  // Eu: perfil e cartão
  'Leaving': 'Saindo',
  '1 position in cooldown': '1 posição em espera',
  '{count} positions in cooldown': '{count} posições em espera',
  'Ready now': 'Pronto agora',
  'Next unlock': 'Próximo desbloqueio',
  'Cooldown finished': 'Espera concluída',
  'Until this position is free': 'Até esta posição ficar livre',
  'Nothing queued': 'Nada na fila',
  'Your weight in the vault': 'Seu peso no cofre',
  'First stake {days} days ago, read from the oldest signature on your position account.': 'Primeiro stake há {days} dias, lido na assinatura mais antiga da sua conta de posição.',
  'Held at least {days} days. Your position has a long signature history, so the walk back is still going.': 'Pelo menos {days} dias. Sua posição tem um histórico longo de assinaturas, então a busca para trás ainda continua.',
  'Reading the age of your position from the chain…': 'Lendo na rede a idade da sua posição…',
  'Stake SKR': 'Fazer stake de SKR',
  'Drawing your card…': 'Desenhando seu cartão…',
  'Share your card': 'Compartilhar seu cartão',
  'Alerts armed': 'Avisos ligados',
  'Wake me at unlock': 'Me acorde no desbloqueio',
  'Refresh': 'Atualizar',
  'Disconnect': 'Desconectar',
  'This address holds no SKR position right now.': 'Este endereço não tem nenhuma posição de SKR agora.',
  'This wallet holds no SKR position yet. The first stake opens one; the position account costs a little rent once.': 'Esta carteira ainda não tem posição de SKR. O primeiro stake abre uma; a conta de posição custa um pouco de aluguel, uma vez só.',
  'This position is being looked at, not signed for. Connect the wallet that holds it to stake from it.': 'Esta posição está só sendo consultada, não assinada. Conecte a carteira que a tem para fazer stake a partir dela.',
  'Connect the wallet that holds your stake, or paste any public address. Nothing is signed.': 'Conecte a carteira que tem o seu stake, ou cole qualquer endereço público. Nada é assinado.',
  'Connect Solana Mobile': 'Conectar Solana Mobile',
  'OR': 'OU',
  'Paste a Solana address': 'Cole um endereço Solana',
  'Look up': 'Consultar',
  'WEIGHT': 'PESO',
  'POSITIONS': 'POSIÇÕES',
  'READ FROM': 'LIDO DE',
  '1 unlock alert armed on this phone.': '1 aviso de desbloqueio ligado neste telefone.',
  '{count} unlock alerts armed on this phone.': '{count} avisos de desbloqueio ligados neste telefone.',
  'Nothing left to wait for — the cooldown is already over.': 'Não falta mais nada: a espera já acabou.',
  'Caption copied. Paste it next to the picture.': 'Legenda copiada. Cole junto com a imagem.',
  'This phone would not take the caption — type it yourself.': 'Este telefone não aceitou a legenda: digite você mesmo.',
  'Your SKR staker card': 'Seu cartão de staker SKR',
  'This phone has nothing to share with.': 'Este telefone não tem com o que compartilhar.',
  'Hide my name on the card': 'Esconder meu nome no cartão',
  'The eye in the ring closes and the card says A Seeker.': 'O olho no anel se fecha e o cartão diz "A Seeker".',
  'Hide my amount on the card': 'Esconder meu valor no cartão',
  'Days, since and one-of stay; the position line goes.': 'Dias, data de início e "uma de N" ficam; a linha do valor sai.',
  'An exact amount next to a start date is close to a fingerprint. Your choice, said plainly.': 'Um valor exato junto de uma data de início é quase uma impressão digital. A escolha é sua, dito sem rodeios.',

  // Os dezesseis do dia
  'Sixteen': 'Dezesseis',
  'The daily sixteen': 'Os dezesseis do dia',
  '16 parts of 1 SKR, one approval. A small daily habit that keeps your position moving.': '16 partes de 1 SKR, uma só aprovação. Um pequeno hábito diário que mantém sua posição em movimento.',

  // Gorjeta
  'Support SKR Eyes': 'Apoie o SKR Eyes',
  'Send a tip': 'Dar gorjeta',
  'A tip in SKR': 'Uma gorjeta em SKR',
  'How much': 'Quanto',
  'Any amount you like. Goes to {name}, the wallet behind this app.': 'O valor que você quiser. Vai para {name}, a carteira por trás deste app.',
  'Send {amount} SKR to {name}': 'Enviar {amount} SKR para {name}',
  '{amount} SKR on its way to {name}': '{amount} SKR a caminho de {name}',
  'Thank you': 'Obrigado',
  'Done': 'Pronto',
  'Landing on chain…': 'Entrando na rede…',
  'Your wallet signs and sends it. The app only fetches a blockhash before and reads the status after.': 'Sua carteira assina e envia. O app só busca um blockhash antes e lê o status depois.',
  'A tip changes nothing about your position and nothing about any airdrop. It is a thank you, not a fee.': 'Uma gorjeta não muda nada na sua posição nem em nenhum airdrop. É um agradecimento, não uma taxa.',
  'Free and open source, built by one Seeker. Tips in SKR go to kosa.skr and are staked right away, all of them.': 'Gratuito e de código aberto, feito por um Seeker. As gorjetas em SKR vão para kosa.skr e entram em stake na hora, todas elas.',
  'This app is free, open source, and built by one Seeker. If it saved you a moment, a tip is welcome. Every SKR that arrives is staked right away, all of it.': 'Este app é gratuito, de código aberto e feito por um Seeker. Se ele te poupou um momento, uma gorjeta é bem-vinda. Cada SKR que chega entra em stake na hora, tudo.',
  'This is {name} itself. A tip to your own wallet moves nothing; try from another wallet.': 'Esta carteira é o próprio {name}. Uma gorjeta para a sua própria carteira não move nada; tente de outra carteira.',
  'The chain rejected the transfer.': 'A rede recusou a transferência.',
  'The wallet declined. Nothing was sent.': 'A carteira recusou. Nada foi enviado.',
  'The wallet returned no signature.': 'A carteira não devolveu nenhuma assinatura.',
  'SKR has six decimal places. Shorten the amount.': 'SKR tem seis casas decimais. Encurte o valor.',

  // Erros que a pessoa chega a ver
  'The finalized snapshot is still warming up. Try again in a moment.': 'A leitura confirmada ainda está sendo preparada. Tente daqui a pouco.',
  'This position could not be read': 'Não deu para ler esta posição',
  'The wallet request was cancelled': 'O pedido à carteira foi cancelado',
  'The wallet did not return an account.': 'A carteira não devolveu nenhuma conta.',
  'Alerts could not be scheduled': 'Não deu para programar os avisos',
  'The card is not ready yet': 'O cartão ainda não está pronto',
  'The card could not be drawn': 'Não deu para desenhar o cartão',
  'the chain returned no signatures': 'a rede não devolveu assinaturas',
  'age lookup failed': 'a consulta de idade falhou',
  'SKR Eyes API returned {status}': 'A API do SKR Eyes respondeu {status}',
  'The age service answered {status}': 'O serviço de idade respondeu {status}',

  // Tela de avisos
  'Notifications allowed': 'Notificações permitidas',
  'Notifications off': 'Notificações desligadas',
  'Alerts are scheduled on the phone itself. Nothing about you leaves the device.': 'Os avisos são programados pelo próprio telefone. Nada seu sai do aparelho.',
  'Allow notifications and this app can wake you exactly when your cooldown ends.': 'Permita as notificações e o app poderá te acordar na hora exata em que a espera acabar.',
  'Allow notifications': 'Permitir notificações',
  'Open settings': 'Abrir configurações',
  'This phone can now wake you.': 'Agora este telefone pode te acordar.',
  'Android will not ask again. Turn notifications on for SKR Eyes in the system settings.': 'O Android não vai perguntar de novo. Ligue as notificações do SKR Eyes nas configurações do sistema.',
  'Android is holding notifications back for this app.': 'O Android está segurando as notificações deste app.',
  'Android did not answer the permission request. Try again, or turn notifications on in the system settings.': 'O Android não respondeu ao pedido de permissão. Tente de novo ou ligue as notificações nas configurações do sistema.',
  'This phone would not open its settings screen.': 'Este telefone não abriu a tela de configurações.',
  'Wake me at my unlock': 'Me acorde no meu desbloqueio',
  'Connect your wallet on the Me screen and this switch becomes live.': 'Conecte sua carteira na aba Eu e esta chave passa a funcionar.',
  'One hour before, and again the moment the cooldown ends. Scheduled by this phone from the exact on-chain time.': 'Uma hora antes e de novo no momento em que a espera acaba. Programado por este telefone pela hora exata da rede.',
  'Nothing of yours is unlocking, so there is nothing to wake you for yet.': 'Você não tem nada desbloqueando, então ainda não há por que te acordar.',
  'Large moves, heard and felt': 'Grandes movimentos, ouvidos e sentidos',
  'A stake of 10K SKR or more rings like a glass coin, a stake of 100K rings the vault bell, an exit of 100K lands with a low boom. On every screen while the app is open, each with a short buzz.': 'Um stake de 10K SKR ou mais soa como uma moeda de vidro, um stake de 100K toca o sino do cofre, uma saída de 100K chega com um estrondo grave. Em qualquer tela enquanto o app está aberto, cada um com uma vibração curta.',
  'Other people\'s moves do not wake the phone while the app is closed. Only your own unlock does.': 'Os movimentos de outras pessoas não acordam o telefone com o app fechado. Só o seu próprio desbloqueio acorda.',
  'What counts as large': 'O que conta como grande',
  'Built-in thresholds behind the bell and the boom, until the server publishes its own.': 'Limites embutidos por trás do sino e do estrondo, até o servidor publicar os dele.',
  'These come from the server, move with real traffic, and drive the bell and the boom.': 'Estes vêm do servidor, acompanham o movimento real e comandam o sino e o estrondo.',
  'Send a test notification': 'Enviar uma notificação de teste',
  'A test notification will arrive in a few seconds.': 'A notificação de teste chega em alguns segundos.',
  'The test notification could not be scheduled': 'Não deu para programar a notificação de teste',
  '1 reminder set on this phone for your unlock.': '1 lembrete marcado neste telefone para o seu desbloqueio.',
  '{count} reminders set on this phone for your unlock.': '{count} lembretes marcados neste telefone para o seu desbloqueio.',
  'The reminders for your unlock were cancelled.': 'Os lembretes do seu desbloqueio foram cancelados.',
  'The alert could not be changed.': 'Não deu para mudar o aviso.',
  'Language': 'Idioma',
  'The app follows your phone until you choose here. The card you share stays in English, so it reads the same to everyone who sees it.': 'O app segue o idioma do telefone até você escolher aqui. O cartão que você compartilha continua em inglês, então todo mundo lê a mesma coisa.',

  // As próprias notificações
  'This wallet has no pending SKR unlock.': 'Esta carteira não tem desbloqueio de SKR pendente.',
  'SKR unlocks in 1 hour': 'SKR desbloqueia em 1 hora',
  'Your pending SKR is approaching its withdrawable time.': 'Seu SKR pendente está quase liberado para saque.',
  'Your SKR is now withdrawable': 'Seu SKR já pode ser sacado',
  'Open SKR Eyes to verify the finalized position and evidence.': 'Abra o SKR Eyes para conferir a posição confirmada e as provas.',
  'SKR Eyes alerts are ready': 'Os avisos do SKR Eyes estão prontos',
  'Test complete. Real unlock alerts will use finalized on-chain time.': 'Teste concluído. Os avisos de verdade vão usar a hora confirmada da rede.',

  // Janela de stake
  'Add to your position': 'Somar à sua posição',
  'Amount per transaction': 'Valor por transação',
  'SKR has six decimal places. Shorten the amount — the extra digits cannot be staked.': 'SKR tem seis casas decimais. Encurte o valor: os dígitos a mais não entram em stake.',
  'A single transaction cannot stake less than 1 SKR.': 'Uma transação não pode colocar menos de 1 SKR em stake.',
  'This is what one transaction stakes. The total is this amount times the count below.': 'É isto que uma transação coloca em stake. O total é este valor vezes o número abaixo.',
  'How many transactions': 'Quantas transações',
  'One transaction, one wallet approval.': 'Uma transação, uma aprovação na carteira.',
  '{count} identical transactions from one approval, sent one after another. Each one is a separate on-chain stake.': '{count} transações iguais com uma só aprovação, enviadas uma após a outra. Cada uma é um stake separado na rede.',
  'This needs {needed} SKR and you hold {held}. ': 'Isto precisa de {needed} SKR e você tem {held}. ',
  'At this amount you can send 1 part.': 'Com este valor dá para enviar 1 parte.',
  'At this amount you can send {count} parts.': 'Com este valor dá para enviar {count} partes.',
  'Lower the amount to stake what you have.': 'Diminua o valor para colocar em stake o que você tem.',
  'You hold {held} SKR.': 'Você tem {held} SKR.',
  'Before you sign': 'Antes de assinar',
  'sent as': 'enviado como',
  'you stake in total': 'total em stake',
  'position account rent': 'aluguel da conta de posição',
  'already paid': 'já pago',
  '{sol} SOL, once': '{sol} SOL, uma vez',
  'Your position account already exists, so only the network fee applies — a few thousand lamports per transaction.': 'Sua conta de posição já existe, então só entra a taxa de rede: alguns milhares de lamports por transação.',
  'The first stake creates your position account and its rent stays with the account. Network fees are a few thousand lamports per transaction.': 'O primeiro stake cria sua conta de posição e o aluguel fica nessa conta. A taxa de rede é de alguns milhares de lamports por transação.',
  'The app was closed while the wallet had this stake. Check your position before staking again, then clear this.': 'O app foi fechado enquanto a carteira estava com este stake. Confira sua posição antes de fazer stake de novo e depois limpe isto.',
  'The wallet that answered is not the one on screen. Connect the wallet that holds this position, then stake. Nothing was sent.': 'A carteira que respondeu não é a que está na tela. Conecte a carteira que tem esta posição e depois faça o stake. Nada foi enviado.',
  'Working…': 'Processando…',
  'At least 1 SKR per transaction': 'No mínimo 1 SKR por transação',
  'Sign and stake {amount} SKR': 'Assinar e colocar {amount} SKR em stake',
  'Sign and stake': 'Assinar e colocar em stake',
  'All parts landed': 'Todas as partes entraram',
  'Stopped': 'Parado',
  'Approve in your wallet': 'Aprove na sua carteira',
  'Preparing transactions': 'Preparando as transações',
  'A run from before': 'Um envio anterior',
  'Landing on chain': 'Entrando na rede',
  'pending': 'aguardando',
  'sending': 'enviando',
  'sent': 'enviada',
  'confirmed': 'confirmada',
  'unknown': 'desconhecido',
  'failed': 'falhou',
  'We do not know yet': 'Ainda não sabemos',
  'What happened': 'O que aconteceu',
  'Ask the chain again': 'Perguntar de novo à rede',
  'Stake again': 'Fazer stake de novo',
  'Discard and start over': 'Descartar e começar de novo',
  'Start over': 'Começar de novo',
  'Close': 'Fechar',
};
