// Português (do Brasil). A chave é a frase em inglês tal como está no código.
//
// Regras desta tabela: linguagem simples, sem palavras de marketing nem pontos
// de exclamação, tratamento por "você". Os tickers (SKR, SOL), o nome da
// carteira (Seed Vault) e o nome do app ficam como estão. Os números chegam já
// formatados: as chaves mudam de lugar, nunca de nome.
//
// Em português a frase fica cerca de um terço mais longa que em inglês, então
// os rótulos de cartão e de botão são mais curtos que a tradução literal.

export const pt: Record<string, string> = {
  // Abas e selo de atualidade
  'Pulse': 'Pulso',
  'Flow': 'Fluxo',
  'Me': 'Eu',
  'Queue': 'Fila',
  'Alerts': 'Avisos',
  'fresh': 'em dia',
  'aging': 'envelhecendo',
  'stale': 'defasado',
  'unavailable': 'sem dados',
  'syncing': 'sincronizando',
  'every number has a receipt': 'todo número tem comprovante',

  // Pulso
  'Staked of total supply': 'Em stake do total emitido',
  '{percent}% of the {supply} SKR total supply · {positions} positions': '{percent}% dos {supply} SKR emitidos · {positions} posições',
  'Waiting for a finalized answer': 'Esperando uma resposta confirmada',
  'Reading the vault': 'Lendo o cofre',
  'Network unavailable': 'Sem rede',
  'Last 24 hours': 'Últimas 24 horas',
  'Last 7 days': 'Últimos 7 dias',
  'Last 30 days': 'Últimos 30 dias',
  '{amount} staked': '{amount} em stake',
  '{amount} asked out': '{amount} pediu saída',
  'staked': 'em stake',
  'asked out': 'pediu saída',
  '{count} wallets': '{count} carteiras',
  'one bar per hour': 'uma barra por hora',
  '{range} as one total · daily bars need a server pass': '{range} em um total só · barras por dia quem calcula é o servidor',
  '{sign}{amount} net': 'líquido {sign}{amount}',
  'history covers {days}d': 'histórico de {days} d',
  'In cooldown': 'Esfriando',
  '{count} positions waiting out the 48 hours': '{count} posições cumprindo as 48 horas',
  'Ready to exit': 'Pronto para sair',
  'Cooldown finished, not yet withdrawn': 'Esfriamento acabou, ainda não sacado',
  'When the queue matures': 'Quando a fila vence',
  'ready': 'pronto',

  // Fila
  'Ready to withdraw': 'Pronto para sacar',
  '{amount} SKR is still cooling down across {count} positions': 'Ainda há {amount} SKR esfriando em {count} posições',
  'Reading the queue': 'Lendo a fila',
  'Time to maturity': 'Tempo até vencer',
  'Exits in flight, soonest first': 'Saídas em andamento, as mais próximas primeiro',
  '{count} shown': '{count} na tela',
  'Nothing is queued to leave right now.': 'Agora não há nada na fila para sair.',

  // Fluxo
  'Live from the vault': 'Ao vivo do cofre',
  'Reconnecting': 'Reconectando',
  'BUZZ ON': 'VIBRA SIM',
  'BUZZ OFF': 'VIBRA NÃO',
  'SOUND ON': 'SOM SIM',
  'SOUND OFF': 'SOM NÃO',
  'Biggest seen today': 'Maior de hoje',
  'Last big move': 'Último movimento grande',
  '{age} ago': 'há {age}',
  'slot {slot}': 'slot {slot}',
  'amount unavailable': 'valor indisponível',
  'withdrew': 'sacou',
  'cancelled exit': 'cancelou a saída',
  'stake': 'stake',
  'unstake': 'saída',
  'withdraw': 'saque',
  'Fold the older large moves': 'Recolher os movimentos grandes anteriores',
  '1 more large move': 'mais 1 movimento grande',
  '{count} more large moves': 'mais {count} movimentos grandes',
  '{count} landed while you watched': '{count} chegaram enquanto você olhava',
  'Watching the chain': 'De olho na rede',
  'While you were away': 'Enquanto você não estava',
  'One large move landed': 'Chegou 1 movimento grande',
  '{count} large moves landed': 'Chegaram {count} movimentos grandes',
  ', the biggest {amount} SKR {verb}': ', o maior de {amount} SKR {verb}',
  'ALL': 'TUDO',
  'only {amount} SKR and up': 'só de {amount} SKR para cima',
  'everything, dust included': 'tudo, inclusive as migalhas',
  'Waiting for the next finalized event of this size.': 'Esperando o próximo evento confirmado desse tamanho.',

  // Eu — perfil e cartão
  'Leaving': 'Saindo',
  '{count} position(s) in cooldown': '{count} posição(ões) esfriando',
  'Ready now': 'Pronto agora',
  'Next unlock': 'Próximo desbloqueio',
  'Cooldown finished': 'Esfriamento acabou',
  'Until this position is free': 'Até esta posição ficar livre',
  'Nothing queued': 'Nada na fila',
  'Your weight in the vault': 'Seu peso no cofre',
  'First stake {days} days ago, read from the oldest signature on your position account.': 'Primeiro stake há {days} dias, lido na assinatura mais antiga da sua conta de posição.',
  'Held at least {days} days. Your position has a long signature history, so the walk back is still going.': 'Pelo menos {days} dias. Sua posição tem um histórico longo de assinaturas, então a volta ainda está em andamento.',
  'Reading the age of your position from the chain…': 'Lendo na rede a idade da sua posição…',
  'Stake SKR': 'Fazer stake de SKR',
  'Drawing your card…': 'Desenhando seu cartão…',
  'Share your card': 'Compartilhar seu cartão',
  'Alerts armed': 'Avisos ligados',
  'Wake me at unlock': 'Me acorde no desbloqueio',
  'Refresh': 'Atualizar',
  'Disconnect': 'Desconectar',
  'This address holds no SKR position right now.': 'Este endereço não tem nenhuma posição de SKR agora.',
  'Connect the wallet that holds your stake, or paste any public address. Nothing is signed.': 'Conecte a carteira que tem o seu stake, ou cole qualquer endereço público. Nada é assinado.',
  'Connect Solana Mobile': 'Conectar Solana Mobile',
  'OR': 'OU',
  'Paste a Solana address': 'Cole um endereço Solana',
  'Look up': 'Consultar',
  'WEIGHT': 'PESO',
  'POSITIONS': 'POSIÇÕES',
  'READ FROM': 'LIDO DE',
  'Connect the wallet that holds your stake to fill this card in.': 'Conecte a carteira que tem o seu stake e o cartão se preenche.',
  '1 unlock alert armed on this phone.': '1 aviso de desbloqueio ligado neste telefone.',
  '{count} unlock alerts armed on this phone.': '{count} avisos de desbloqueio ligados neste telefone.',
  'Nothing left to wait for — the cooldown is already over.': 'Não há mais o que esperar: o esfriamento já acabou.',
  'Caption copied. Paste it next to the picture.': 'Legenda copiada. Cole junto com a imagem.',
  'This phone would not take the caption — type it yourself.': 'Este telefone não aceitou a legenda: digite você mesmo.',
  'Your SKR staker card': 'Seu cartão de staker SKR',
  'This phone has nothing to share with.': 'Este telefone não tem com o que compartilhar.',

  // Erros que a pessoa chega a ver
  'The finalized snapshot is still warming up. Try again in a moment.': 'A leitura confirmada ainda está sendo preparada. Tente daqui a pouco.',
  'This position could not be read': 'Não deu para ler esta posição',
  'The wallet request was cancelled': 'O pedido à carteira foi cancelado',
  'The wallet did not return an account.': 'A carteira não devolveu nenhuma conta.',
  'Alerts could not be scheduled': 'Não deu para programar os avisos',
  'The card is not ready yet': 'O cartão ainda não está pronto',
  'The card could not be drawn': 'Não deu para desenhar o cartão',
  'the chain returned no signatures': 'a rede não devolveu assinaturas',
  'age lookup failed': 'a consulta de idade falhou',
  'SKR Eyes API returned {status}': 'A API do SKR Eyes respondeu {status}',
  'The age service answered {status}': 'O serviço de idade respondeu {status}',

  // Tela de avisos
  'Notifications allowed': 'Notificações permitidas',
  'Notifications off': 'Notificações desligadas',
  'Alerts are scheduled on the phone itself. Nothing about you leaves the device.': 'Os avisos são programados pelo próprio telefone. Nada seu sai do aparelho.',
  'Allow notifications and this app can wake you exactly when your cooldown ends.': 'Permita as notificações e o app poderá te acordar na hora exata em que o esfriamento acabar.',
  'Allow notifications': 'Permitir notificações',
  'Open settings': 'Abrir configurações',
  'This phone can now wake you.': 'Agora este telefone pode te acordar.',
  'Android will not ask again. Turn notifications on for SKR Eyes in the system settings.': 'O Android não vai perguntar de novo. Ligue as notificações do SKR Eyes nas configurações do sistema.',
  'Android is holding notifications back for this app.': 'O Android está segurando as notificações deste app.',
  'Android did not answer the permission request. Try again, or turn notifications on in the system settings.': 'O Android não respondeu ao pedido de permissão. Tente de novo ou ligue as notificações nas configurações do sistema.',
  'This phone would not open its settings screen.': 'Este telefone não abriu a tela de configurações.',
  'Wake me at my unlock': 'Me acorde no meu desbloqueio',
  'Connect your wallet on the Me screen and this switch becomes live.': 'Conecte sua carteira na aba Eu e esta chave passa a funcionar.',
  'One hour before, and again the moment the cooldown ends. Scheduled by this phone from the exact on-chain time.': 'Uma hora antes e de novo no momento em que o esfriamento acaba. Programado por este telefone pela hora exata da rede.',
  'Nothing of yours is unlocking, so there is nothing to wake you for yet.': 'Você não tem nada desbloqueando, então ainda não há por que te acordar.',
  'Large moves while you were away': 'Movimentos grandes enquanto você não estava',
  'Anything above the threshold below is summed up at the top of Flow when you come back to it, and lands with a chime and a buzz while you are watching.': 'Tudo acima do limite abaixo aparece somado no topo do Fluxo quando você voltar, e chega com som e vibração enquanto você estiver olhando.',
  "Waking the phone for someone else's large move while the app is closed needs a background check that Android schedules on its own terms. That is the next version — promising it here before it exists would be the same lie this screen just removed.": 'Acordar o telefone por causa do movimento grande de outra pessoa com o app fechado exige uma verificação em segundo plano que o Android agenda pelas regras dele. Isso é a próxima versão: prometer aqui antes de existir seria a mesma mentira que esta tela acabou de tirar.',
  'What counts as large in Flow': 'O que conta como grande no Fluxo',
  'Built-in thresholds, used by the chime and the buzz on the Flow screen, until the server publishes its own.': 'Limites embutidos: mandam no som e na vibração do Fluxo até o servidor publicar os dele.',
  'These come from the server, move with real traffic, and drive the chime and the buzz on the Flow screen.': 'Estes vêm do servidor, acompanham o movimento real e comandam o som e a vibração do Fluxo.',
  'Send a test notification': 'Enviar uma notificação de teste',
  'A test notification will arrive in a few seconds.': 'A notificação de teste chega em alguns segundos.',
  'The test notification could not be scheduled': 'Não deu para programar a notificação de teste',
  '1 reminder set on this phone for your unlock.': '1 lembrete marcado neste telefone para o seu desbloqueio.',
  '{count} reminders set on this phone for your unlock.': '{count} lembretes marcados neste telefone para o seu desbloqueio.',
  'The reminders for your unlock were cancelled.': 'Os lembretes do seu desbloqueio foram cancelados.',
  'The alert could not be changed.': 'Não deu para mudar o aviso.',
  'Language': 'Idioma',
  'The app follows your phone until you choose here. The card you share stays in English, so it reads the same to everyone who sees it.': 'O app segue o idioma do telefone até você escolher aqui. O cartão que você compartilha continua em inglês, para que todo mundo que vir leia a mesma coisa.',

  // As próprias notificações
  'This wallet has no pending SKR unlock.': 'Esta carteira não tem desbloqueio de SKR pendente.',
  'SKR unlocks in 1 hour': 'SKR desbloqueia em 1 hora',
  'Your pending SKR is approaching its withdrawable time.': 'Seus SKR pendentes estão chegando na hora de sacar.',
  'Your SKR is now withdrawable': 'Seus SKR já podem ser sacados',
  'Open SKR Eyes to verify the finalized position and evidence.': 'Abra o SKR Eyes para conferir a posição confirmada e as provas.',
  'SKR Eyes alerts are ready': 'Os avisos do SKR Eyes estão prontos',
  'Test complete. Real unlock alerts will use finalized on-chain time.': 'Teste concluído. Os avisos de verdade vão usar a hora confirmada da rede.',

  // Janela de stake
  'Add to your position': 'Somar à sua posição',
  'Amount per transaction': 'Valor por transação',
  'SKR has six decimal places. Shorten the amount — the extra digits cannot be staked.': 'SKR tem seis casas decimais. Encurte o valor: os dígitos a mais não entram em stake.',
  'A single transaction cannot stake less than 1 SKR.': 'Uma transação sozinha não pode colocar menos de 1 SKR em stake.',
  'This is what one transaction stakes. The total is this amount times the count below.': 'É isto que uma transação coloca em stake. O total é este valor vezes o número abaixo.',
  'How many transactions': 'Quantas transações',
  'One transaction, one wallet approval.': 'Uma transação, uma confirmação na carteira.',
  '{count} identical transactions from one approval, sent one after another. Each one is a separate on-chain stake.': '{count} transações iguais com uma só confirmação, enviadas uma após a outra. Cada uma é um stake separado na rede.',
  'This needs {needed} SKR and you hold {held}. ': 'Isto precisa de {needed} SKR e você tem {held}. ',
  'At this amount you can send 1 part.': 'Com este valor dá para enviar 1 parte.',
  'At this amount you can send {count} parts.': 'Com este valor dá para enviar {count} partes.',
  'Lower the amount to stake what you have.': 'Diminua o valor para colocar em stake o que você tem.',
  'You hold {held} SKR.': 'Você tem {held} SKR.',
  'Before you sign': 'Antes de assinar',
  'sent as': 'enviado como',
  'you stake in total': 'você coloca no total',
  'position account rent': 'aluguel da conta de posição',
  'already paid': 'já pago',
  '{sol} SOL, once': '{sol} SOL, uma vez',
  'Your position account already exists, so only the network fee applies — a few thousand lamports per transaction.': 'Sua conta de posição já existe, então só entra a taxa de rede: alguns milhares de lamports por transação.',
  'The first stake creates your position account and its rent stays with the account. Network fees are a few thousand lamports per transaction.': 'O primeiro stake cria sua conta de posição e o aluguel fica nessa conta. A taxa de rede é de alguns milhares de lamports por transação.',
  'Working…': 'Trabalhando…',
  'At least 1 SKR per transaction': 'No mínimo 1 SKR por transação',
  'Sign and stake {amount} SKR': 'Assinar e colocar {amount} SKR em stake',
  'Sign and stake': 'Assinar e colocar em stake',
  'All parts landed': 'Todas as partes entraram',
  'Stopped': 'Parado',
  'Approve in your wallet': 'Confirme na sua carteira',
  'Preparing transactions': 'Preparando as transações',
  'A run from before': 'Um envio de antes',
  'Landing on chain': 'Entrando na rede',
  'pending': 'aguardando',
  'sending': 'enviando',
  'sent': 'enviada',
  'confirmed': 'confirmada',
  'unknown': 'desconhecido',
  'failed': 'falhou',
  'We do not know yet': 'Ainda não sabemos',
  'What happened': 'O que aconteceu',
  'Ask the chain again': 'Perguntar de novo à rede',
  'Stake again': 'Fazer stake de novo',
  'Discard and start over': 'Descartar e começar de novo',
  'Start over': 'Começar de novo',
  'Close': 'Fechar',
};
