// Русский. Ключ: сама английская фраза из кода.
//
// Правила этого файла, чтобы второй переводчик держал ту же интонацию:
// простая речь, без рекламных слов и восклицательных знаков. Без обращения
// на «ты» и «вы»: безличные и инфинитивные формы. Тикеры (SKR, SOL), имя
// кошелька (Seed Vault) и название приложения остаются латиницей, человек
// видит их такими везде. Числа приходят уже собранными, скобки можно
// двигать, но не менять. Длинных тире нет, вместо них запятая или точка.
//
// Русский длиннее английского примерно на треть, поэтому подписи на плитках
// и кнопках намеренно короче дословного перевода.

export const ru: Record<string, string> = {
  'Vault': 'Хранилище',
  'over the last 7 days': 'за последние 7 дней',
  'over the last 30 days': 'за последние 30 дней',
  '{percent}% of all SKR is staked': '{percent}% всех SKR в стейке',
  'over the last 24 hours': 'за последние сутки',
  'net': 'итог',
  'wallets': 'кошельков',
  // Вкладки и значок свежести
  'Flow': 'Поток',
  'Me': 'Я',
  'Queue': 'Очередь',
  'Alerts': 'Сигналы',
  'fresh': 'свежо',
  'aging': 'стареет',
  'stale': 'устарело',
  'unavailable': 'нет связи',
  'syncing': 'обновляем',
  'every number has a receipt': 'у каждого числа есть чек',

  // Хранилище (сцена)
  'Waiting for a finalized answer': 'Ждём подтверждённый ответ',
  'Reading the vault': 'Читаем хранилище',
  'Network unavailable': 'Сеть недоступна',
  'Last 24 hours': 'Сутки',
  'Last 7 days': '7 дней',
  'Last 30 days': '30 дней',
  '24h': '24ч',
  'staked': 'застейкано',
  'in': 'в стейк',
  'asked out': 'на выход',
  'staked minus requested out': 'стейк минус запросы на выход',
  'history covers {days}d': 'история за {days} дн.',
  'In cooldown': 'Остывает',
  'cooling down': 'остывает',
  '{count} positions waiting out the 48 hours': '{count} позиций ждут свои 48 часов',
  'Ready to exit': 'Готово к выходу',
  'Cooldown finished, not yet withdrawn': 'Остыло, но ещё не забрали',
  'When the queue matures': 'Когда созреет очередь',
  'ready': 'готово',
  'ready to withdraw': 'можно забрать',
  'Motion': 'Движение',
  'The vault stands still.': 'Хранилище стоит неподвижно.',
  'One gentle frame a second.': 'Один плавный кадр в секунду.',
  'Live while you watch. Calm after 90 seconds without a touch.': 'Живо, пока смотрят. Через 90 секунд без касаний переходит в спокойный режим.',
  'Receipt': 'Чек',
  'Open on Solscan': 'Открыть в Solscan',

  // Очередь
  'Exits in flight, soonest first': 'Выходы в пути, ближайшие сверху',
  '{count} shown': 'показано {count}',
  'Show all {count}': 'Показать все {count}',
  'Show fewer': 'Свернуть',
  'Nothing is queued to leave right now.': 'Сейчас на выход никто не стоит.',

  // Поток
  'Live from the vault': 'Прямо из хранилища',
  'Reconnecting': 'Переподключаемся',
  'BUZZ ON': 'ВИБРО ВКЛ',
  'BUZZ OFF': 'ВИБРО ВЫКЛ',
  'SOUND ON': 'ЗВУК ВКЛ',
  'SOUND OFF': 'ЗВУК ВЫКЛ',
  'Biggest seen today': 'Крупнейшее за сегодня',
  'Biggest stake today': 'Крупнейший стейк за сегодня',
  'Biggest exit today': 'Крупнейший выход за сегодня',
  'Biggest withdrawal today': 'Крупнейший вывод за сегодня',
  'Last big move': 'Последнее крупное',
  '{age} ago': '{age} назад',
  'slot {slot}': 'слот {slot}',
  'amount unavailable': 'сумма недоступна',
  'withdrew': 'забрал',
  'cancelled exit': 'отменил выход',
  'stake': 'стейк',
  'unstake': 'выход',
  'withdraw': 'вывод',
  'Fold the older large moves': 'Свернуть прежние крупные',
  '1 more large move': 'ещё 1 крупное',
  '{count} more large moves': 'ещё {count} крупных',
  '{count} landed while you watched': '{count} пришло на глазах',
  'Watching the chain': 'Следим за цепочкой',
  'ALL': 'ВСЁ',
  'only {amount} SKR and up': 'только от {amount} SKR',
  'everything, dust included': 'всё, вместе с мелочью',
  'Waiting for the next finalized event of this size.': 'Ждём следующее подтверждённое событие такого размера.',

  // Я: профиль и карточка
  'Leaving': 'Уходит',
  '1 position in cooldown': '1 позиция остывает',
  '{count} positions in cooldown': 'остывает позиций: {count}',
  'Ready now': 'Уже готово',
  'Next unlock': 'Ближайшая разблокировка',
  'Cooldown finished': 'Остывание закончилось',
  'Until this position is free': 'Пока позиция не освободится',
  'Nothing queued': 'Очереди нет',
  'Your weight in the vault': 'Вес в хранилище',
  'First stake {days} days ago, read from the oldest signature on your position account.': 'Первый стейк {days} дней назад, по самой старой подписи на аккаунте позиции.',
  'Held at least {days} days. Your position has a long signature history, so the walk back is still going.': 'Держится минимум {days} дней. У позиции длинная история подписей, обход ещё идёт.',
  'Reading the age of your position from the chain…': 'Читаем возраст позиции из цепочки…',
  'Stake SKR': 'Застейкать SKR',
  'Drawing your card…': 'Рисуем карточку…',
  'Share your card': 'Поделиться карточкой',
  'Alerts armed': 'Оповещения поставлены',
  'Wake me at unlock': 'Разбудить при разблокировке',
  'Refresh': 'Обновить',
  'Disconnect': 'Отключить',
  'This address holds no SKR position right now.': 'На этом адресе сейчас нет позиции SKR.',
  'Connect the wallet that holds your stake, or paste any public address. Nothing is signed.': 'Можно подключить кошелёк со стейком или вставить любой публичный адрес. Ничего не подписывается.',
  'Connect Solana Mobile': 'Подключить Solana Mobile',
  'OR': 'ИЛИ',
  'Paste a Solana address': 'Вставить адрес Solana',
  'Look up': 'Найти',
  'WEIGHT': 'ВЕС',
  'POSITIONS': 'ПОЗИЦИЙ',
  'READ FROM': 'ИСТОЧНИК',
  'This position is being looked at, not signed for. Connect the wallet that holds it to stake from it.': 'Эту позицию только смотрят, подписывать за неё нельзя. Чтобы стейкать с неё, нужно подключить кошелёк, который её держит.',
  'This wallet holds no SKR position yet. The first stake opens one; the position account costs a little rent once.': 'У этого кошелька пока нет позиции SKR. Первый стейк её откроет; аккаунт позиции один раз возьмёт немного ренты.',
  '1 unlock alert armed on this phone.': 'На этом телефоне поставлено 1 оповещение о разблокировке.',
  '{count} unlock alerts armed on this phone.': 'На этом телефоне поставлено {count} оповещений о разблокировке.',
  'Nothing left to wait for — the cooldown is already over.': 'Ждать нечего, остывание уже закончилось.',
  'Caption copied. Paste it next to the picture.': 'Подпись скопирована, её можно вставить рядом с картинкой.',
  'This phone would not take the caption — type it yourself.': 'Телефон не принял подпись, придётся набрать её вручную.',
  'Your SKR staker card': 'Карточка стейкера SKR',
  'This phone has nothing to share with.': 'На этом телефоне нечем поделиться.',
  'Hide my name on the card': 'Скрыть имя на карточке',
  'The eye in the ring closes and the card says A Seeker.': 'Глаз в кольце закрывается, и на карточке будет написано A Seeker.',
  'Hide my amount on the card': 'Скрыть сумму на карточке',
  'Days, since and one-of stay; the position line goes.': 'Дни, дата начала и «одна из» остаются, строка с позицией уходит.',
  'An exact amount next to a start date is close to a fingerprint. Your choice, said plainly.': 'Точная сумма рядом с датой начала почти как отпечаток пальца. Это личный выбор, говорим как есть.',

  // Шестнадцать
  'Sixteen': 'Шестнадцать',
  'The daily sixteen': 'Ежедневные шестнадцать',
  '16 parts of 1 SKR, one approval. A small daily habit that keeps your position moving.': '1 SKR шестнадцатью частями, одно подтверждение. Маленькая ежедневная привычка, которая держит позицию в движении.',

  // Чаевые
  'Support SKR Eyes': 'Поддержать SKR Eyes',
  'Send a tip': 'Оставить чаевые',
  'A tip in SKR': 'Чаевые в SKR',
  'How much': 'Сколько',
  'Any amount you like. Goes to {name}, the wallet behind this app.': 'Любая сумма. Уйдёт на {name}, кошелёк автора этого приложения.',
  'Send {amount} SKR to {name}': 'Отправить {amount} SKR на {name}',
  '{amount} SKR on its way to {name}': '{amount} SKR в пути к {name}',
  'Thank you': 'Спасибо',
  'Done': 'Готово',
  'Landing on chain…': 'Ложится в цепочку…',
  'Your wallet signs and sends it. The app only fetches a blockhash before and reads the status after.': 'Подписывает и отправляет кошелёк. Приложение только берёт блокхеш до и читает статус после.',
  'A tip changes nothing about your position and nothing about any airdrop. It is a thank you, not a fee.': 'Чаевые никак не влияют ни на позицию, ни на какой-либо аирдроп. Это спасибо, а не плата.',
  'Free and open source, built by one Seeker. Tips in SKR go to kosa.skr and are staked right away, all of them.': 'Бесплатно и с открытым кодом, сделано одним владельцем Seeker. Чаевые в SKR уходят на kosa.skr и сразу целиком идут в стейк.',
  'This app is free, open source, and built by one Seeker. If it saved you a moment, a tip is welcome. Every SKR that arrives is staked right away, all of it.': 'Приложение бесплатное, с открытым кодом, сделано одним владельцем Seeker. Если оно сэкономило минуту, чаевые будут кстати. Каждый пришедший SKR сразу целиком идёт в стейк.',
  'This is {name} itself. A tip to your own wallet moves nothing; try from another wallet.': 'Это и есть {name}. Чаевые на собственный кошелёк ничего не двигают, нужен другой кошелёк.',
  'The chain rejected the transfer.': 'Цепочка отклонила перевод.',
  'The wallet declined. Nothing was sent.': 'Кошелёк отказал. Ничего не отправлено.',
  'The wallet returned no signature.': 'Кошелёк не вернул подпись.',
  'SKR has six decimal places. Shorten the amount.': 'У SKR шесть знаков после запятой. Сумму нужно укоротить.',

  // Ошибки, которые человек действительно видит
  'The finalized snapshot is still warming up. Try again in a moment.': 'Подтверждённый снимок ещё готовится. Через минуту можно попробовать снова.',
  'This position could not be read': 'Не удалось прочитать эту позицию',
  'The wallet request was cancelled': 'Запрос к кошельку отменён',
  'The wallet did not return an account.': 'Кошелёк не вернул аккаунт.',
  'Alerts could not be scheduled': 'Не удалось поставить оповещения',
  'The card is not ready yet': 'Карточка ещё не готова',
  'The card could not be drawn': 'Не удалось нарисовать карточку',
  'the chain returned no signatures': 'цепочка не вернула подписей',
  'age lookup failed': 'не удалось узнать возраст',
  'SKR Eyes API returned {status}': 'API SKR Eyes ответил {status}',
  'The age service answered {status}': 'Служба возраста ответила {status}',
  'The app was closed while the wallet had this stake. Check your position before staking again, then clear this.': 'Приложение закрылось, пока кошелёк держал этот стейк. Перед новым стейком стоит проверить позицию, а потом убрать это.',
  'The wallet that answered is not the one on screen. Connect the wallet that holds this position, then stake. Nothing was sent.': 'Ответил не тот кошелёк, что на экране. Нужно подключить кошелёк с этой позицией и тогда стейкать. Ничего не отправлено.',

  // Экран оповещений
  'Notifications allowed': 'Уведомления разрешены',
  'Notifications off': 'Уведомления выключены',
  'Alerts are scheduled on the phone itself. Nothing about you leaves the device.': 'Оповещения ставит сам телефон. Никакие данные с устройства не уходят.',
  'Allow notifications and this app can wake you exactly when your cooldown ends.': 'Если разрешить уведомления, приложение разбудит ровно в момент конца остывания.',
  'Allow notifications': 'Разрешить уведомления',
  'Open settings': 'Открыть настройки',
  'This phone can now wake you.': 'Теперь телефон сможет разбудить.',
  'Android will not ask again. Turn notifications on for SKR Eyes in the system settings.': 'Android больше не спросит. Уведомления для SKR Eyes включаются в системных настройках.',
  'Android is holding notifications back for this app.': 'Android придерживает уведомления этого приложения.',
  'Android did not answer the permission request. Try again, or turn notifications on in the system settings.': 'Android не ответил на запрос разрешения. Можно попробовать ещё раз или включить уведомления в системных настройках.',
  'This phone would not open its settings screen.': 'Телефон не открыл свои настройки.',
  'Wake me at my unlock': 'Разбудить, когда разблокируется',
  'Connect your wallet on the Me screen and this switch becomes live.': 'Переключатель заработает после подключения кошелька на вкладке «Я».',
  'One hour before, and again the moment the cooldown ends. Scheduled by this phone from the exact on-chain time.': 'За час до и ещё раз в момент конца остывания. Ставит сам телефон по точному времени из цепочки.',
  'Nothing of yours is unlocking, so there is nothing to wake you for yet.': 'Ничего не разблокируется, так что будить пока незачем.',
  'Large moves, heard and felt': 'Крупные движения, звуком и вибрацией',
  'A stake of 1K SKR or more rings like a glass coin, a stake of 100K rings the vault bell, an exit of 100K lands with a low boom. On every screen while the app is open, each with a short buzz.': 'Стейк от 1K SKR звенит как стеклянная монета, стейк от 100K бьёт в колокол хранилища, выход на 100K ложится низким гулом. На любом экране, пока приложение открыто, и каждый раз с короткой вибрацией.',
  "Other people's moves do not wake the phone while the app is closed. Only your own unlock does.": 'Чужие движения не будят телефон, пока приложение закрыто. Будит только собственная разблокировка.',
  'What counts as large': 'Что считается крупным',
  'Built-in thresholds behind the bell and the boom, until the server publishes its own.': 'Встроенные пороги для колокола и гула, пока сервер не опубликует свои.',
  'These come from the server, move with real traffic, and drive the bell and the boom.': 'Эти приходят с сервера, двигаются вместе с реальным потоком и управляют колоколом и гулом.',
  'Send a test notification': 'Отправить тестовое уведомление',
  'A test notification will arrive in a few seconds.': 'Тестовое уведомление придёт через несколько секунд.',
  'The test notification could not be scheduled': 'Не удалось поставить тестовое уведомление',
  '1 reminder set on this phone for your unlock.': 'На этом телефоне поставлено 1 напоминание о разблокировке.',
  '{count} reminders set on this phone for your unlock.': 'На этом телефоне поставлено {count} напоминаний о разблокировке.',
  'The reminders for your unlock were cancelled.': 'Напоминания о разблокировке отменены.',
  'The alert could not be changed.': 'Не удалось изменить оповещение.',
  'Language': 'Язык',
  'The app follows your phone until you choose here. The card you share stays in English, so it reads the same to everyone who sees it.': 'Пока язык не выбран здесь, приложение идёт за языком телефона. Карточка для отправки всегда на английском, чтобы все прочитали её одинаково.',

  // Сами уведомления
  'This wallet has no pending SKR unlock.': 'У этого кошелька нет SKR в ожидании разблокировки.',
  'SKR unlocks in 1 hour': 'SKR разблокируется через час',
  'Your pending SKR is approaching its withdrawable time.': 'SKR в ожидании скоро можно будет забрать.',
  'Your SKR is now withdrawable': 'SKR теперь можно забрать',
  'Open SKR Eyes to verify the finalized position and evidence.': 'В SKR Eyes можно проверить подтверждённую позицию и доказательства.',
  'SKR Eyes alerts are ready': 'Оповещения SKR Eyes готовы',
  'Test complete. Real unlock alerts will use finalized on-chain time.': 'Проверка прошла. Настоящие оповещения пойдут по подтверждённому времени из цепочки.',

  // Окно стейка
  'Add to your position': 'Добавить к позиции',
  'Amount per transaction': 'Сумма одной транзакции',
  'SKR has six decimal places. Shorten the amount — the extra digits cannot be staked.': 'У SKR шесть знаков после запятой. Сумму нужно укоротить, лишние цифры застейкать нельзя.',
  'A single transaction cannot stake less than 1 SKR.': 'Одной транзакцией нельзя застейкать меньше 1 SKR.',
  'This is what one transaction stakes. The total is this amount times the count below.': 'Столько стейкает одна транзакция. Итог: эта сумма, умноженная на число ниже.',
  'How many transactions': 'Сколько транзакций',
  'One transaction, one wallet approval.': 'Одна транзакция, одно подтверждение в кошельке.',
  '{count} identical transactions from one approval, sent one after another. Each one is a separate on-chain stake.': '{count} одинаковых транзакций с одного подтверждения, уходят одна за другой. Каждая из них отдельный стейк в цепочке.',
  'This needs {needed} SKR and you hold {held}. ': 'Нужно {needed} SKR, а на балансе {held}. ',
  'At this amount you can send 1 part.': 'На эту сумму выйдет 1 часть.',
  'At this amount you can send {count} parts.': 'На эту сумму выйдет частей: {count}.',
  'Lower the amount to stake what you have.': 'Чтобы застейкать то, что есть, сумму нужно уменьшить.',
  'You hold {held} SKR.': 'На балансе {held} SKR.',
  'Before you sign': 'Перед подписью',
  'sent as': 'уйдёт как',
  'you stake in total': 'всего в стейк',
  'position account rent': 'рента аккаунта позиции',
  'already paid': 'уже оплачена',
  '{sol} SOL, once': '{sol} SOL, один раз',
  'Your position account already exists, so only the network fee applies — a few thousand lamports per transaction.': 'Аккаунт позиции уже есть, поэтому платится только комиссия сети, несколько тысяч лампортов за транзакцию.',
  'The first stake creates your position account and its rent stays with the account. Network fees are a few thousand lamports per transaction.': 'Первый стейк создаёт аккаунт позиции, и рента остаётся на этом аккаунте. Комиссия сети: несколько тысяч лампортов за транзакцию.',
  'Working…': 'Работаем…',
  'At least 1 SKR per transaction': 'Минимум 1 SKR на транзакцию',
  'Sign and stake {amount} SKR': 'Подписать и застейкать {amount} SKR',
  'Sign and stake': 'Подписать и застейкать',
  'All parts landed': 'Все части прошли',
  'Stopped': 'Остановлено',
  'Approve in your wallet': 'Подтверждение в кошельке',
  'Preparing transactions': 'Готовим транзакции',
  'A run from before': 'Запуск с прошлого раза',
  'Landing on chain': 'Ложится в цепочку',
  'pending': 'ждёт',
  'sending': 'отправка',
  'sent': 'отправлено',
  'confirmed': 'подтверждено',
  'unknown': 'неизвестно',
  'failed': 'не прошло',
  'We do not know yet': 'Пока неизвестно',
  'What happened': 'Что случилось',
  'Ask the chain again': 'Спросить цепочку ещё раз',
  'Stake again': 'Застейкать ещё',
  'Discard and start over': 'Сбросить и начать заново',
  'Start over': 'Начать заново',
  'Close': 'Закрыть',
};
