// Русский. Ключ — сама английская фраза из кода.
//
// Правила этого файла, чтобы второй переводчик держал ту же интонацию:
// простая речь, без рекламных слов и восклицательных знаков. Тикеры (SKR,
// SOL), имя кошелька (Seed Vault) и название приложения остаются латиницей —
// человек видит их такими везде. Числа приходят уже собранными, скобки можно
// двигать, но не менять.
//
// Русский длиннее английского примерно на треть, поэтому подписи на плитках
// и кнопках намеренно короче дословного перевода.

export const ru: Record<string, string> = {
  'over the last 7 days': 'за последние 7 дней',
  'over the last 30 days': 'за последние 30 дней',
  '{percent}% of all SKR is staked': '{percent}% всех SKR в стейке',
  'over the last 24 hours': 'за последние сутки',
  'net': 'итог',
  'wallets': 'кошельков',
  // Вкладки и значок свежести
  'Pulse': 'Пульс',
  'Flow': 'Поток',
  'Me': 'Я',
  'Queue': 'Очередь',
  'Alerts': 'Сигналы',
  'fresh': 'свежо',
  'aging': 'стареет',
  'stale': 'устарело',
  'unavailable': 'нет связи',
  'syncing': 'синхрон',
  'every number has a receipt': 'у каждого числа есть чек',

  // Пульс
  'Waiting for a finalized answer': 'Ждём подтверждённый ответ',
  'Reading the vault': 'Читаем хранилище',
  'Network unavailable': 'Сеть недоступна',
  'Last 24 hours': 'Сутки',
  'Last 7 days': '7 дней',
  'Last 30 days': '30 дней',
  'staked': 'в стейк',
  'asked out': 'на выход',
  'history covers {days}d': 'история за {days} дн.',
  'In cooldown': 'Остывает',
  '{count} positions waiting out the 48 hours': '{count} позиций ждут свои 48 часов',
  'Ready to exit': 'Готово к выходу',
  'Cooldown finished, not yet withdrawn': 'Остыло, но ещё не забрали',
  'When the queue matures': 'Когда созреет очередь',
  'ready': 'готово',

  // Очередь
  'Ready to withdraw': 'Можно забрать',
  '{amount} SKR is still cooling down across {count} positions': 'Ещё {amount} SKR остывает в {count} позициях',
  'Reading the queue': 'Читаем очередь',
  'Time to maturity': 'До созревания',
  'Exits in flight, soonest first': 'Выходы в пути, ближайшие сверху',
  '{count} shown': 'показано {count}',
  'Nothing is queued to leave right now.': 'Сейчас на выход никто не стоит.',

  // Поток
  'Live from the vault': 'Прямо из хранилища',
  'Reconnecting': 'Переподключаемся',
  'BUZZ ON': 'ВИБРО ВКЛ',
  'BUZZ OFF': 'ВИБРО ВЫКЛ',
  'SOUND ON': 'ЗВУК ВКЛ',
  'SOUND OFF': 'ЗВУК ВЫКЛ',
  'Biggest seen today': 'Крупнейшее за сутки',
  'Last big move': 'Последнее крупное',
  '{age} ago': '{age} назад',
  'slot {slot}': 'слот {slot}',
  'amount unavailable': 'сумма недоступна',
  'withdrew': 'забрал',
  'cancelled exit': 'отменил выход',
  'stake': 'стейк',
  'unstake': 'вывод',
  'withdraw': 'забрать',
  'Fold the older large moves': 'Свернуть прежние крупные',
  '1 more large move': 'ещё 1 крупное',
  '{count} more large moves': 'ещё {count} крупных',
  '{count} landed while you watched': '{count} пришло при тебе',
  'Watching the chain': 'Смотрим за цепочкой',
  'While you were away': 'Пока тебя не было',
  'One large move landed': 'Пришло 1 крупное движение',
  '{count} large moves landed': 'Пришло {count} крупных движений',
  ', the biggest {amount} SKR {verb}': ', крупнейшее — {amount} SKR {verb}',
  'ALL': 'ВСЁ',
  'only {amount} SKR and up': 'только от {amount} SKR',
  'everything, dust included': 'всё, вместе с мелочью',
  'Waiting for the next finalized event of this size.': 'Ждём следующее подтверждённое событие такого размера.',

  // Я — профиль и карточка
  'Leaving': 'Уходит',
  '{count} position(s) in cooldown': '{count} позиций остывает',
  'Ready now': 'Уже готово',
  'Next unlock': 'Ближайшая разблокировка',
  'Cooldown finished': 'Остывание закончилось',
  'Until this position is free': 'Пока позиция не освободится',
  'Nothing queued': 'Очереди нет',
  'Your weight in the vault': 'Твой вес в хранилище',
  'First stake {days} days ago, read from the oldest signature on your position account.': 'Первый стейк {days} дней назад, взято из самой старой подписи на твоём счёте позиции.',
  'Held at least {days} days. Your position has a long signature history, so the walk back is still going.': 'Держишь минимум {days} дней. У позиции длинная история подписей, обход ещё идёт.',
  'Reading the age of your position from the chain…': 'Читаем возраст твоей позиции из цепочки…',
  'Stake SKR': 'Застейкать SKR',
  'Drawing your card…': 'Рисуем карточку…',
  'Share your card': 'Поделиться карточкой',
  'Alerts armed': 'Оповещения поставлены',
  'Wake me at unlock': 'Разбудить при разблокировке',
  'Refresh': 'Обновить',
  'Disconnect': 'Отключить',
  'This address holds no SKR position right now.': 'На этом адресе сейчас нет позиции SKR.',
  'Connect the wallet that holds your stake, or paste any public address. Nothing is signed.': 'Подключи кошелёк со своим стейком или вставь любой публичный адрес. Ничего не подписывается.',
  'Connect Solana Mobile': 'Подключить Solana Mobile',
  'OR': 'ИЛИ',
  'Paste a Solana address': 'Вставь адрес Solana',
  'Look up': 'Найти',
  'WEIGHT': 'ВЕС',
  'POSITIONS': 'ПОЗИЦИЙ',
  'READ FROM': 'ЧИТАЛИ С',
  'Connect the wallet that holds your stake to fill this card in.': 'Подключи кошелёк со своим стейком, и карточка заполнится.',
  '1 unlock alert armed on this phone.': 'На этом телефоне поставлено 1 оповещение о разблокировке.',
  '{count} unlock alerts armed on this phone.': 'На этом телефоне поставлено {count} оповещений о разблокировке.',
  'Nothing left to wait for — the cooldown is already over.': 'Ждать нечего — остывание уже закончилось.',
  'Caption copied. Paste it next to the picture.': 'Подпись скопирована. Вставь её рядом с картинкой.',
  'This phone would not take the caption — type it yourself.': 'Телефон не принял подпись — набери её сам.',
  'Your SKR staker card': 'Твоя карточка стейкера SKR',
  'This phone has nothing to share with.': 'На этом телефоне нечем поделиться.',

  // Ошибки, которые человек действительно видит
  'The finalized snapshot is still warming up. Try again in a moment.': 'Подтверждённый снимок ещё готовится. Попробуй через минуту.',
  'This position could not be read': 'Не удалось прочитать эту позицию',
  'The wallet request was cancelled': 'Запрос к кошельку отменён',
  'The wallet did not return an account.': 'Кошелёк не вернул счёт.',
  'Alerts could not be scheduled': 'Не удалось поставить оповещения',
  'The card is not ready yet': 'Карточка ещё не готова',
  'The card could not be drawn': 'Не удалось нарисовать карточку',
  'the chain returned no signatures': 'цепочка не вернула подписей',
  'age lookup failed': 'не удалось узнать возраст',
  'SKR Eyes API returned {status}': 'API SKR Eyes ответил {status}',
  'The age service answered {status}': 'Служба возраста ответила {status}',

  // Экран оповещений
  'Notifications allowed': 'Уведомления разрешены',
  'Notifications off': 'Уведомления выключены',
  'Alerts are scheduled on the phone itself. Nothing about you leaves the device.': 'Оповещения ставит сам телефон. Ничего о тебе с устройства не уходит.',
  'Allow notifications and this app can wake you exactly when your cooldown ends.': 'Разреши уведомления, и приложение разбудит тебя ровно тогда, когда закончится остывание.',
  'Allow notifications': 'Разрешить уведомления',
  'Open settings': 'Открыть настройки',
  'This phone can now wake you.': 'Теперь телефон может тебя разбудить.',
  'Android will not ask again. Turn notifications on for SKR Eyes in the system settings.': 'Android больше не спросит. Включи уведомления для SKR Eyes в системных настройках.',
  'Android is holding notifications back for this app.': 'Android придерживает уведомления этого приложения.',
  'Android did not answer the permission request. Try again, or turn notifications on in the system settings.': 'Android не ответил на запрос разрешения. Попробуй ещё раз или включи уведомления в системных настройках.',
  'This phone would not open its settings screen.': 'Телефон не открыл свои настройки.',
  'Wake me at my unlock': 'Разбудить, когда разблокируется',
  'Connect your wallet on the Me screen and this switch becomes live.': 'Подключи кошелёк на вкладке «Я», и этот переключатель заработает.',
  'One hour before, and again the moment the cooldown ends. Scheduled by this phone from the exact on-chain time.': 'За час до и ещё раз в момент конца остывания. Ставит сам телефон по точному времени из цепочки.',
  'Nothing of yours is unlocking, so there is nothing to wake you for yet.': 'У тебя ничего не разблокируется, значит будить пока не за чем.',
  'Large moves while you were away': 'Крупные движения, пока тебя не было',
  'Anything above the threshold below is summed up at the top of Flow when you come back to it, and lands with a chime and a buzz while you are watching.': 'Всё, что выше порога ниже, собирается сверху вкладки «Поток», когда ты туда вернёшься, а пока ты смотришь — приходит со звуком и вибрацией.',
  "Waking the phone for someone else's large move while the app is closed needs a background check that Android schedules on its own terms. That is the next version — promising it here before it exists would be the same lie this screen just removed.": 'Будить телефон из-за чужого крупного движения при закрытом приложении можно только фоновой проверкой, а её Android назначает по своим правилам. Это следующая версия — пообещать здесь раньше, чем сделано, было бы ровно той ложью, которую этот экран только что убрал.',
  'What counts as large in Flow': 'Что считается крупным в «Потоке»',
  'Built-in thresholds, used by the chime and the buzz on the Flow screen, until the server publishes its own.': 'Встроенные пороги — по ним звук и вибрация на «Потоке», пока сервер не опубликует свои.',
  'These come from the server, move with real traffic, and drive the chime and the buzz on the Flow screen.': 'Эти приходят с сервера, двигаются вместе с реальным потоком и задают звук и вибрацию на «Потоке».',
  'Send a test notification': 'Отправить тестовое уведомление',
  'A test notification will arrive in a few seconds.': 'Тестовое уведомление придёт через несколько секунд.',
  'The test notification could not be scheduled': 'Не удалось поставить тестовое уведомление',
  '1 reminder set on this phone for your unlock.': 'На этом телефоне поставлено 1 напоминание о твоей разблокировке.',
  '{count} reminders set on this phone for your unlock.': 'На этом телефоне поставлено {count} напоминаний о твоей разблокировке.',
  'The reminders for your unlock were cancelled.': 'Напоминания о разблокировке отменены.',
  'The alert could not be changed.': 'Не удалось изменить оповещение.',
  'Language': 'Язык',
  'The app follows your phone until you choose here. The card you share stays in English, so it reads the same to everyone who sees it.': 'Пока ты не выбрал здесь, приложение идёт за языком телефона. Карточка, которой делишься, всегда на английском — чтобы её одинаково прочитал каждый, кто увидит.',

  // Сами уведомления
  'This wallet has no pending SKR unlock.': 'У этого кошелька нет SKR в ожидании разблокировки.',
  'SKR unlocks in 1 hour': 'SKR разблокируется через час',
  'Your pending SKR is approaching its withdrawable time.': 'Твои SKR подходят к моменту, когда их можно забрать.',
  'Your SKR is now withdrawable': 'Твои SKR теперь можно забрать',
  'Open SKR Eyes to verify the finalized position and evidence.': 'Открой SKR Eyes, чтобы проверить подтверждённую позицию и доказательства.',
  'SKR Eyes alerts are ready': 'Оповещения SKR Eyes готовы',
  'Test complete. Real unlock alerts will use finalized on-chain time.': 'Проверка прошла. Настоящие оповещения пойдут по подтверждённому времени из цепочки.',

  // Окно стейка
  'Add to your position': 'Добавить к позиции',
  'Amount per transaction': 'Сумма одной транзакции',
  'SKR has six decimal places. Shorten the amount — the extra digits cannot be staked.': 'У SKR шесть знаков после запятой. Укороти сумму — лишние цифры застейкать нельзя.',
  'A single transaction cannot stake less than 1 SKR.': 'Одной транзакцией нельзя застейкать меньше 1 SKR.',
  'This is what one transaction stakes. The total is this amount times the count below.': 'Столько стейкает одна транзакция. Итог — эта сумма, умноженная на число ниже.',
  'How many transactions': 'Сколько транзакций',
  'One transaction, one wallet approval.': 'Одна транзакция, одно подтверждение в кошельке.',
  '{count} identical transactions from one approval, sent one after another. Each one is a separate on-chain stake.': '{count} одинаковых транзакций с одного подтверждения, уходят одна за другой. Каждая — отдельный стейк в цепочке.',
  'This needs {needed} SKR and you hold {held}. ': 'Нужно {needed} SKR, а у тебя {held}. ',
  'At this amount you can send 1 part.': 'На эту сумму выйдет 1 часть.',
  'At this amount you can send {count} parts.': 'На эту сумму выйдет частей: {count}.',
  'Lower the amount to stake what you have.': 'Уменьши сумму, чтобы застейкать то, что есть.',
  'You hold {held} SKR.': 'У тебя {held} SKR.',
  'Before you sign': 'Перед подписью',
  'sent as': 'уйдёт как',
  'you stake in total': 'стейкаешь всего',
  'position account rent': 'рента счёта позиции',
  'already paid': 'уже оплачена',
  '{sol} SOL, once': '{sol} SOL, один раз',
  'Your position account already exists, so only the network fee applies — a few thousand lamports per transaction.': 'Счёт позиции у тебя уже есть, поэтому платишь только комиссию сети — несколько тысяч лампортов за транзакцию.',
  'The first stake creates your position account and its rent stays with the account. Network fees are a few thousand lamports per transaction.': 'Первый стейк создаёт счёт позиции, и рента остаётся на этом счёте. Комиссия сети — несколько тысяч лампортов за транзакцию.',
  'Working…': 'Работаем…',
  'At least 1 SKR per transaction': 'Минимум 1 SKR на транзакцию',
  'Sign and stake {amount} SKR': 'Подписать и застейкать {amount} SKR',
  'Sign and stake': 'Подписать и застейкать',
  'All parts landed': 'Все части прошли',
  'Stopped': 'Остановлено',
  'Approve in your wallet': 'Подтверди в кошельке',
  'Preparing transactions': 'Готовим транзакции',
  'A run from before': 'Запуск с прошлого раза',
  'Landing on chain': 'Ложится в цепочку',
  'pending': 'ждёт',
  'sending': 'отправка',
  'sent': 'отправлено',
  'confirmed': 'подтверждено',
  'unknown': 'неизвестно',
  'failed': 'не прошло',
  'We do not know yet': 'Мы пока не знаем',
  'What happened': 'Что случилось',
  'Ask the chain again': 'Спросить цепочку ещё раз',
  'Stake again': 'Застейкать ещё',
  'Discard and start over': 'Сбросить и начать заново',
  'Start over': 'Начать заново',
  'Close': 'Закрыть',
};
