// Türkçe. Anahtar, koddaki İngilizce cümlenin kendisidir.
//
// Bu tablonun kuralları: sade dil, pazarlama sözü yok, ünlem yok, sen dili.
// Simgeler (SKR, SOL), cüzdanın adı (Seed Vault) ve uygulamanın adı olduğu gibi
// kalır; Latin harfli adlara gelen ekler kesme işaretiyle ayrılır (SKR'yi).
// Sayılar zaten biçimlenmiş gelir: süslü parantezler yer değiştirir,
// içeriği değişmez.

export const tr: Record<string, string> = {
  'All': 'Tümü',
  'Stakes': 'Stake',
  'Exits': 'Çıkış',
  'Withdrew': 'Çekim',
  'Vault': 'Kasa',
  'over the last 7 days': 'son 7 günde',
  'over the last 30 days': 'son 30 günde',
  '{percent}% of all SKR is staked': 'tüm SKR\'nin %{percent} kadarı stake edilmiş',
  'over the last 24 hours': 'son 24 saatte',
  'net': 'net',
  'wallets': 'cüzdan',
  // Sekmeler ve tazelik rozeti
  'Flow': 'Akış',
  'Me': 'Ben',
  'Queue': 'Sıra',
  'Alerts': 'Uyarılar',
  'fresh': 'taze',
  'aging': 'eskiyor',
  'stale': 'bayat',
  'unavailable': 'yok',
  'syncing': 'eşitleniyor',
  'every number has a receipt': 'her sayının bir makbuzu var',

  // Nabız
  'Waiting for a finalized answer': 'Kesinleşmiş bir yanıt bekleniyor',
  'Reading the vault': 'Kasa okunuyor',
  'Network unavailable': 'Ağa ulaşılamıyor',
  'Last 24 hours': 'Son 24 saat',
  'Last 7 days': 'Son 7 gün',
  'Last 30 days': 'Son 30 gün',
  '24h': '24s',
  'staked': 'stake edildi',
  'asked out': 'çıkış istedi',
  'in': 'girdi',
  'staked minus requested out': 'stake edilen eksi çıkış istenen',
  'history covers {days}d': '{days} günlük geçmiş',
  'In cooldown': 'Bekleme süresinde',
  '{count} positions waiting out the 48 hours': '{count} pozisyon 48 saatini dolduruyor',
  'Ready to exit': 'Çıkışa hazır',
  'Cooldown finished, not yet withdrawn': 'Bekleme bitti, henüz çekilmedi',
  'When the queue matures': 'Sıranın süresi ne zaman doluyor',
  'ready': 'hazır',
  'ready to withdraw': 'çekilmeye hazır',
  'cooling down': 'beklemede',

  // Kasa sahnesi
  'Motion': 'Hareket',
  'The vault stands still.': 'Kasa kıpırdamaz.',
  'One gentle frame a second.': 'Saniyede tek, yumuşak bir kare.',
  'Live while you watch. Calm after 90 seconds without a touch.': 'Sen bakarken canlı. 90 saniye dokunulmazsa sakin.',
  'Receipt': 'Makbuz',
  'Open on Solscan': 'Solscan\'de aç',

  // Sıra
  'Exits in flight, soonest first': 'Yoldaki çıkışlar, en yakını başta',
  '{count} shown': '{count} tanesi görünüyor',
  'Show all {count}': 'Hepsini göster ({count})',
  'Show fewer': 'Daha az göster',
  'Nothing is queued to leave right now.': 'Şu anda çıkış sırasında hiçbir şey yok.',

  // Akış
  'Live from the vault': 'Kasadan canlı',
  'Reconnecting': 'Yeniden bağlanıyor',
  'BUZZ ON': 'TİTREŞİM AÇIK',
  'BUZZ OFF': 'TİTREŞİM KAPALI',
  'SOUND ON': 'SES AÇIK',
  'SOUND OFF': 'SES KAPALI',
  'Biggest seen today': 'Bugünün en büyüğü',
  'Biggest stake today': 'Bugünün en büyük stake\'i',
  'Biggest exit today': 'Bugünün en büyük çıkışı',
  'Biggest withdrawal today': 'Bugünün en büyük çekimi',
  'Last big move': 'Son büyük hareket',
  '{age} ago': '{age} önce',
  'slot {slot}': 'slot {slot}',
  'amount unavailable': 'tutar okunamadı',
  'withdrew': 'çekti',
  'cancelled exit': 'çıkışı iptal etti',
  'stake': 'stake',
  'unstake': 'çıkış',
  'withdraw': 'çekim',
  'Fold the older large moves': 'Eski büyük hareketleri daralt',
  '1 more large move': '1 büyük hareket daha',
  '{count} more large moves': '{count} büyük hareket daha',
  '{count} landed while you watched': 'sen bakarken {count} tanesi geldi',
  'Watching the chain': 'Zincir izleniyor',
  'ALL': 'HEPSİ',
  'only {amount} SKR and up': 'sadece {amount} SKR ve üstü',
  'everything, dust included': 'hepsi, kırıntılar dahil',
  'Waiting for the next finalized event of this size.': 'Bu büyüklükte kesinleşmiş bir sonraki işlem bekleniyor.',

  // Ben: profil ve kart
  'Leaving': 'Çıkıyor',
  '1 position in cooldown': '1 pozisyon beklemede',
  '{count} positions in cooldown': '{count} pozisyon beklemede',
  'Ready now': 'Şimdi hazır',
  'Next unlock': 'Sıradaki açılış',
  'Cooldown finished': 'Bekleme bitti',
  'Until this position is free': 'Bu pozisyon serbest kalana kadar',
  'Nothing queued': 'Sırada bir şey yok',
  'Your weight in the vault': 'Kasadaki ağırlığın',
  'First stake {days} days ago, read from the oldest signature on your position account.': 'İlk stake {days} gün önce; pozisyon hesabındaki en eski imzadan okundu.',
  'Held at least {days} days. Your position has a long signature history, so the walk back is still going.': 'En az {days} gündür duruyor. Pozisyonunun imza geçmişi uzun, geriye doğru tarama sürüyor.',
  'Reading the age of your position from the chain…': 'Pozisyonunun yaşı zincirden okunuyor…',
  'Stake SKR': 'SKR stake et',
  'Drawing your card…': 'Kartın çiziliyor…',
  'Share your card': 'Kartını paylaş',
  'Alerts armed': 'Uyarılar kuruldu',
  'Wake me at unlock': 'Açılışta beni uyandır',
  'Refresh': 'Yenile',
  'Disconnect': 'Bağlantıyı kes',
  'This address holds no SKR position right now.': 'Bu adreste şu anda SKR pozisyonu yok.',
  'This wallet holds no SKR position yet. The first stake opens one; the position account costs a little rent once.': 'Bu cüzdanın henüz SKR pozisyonu yok. İlk stake bir tane açar; pozisyon hesabı bir kereliğine küçük bir kira ister.',
  'This position is being looked at, not signed for. Connect the wallet that holds it to stake from it.': 'Bu pozisyona yalnızca bakılıyor, onun adına imza atılmıyor. Buradan stake etmek için onu tutan cüzdanı bağla.',
  'Connect the wallet that holds your stake, or paste any public address. Nothing is signed.': 'Stake\'ini tutan cüzdanı bağla ya da herhangi bir açık adresi yapıştır. Hiçbir şey imzalanmaz.',
  'Connect Solana Mobile': 'Solana Mobile\'ı bağla',
  'OR': 'VEYA',
  'Paste a Solana address': 'Bir Solana adresi yapıştır',
  'Look up': 'Sorgula',
  'WEIGHT': 'AĞIRLIK',
  'POSITIONS': 'POZİSYON',
  'READ FROM': 'OKUNDUĞU YER',
  '1 unlock alert armed on this phone.': 'Bu telefonda 1 açılış uyarısı kuruldu.',
  '{count} unlock alerts armed on this phone.': 'Bu telefonda {count} açılış uyarısı kuruldu.',
  'Nothing left to wait for — the cooldown is already over.': 'Beklenecek bir şey kalmadı, bekleme süresi çoktan bitti.',
  'Caption copied. Paste it next to the picture.': 'Yazı kopyalandı. Resmin yanına yapıştır.',
  'This phone would not take the caption — type it yourself.': 'Bu telefon yazıyı almadı, kendin yaz.',
  'Your SKR staker card': 'SKR stake kartın',
  'This phone has nothing to share with.': 'Bu telefonda paylaşacak bir uygulama yok.',

  // Kart gizliliği
  'Hide my name on the card': 'Kartta adımı gizle',
  'The eye in the ring closes and the card says A Seeker.': 'Halkadaki göz kapanır ve kartta "Bir Seeker sahibi" yazar.',
  'Hide my amount on the card': 'Kartta tutarımı gizle',
  'Days, since and one-of stay; the position line goes.': 'Gün sayısı, başlangıç tarihi ve "kaç pozisyondan biri" kalır; pozisyon satırı gider.',
  'An exact amount next to a start date is close to a fingerprint. Your choice, said plainly.': 'Başlangıç tarihinin yanında tam bir tutar, neredeyse parmak izi gibidir. Seçim senin, açıkça söylüyoruz.',

  // Günlük on altı
  'Sixteen': 'On altı',
  'The daily sixteen': 'Günlük on altı',
  '16 parts of 1 SKR, one approval. A small daily habit that keeps your position moving.': '1 SKR\'nin 16 parçası, tek onay. Pozisyonunu hareketli tutan küçük bir günlük alışkanlık.',

  // Bahşiş penceresi
  'Support SKR Eyes': 'SKR Eyes\'a destek ol',
  'Send a tip': 'Bahşiş gönder',
  'A tip in SKR': 'SKR ile bahşiş',
  'How much': 'Ne kadar',
  'Any amount you like. Goes to {name}, the wallet behind this app.': 'Dilediğin kadar. {name} adresine, yani bu uygulamanın arkasındaki cüzdana gider.',
  'Send {amount} SKR to {name}': '{name} adresine {amount} SKR gönder',
  '{amount} SKR on its way to {name}': '{amount} SKR {name} adresine yolda',
  'Thank you': 'Teşekkürler',
  'Done': 'Tamam',
  'Landing on chain…': 'Zincire yazılıyor…',
  'Your wallet signs and sends it. The app only fetches a blockhash before and reads the status after.': 'İmzalayan ve gönderen cüzdanındır. Uygulama yalnızca öncesinde bir blockhash alır, sonrasında durumu okur.',
  'A tip changes nothing about your position and nothing about any airdrop. It is a thank you, not a fee.': 'Bahşiş pozisyonunda da herhangi bir airdrop\'ta da hiçbir şeyi değiştirmez. Bu bir teşekkür, ücret değil.',
  'Free and open source, built by one Seeker. Tips in SKR go to kosa.skr and are staked right away, all of them.': 'Ücretsiz ve açık kaynak, tek bir Seeker sahibinin elinden çıktı. SKR bahşişleri kosa.skr\'ye gider ve hemen stake edilir, hepsi.',
  'This app is free, open source, and built by one Seeker. If it saved you a moment, a tip is welcome. Every SKR that arrives is staked right away, all of it.': 'Bu uygulama ücretsiz, açık kaynak ve tek bir Seeker sahibinin işi. Sana bir an kazandırdıysa bahşişe açığız. Gelen her SKR hemen stake edilir, tamamı.',
  'This is {name} itself. A tip to your own wallet moves nothing; try from another wallet.': 'Bu adres zaten {name}. Kendi cüzdanına bahşiş hiçbir şey taşımaz; başka bir cüzdandan dene.',
  'The chain rejected the transfer.': 'Zincir transferi reddetti.',
  'The wallet declined. Nothing was sent.': 'Cüzdan reddetti. Hiçbir şey gönderilmedi.',
  'The wallet returned no signature.': 'Cüzdan imza döndürmedi.',
  'SKR has six decimal places. Shorten the amount.': 'SKR\'nin altı ondalık basamağı var. Tutarı kısalt.',

  // Kişinin gerçekten gördüğü hatalar
  'The finalized snapshot is still warming up. Try again in a moment.': 'Kesinleşmiş anlık görüntü hâlâ hazırlanıyor. Birazdan yeniden dene.',
  'This position could not be read': 'Bu pozisyon okunamadı',
  'The wallet request was cancelled': 'Cüzdan isteği iptal edildi',
  'The wallet did not return an account.': 'Cüzdan bir hesap döndürmedi.',
  'The wallet that answered is not the one on screen. Connect the wallet that holds this position, then stake. Nothing was sent.': 'Yanıt veren cüzdan ekrandaki cüzdan değil. Bu pozisyonu tutan cüzdanı bağla, sonra stake et. Hiçbir şey gönderilmedi.',
  'The app was closed while the wallet had this stake. Check your position before staking again, then clear this.': 'Cüzdan bu stake\'i işlerken uygulama kapandı. Yeniden stake etmeden önce pozisyonunu kontrol et, sonra bunu temizle.',
  'Alerts could not be scheduled': 'Uyarılar kurulamadı',
  'The card is not ready yet': 'Kart henüz hazır değil',
  'The card could not be drawn': 'Kart çizilemedi',
  'the chain returned no signatures': 'zincir hiç imza döndürmedi',
  'age lookup failed': 'yaş sorgusu başarısız oldu',
  'SKR Eyes API returned {status}': 'SKR Eyes API {status} döndürdü',
  'The age service answered {status}': 'Yaş servisi {status} yanıtladı',

  // Uyarılar ekranı
  'Notifications allowed': 'Bildirimlere izin verildi',
  'Notifications off': 'Bildirimler kapalı',
  'Alerts are scheduled on the phone itself. Nothing about you leaves the device.': 'Uyarıları telefonun kendisi kurar. Sana dair hiçbir şey cihazdan çıkmaz.',
  'Allow notifications and this app can wake you exactly when your cooldown ends.': 'Bildirimlere izin ver, uygulama bekleme süren biter bitmez seni uyandırsın.',
  'Allow notifications': 'Bildirimlere izin ver',
  'Open settings': 'Ayarları aç',
  'This phone can now wake you.': 'Bu telefon artık seni uyandırabilir.',
  'Android will not ask again. Turn notifications on for SKR Eyes in the system settings.': 'Android bir daha sormayacak. SKR Eyes için bildirimleri sistem ayarlarından aç.',
  'Android is holding notifications back for this app.': 'Android bu uygulamanın bildirimlerini engelliyor.',
  'Android did not answer the permission request. Try again, or turn notifications on in the system settings.': 'Android izin isteğine yanıt vermedi. Yeniden dene ya da bildirimleri sistem ayarlarından aç.',
  'This phone would not open its settings screen.': 'Bu telefon ayarlar ekranını açmadı.',
  'Wake me at my unlock': 'Açılışımda beni uyandır',
  'Connect your wallet on the Me screen and this switch becomes live.': 'Cüzdanını Ben sekmesinde bağla, bu düğme etkinleşsin.',
  'One hour before, and again the moment the cooldown ends. Scheduled by this phone from the exact on-chain time.': 'Bir saat önce, bir de bekleme süresinin bittiği anda. Zincirdeki tam saate göre bu telefon kurar.',
  'Nothing of yours is unlocking, so there is nothing to wake you for yet.': 'Açılan bir şeyin yok, yani şimdilik seni uyandıracak bir sebep de yok.',
  'Large moves, heard and felt': 'Büyük hareketler, duyulur ve hissedilir',
  'A stake of 10K SKR or more rings like a glass coin, a stake of 100K rings the vault bell, an exit of 100K lands with a low boom. On every screen while the app is open, each with a short buzz.': '10K SKR ve üstü bir stake cam bir para gibi çınlar, 100K\'lık bir stake kasa çanını çalar, 100K\'lık bir çıkış derin bir gümbürtüyle iner. Uygulama açıkken her ekranda, her biri kısa bir titreşimle.',
  'Other people\'s moves do not wake the phone while the app is closed. Only your own unlock does.': 'Uygulama kapalıyken başkalarının hareketleri telefonu uyandırmaz. Yalnızca senin açılışın uyandırır.',
  'What counts as large': 'Ne büyük sayılır',
  'Built-in thresholds behind the bell and the boom, until the server publishes its own.': 'Sunucu kendi eşiklerini yayınlayana kadar çanın ve gümbürtünün arkasındaki gömülü eşikler.',
  'These come from the server, move with real traffic, and drive the bell and the boom.': 'Bunlar sunucudan gelir, gerçek trafikle birlikte değişir; çanı ve gümbürtüyü bunlar yönetir.',
  'Send a test notification': 'Deneme bildirimi gönder',
  'A test notification will arrive in a few seconds.': 'Deneme bildirimi birkaç saniye içinde gelecek.',
  'The test notification could not be scheduled': 'Deneme bildirimi kurulamadı',
  '1 reminder set on this phone for your unlock.': 'Açılışın için bu telefona 1 hatırlatma kuruldu.',
  '{count} reminders set on this phone for your unlock.': 'Açılışın için bu telefona {count} hatırlatma kuruldu.',
  'The reminders for your unlock were cancelled.': 'Açılış hatırlatmaların iptal edildi.',
  'The alert could not be changed.': 'Uyarı değiştirilemedi.',
  'Language': 'Dil',
  'The app follows your phone until you choose here. The card you share stays in English, so it reads the same to everyone who sees it.': 'Buradan seçim yapana kadar uygulama telefonun dilini izler. Paylaştığın kart İngilizce kalır; böylece onu gören herkes aynı şeyi okur.',

  // Bildirimlerin kendisi
  'This wallet has no pending SKR unlock.': 'Bu cüzdanda bekleyen SKR açılışı yok.',
  'SKR unlocks in 1 hour': 'SKR 1 saat sonra açılıyor',
  'Your pending SKR is approaching its withdrawable time.': 'Bekleyen SKR\'lerin çekilebilir olacağı saate yaklaşıyor.',
  'Your SKR is now withdrawable': 'SKR\'lerini artık çekebilirsin',
  'Open SKR Eyes to verify the finalized position and evidence.': 'Kesinleşmiş pozisyonu ve kanıtı görmek için SKR Eyes\'ı aç.',
  'SKR Eyes alerts are ready': 'SKR Eyes uyarıları hazır',
  'Test complete. Real unlock alerts will use finalized on-chain time.': 'Deneme tamam. Gerçek uyarılar zincirdeki kesinleşmiş saati kullanacak.',

  // Stake penceresi
  'Add to your position': 'Pozisyonuna ekle',
  'Amount per transaction': 'İşlem başına tutar',
  'SKR has six decimal places. Shorten the amount — the extra digits cannot be staked.': 'SKR\'nin altı ondalık basamağı var. Tutarı kısalt, fazla haneler stake edilemez.',
  'A single transaction cannot stake less than 1 SKR.': 'Tek bir işlem 1 SKR\'den azını stake edemez.',
  'This is what one transaction stakes. The total is this amount times the count below.': 'Bir işlemin stake ettiği miktar budur. Toplam, bu tutarın aşağıdaki sayıyla çarpımıdır.',
  'How many transactions': 'Kaç işlem',
  'One transaction, one wallet approval.': 'Tek işlem, cüzdanda tek onay.',
  '{count} identical transactions from one approval, sent one after another. Each one is a separate on-chain stake.': 'Tek onayla birbirinin aynı {count} işlem, arka arkaya gönderilir. Her biri zincirde ayrı bir stake\'tir.',
  'This needs {needed} SKR and you hold {held}. ': 'Bunun için {needed} SKR gerekiyor, sende {held} var. ',
  'At this amount you can send 1 part.': 'Bu tutarla 1 parça gönderebilirsin.',
  'At this amount you can send {count} parts.': 'Bu tutarla {count} parça gönderebilirsin.',
  'Lower the amount to stake what you have.': 'Elindekini stake etmek için tutarı düşür.',
  'You hold {held} SKR.': 'Sende {held} SKR var.',
  'Before you sign': 'İmzalamadan önce',
  'sent as': 'gönderim biçimi',
  'you stake in total': 'toplam stake',
  'position account rent': 'pozisyon hesabı kirası',
  'already paid': 'zaten ödendi',
  '{sol} SOL, once': '{sol} SOL, bir kez',
  'Your position account already exists, so only the network fee applies — a few thousand lamports per transaction.': 'Pozisyon hesabın zaten var, bu yüzden sadece ağ ücreti işler: işlem başına birkaç bin lamport.',
  'The first stake creates your position account and its rent stays with the account. Network fees are a few thousand lamports per transaction.': 'İlk stake pozisyon hesabını açar ve kirası o hesapta kalır. Ağ ücreti işlem başına birkaç bin lamporttur.',
  'Working…': 'Çalışıyor…',
  'At least 1 SKR per transaction': 'İşlem başına en az 1 SKR',
  'Sign and stake {amount} SKR': 'İmzala ve {amount} SKR stake et',
  'Sign and stake': 'İmzala ve stake et',
  'All parts landed': 'Bütün parçalar geçti',
  'Stopped': 'Durduruldu',
  'Approve in your wallet': 'Cüzdanında onayla',
  'Preparing transactions': 'İşlemler hazırlanıyor',
  'A run from before': 'Önceden kalan bir gönderim',
  'Landing on chain': 'Zincire yazılıyor',
  'pending': 'bekliyor',
  'sending': 'gönderiliyor',
  'sent': 'gönderildi',
  'confirmed': 'onaylandı',
  'unknown': 'bilinmiyor',
  'failed': 'başarısız',
  'We do not know yet': 'Henüz bilmiyoruz',
  'What happened': 'Ne oldu',
  'Ask the chain again': 'Zincire yeniden sor',
  'Stake again': 'Yeniden stake et',
  'Discard and start over': 'Vazgeç ve baştan başla',
  'Start over': 'Baştan başla',
  'Close': 'Kapat',
};
