// Tiếng Việt. Khoá tra cứu chính là câu tiếng Anh nằm trong mã nguồn.
//
// Quy tắc của bảng này: nói giản dị, không dùng từ quảng cáo, không dùng dấu
// chấm than, xưng hô "bạn". Mã token (SKR, SOL), tên ví (Seed Vault) và tên ứng
// dụng giữ nguyên. Các con số đã được định dạng sẵn: dấu ngoặc nhọn có thể đổi
// chỗ nhưng không đổi tên.

export const vi: Record<string, string> = {
  // Thẻ và huy hiệu độ mới
  'Pulse': 'Nhịp',
  'Flow': 'Dòng',
  'Me': 'Tôi',
  'Queue': 'Hàng chờ',
  'Alerts': 'Nhắc',
  'fresh': 'mới',
  'aging': 'đang cũ',
  'stale': 'quá cũ',
  'unavailable': 'không có',
  'syncing': 'đang đồng bộ',
  'every number has a receipt': 'mỗi con số đều có bằng chứng',

  // Nhịp
  'Staked of total supply': 'Đã stake trên tổng cung',
  '{percent}% of the {supply} SKR total supply · {positions} positions': '{percent}% của {supply} SKR tổng cung · {positions} vị thế',
  'Waiting for a finalized answer': 'Đang chờ câu trả lời đã chốt',
  'Reading the vault': 'Đang đọc kho',
  'Network unavailable': 'Không có mạng',
  'Last 24 hours': '24 giờ qua',
  'Last 7 days': '7 ngày qua',
  'Last 30 days': '30 ngày qua',
  '{amount} staked': 'stake {amount}',
  '{amount} asked out': 'xin rút {amount}',
  'staked': 'đã stake',
  'asked out': 'xin rút',
  '{count} wallets': '{count} ví',
  'one bar per hour': 'mỗi giờ một cột',
  '{range} as one total · daily bars need a server pass': '{range} gộp thành một cột · cột theo ngày cần máy chủ tính',
  '{sign}{amount} net': 'ròng {sign}{amount}',
  'history covers {days}d': 'lịch sử {days} ngày',
  'In cooldown': 'Đang chờ nguội',
  '{count} positions waiting out the 48 hours': '{count} vị thế đang chờ hết 48 giờ',
  'Ready to exit': 'Sẵn sàng rời',
  'Cooldown finished, not yet withdrawn': 'Đã nguội xong, chưa rút',
  'When the queue matures': 'Khi nào hàng chờ tới hạn',
  'ready': 'sẵn sàng',

  // Hàng chờ
  'Ready to withdraw': 'Sẵn sàng rút',
  '{amount} SKR is still cooling down across {count} positions': 'Còn {amount} SKR đang nguội trong {count} vị thế',
  'Reading the queue': 'Đang đọc hàng chờ',
  'Time to maturity': 'Còn bao lâu tới hạn',
  'Exits in flight, soonest first': 'Các lệnh rời đang chạy, gần nhất lên trước',
  '{count} shown': 'hiện {count}',
  'Nothing is queued to leave right now.': 'Hiện không có gì đang xếp hàng để rời đi.',

  // Dòng
  'Live from the vault': 'Trực tiếp từ kho',
  'Reconnecting': 'Đang kết nối lại',
  'BUZZ ON': 'RUNG BẬT',
  'BUZZ OFF': 'RUNG TẮT',
  'SOUND ON': 'ÂM BẬT',
  'SOUND OFF': 'ÂM TẮT',
  'Biggest seen today': 'Lớn nhất hôm nay',
  'Last big move': 'Lần biến động lớn gần nhất',
  '{age} ago': '{age} trước',
  'slot {slot}': 'slot {slot}',
  'amount unavailable': 'không đọc được số tiền',
  'withdrew': 'đã rút',
  'cancelled exit': 'huỷ rời',
  'stake': 'stake',
  'unstake': 'rời',
  'withdraw': 'rút',
  'Fold the older large moves': 'Thu gọn các biến động lớn cũ hơn',
  '1 more large move': 'thêm 1 biến động lớn',
  '{count} more large moves': 'thêm {count} biến động lớn',
  '{count} landed while you watched': '{count} giao dịch tới trong lúc bạn xem',
  'Watching the chain': 'Đang theo dõi chuỗi',
  'While you were away': 'Trong lúc bạn vắng mặt',
  'One large move landed': 'Có 1 biến động lớn đã tới',
  '{count} large moves landed': 'Có {count} biến động lớn đã tới',
  ', the biggest {amount} SKR {verb}': ', lớn nhất là {amount} SKR {verb}',
  'ALL': 'TẤT CẢ',
  'only {amount} SKR and up': 'chỉ từ {amount} SKR trở lên',
  'everything, dust included': 'tất cả, kể cả những khoản lẻ',
  'Waiting for the next finalized event of this size.': 'Đang chờ giao dịch đã chốt tiếp theo ở mức này.',

  // Tôi — hồ sơ và thẻ
  'Leaving': 'Đang rời',
  '{count} position(s) in cooldown': '{count} vị thế đang nguội',
  'Ready now': 'Sẵn sàng ngay',
  'Next unlock': 'Lần mở khoá tới',
  'Cooldown finished': 'Đã nguội xong',
  'Until this position is free': 'Cho tới khi vị thế này được giải phóng',
  'Nothing queued': 'Không có gì trong hàng chờ',
  'Your weight in the vault': 'Tỷ trọng của bạn trong kho',
  'First stake {days} days ago, read from the oldest signature on your position account.': 'Lần stake đầu cách đây {days} ngày, đọc từ chữ ký cũ nhất trên tài khoản vị thế của bạn.',
  'Held at least {days} days. Your position has a long signature history, so the walk back is still going.': 'Ít nhất {days} ngày. Vị thế của bạn có lịch sử chữ ký dài nên việc lần ngược vẫn đang chạy.',
  'Reading the age of your position from the chain…': 'Đang đọc tuổi vị thế của bạn từ chuỗi…',
  'Stake SKR': 'Stake SKR',
  'Drawing your card…': 'Đang vẽ thẻ của bạn…',
  'Share your card': 'Chia sẻ thẻ của bạn',
  'Alerts armed': 'Đã đặt nhắc',
  'Wake me at unlock': 'Đánh thức khi mở khoá',
  'Refresh': 'Làm mới',
  'Disconnect': 'Ngắt kết nối',
  'This address holds no SKR position right now.': 'Địa chỉ này hiện không có vị thế SKR nào.',
  'Connect the wallet that holds your stake, or paste any public address. Nothing is signed.': 'Kết nối ví đang giữ phần stake của bạn, hoặc dán bất kỳ địa chỉ công khai nào. Không ký gì cả.',
  'Connect Solana Mobile': 'Kết nối Solana Mobile',
  'OR': 'HOẶC',
  'Paste a Solana address': 'Dán một địa chỉ Solana',
  'Look up': 'Tra cứu',
  'WEIGHT': 'TỶ TRỌNG',
  'POSITIONS': 'VỊ THẾ',
  'READ FROM': 'ĐỌC TỪ',
  'Connect the wallet that holds your stake to fill this card in.': 'Kết nối ví đang giữ phần stake của bạn để thẻ này được điền.',
  '1 unlock alert armed on this phone.': 'Đã đặt 1 nhắc mở khoá trên máy này.',
  '{count} unlock alerts armed on this phone.': 'Đã đặt {count} nhắc mở khoá trên máy này.',
  'Nothing left to wait for — the cooldown is already over.': 'Không còn gì để chờ, thời gian nguội đã hết.',
  'Caption copied. Paste it next to the picture.': 'Đã chép phần chữ. Dán nó cạnh ảnh.',
  'This phone would not take the caption — type it yourself.': 'Máy này không nhận phần chữ, bạn tự gõ nhé.',
  'Your SKR staker card': 'Thẻ staker SKR của bạn',
  'This phone has nothing to share with.': 'Máy này không có ứng dụng nào để chia sẻ.',

  // Những lỗi người dùng thật sự nhìn thấy
  'The finalized snapshot is still warming up. Try again in a moment.': 'Bản chốt vẫn đang được chuẩn bị. Thử lại sau giây lát.',
  'This position could not be read': 'Không đọc được vị thế này',
  'The wallet request was cancelled': 'Yêu cầu gửi tới ví đã bị huỷ',
  'The wallet did not return an account.': 'Ví không trả về tài khoản nào.',
  'Alerts could not be scheduled': 'Không đặt được nhắc',
  'The card is not ready yet': 'Thẻ chưa sẵn sàng',
  'The card could not be drawn': 'Không vẽ được thẻ',
  'the chain returned no signatures': 'chuỗi không trả về chữ ký nào',
  'age lookup failed': 'tra cứu tuổi thất bại',
  'SKR Eyes API returned {status}': 'API của SKR Eyes trả về {status}',
  'The age service answered {status}': 'Dịch vụ tuổi trả lời {status}',

  // Màn hình nhắc
  'Notifications allowed': 'Đã cho phép thông báo',
  'Notifications off': 'Thông báo đang tắt',
  'Alerts are scheduled on the phone itself. Nothing about you leaves the device.': 'Nhắc do chính điện thoại đặt. Không có thông tin nào của bạn rời khỏi máy.',
  'Allow notifications and this app can wake you exactly when your cooldown ends.': 'Cho phép thông báo để ứng dụng đánh thức bạn đúng lúc thời gian nguội kết thúc.',
  'Allow notifications': 'Cho phép thông báo',
  'Open settings': 'Mở cài đặt',
  'This phone can now wake you.': 'Giờ máy này có thể đánh thức bạn.',
  'Android will not ask again. Turn notifications on for SKR Eyes in the system settings.': 'Android sẽ không hỏi lại. Hãy bật thông báo cho SKR Eyes trong cài đặt hệ thống.',
  'Android is holding notifications back for this app.': 'Android đang chặn thông báo của ứng dụng này.',
  'Android did not answer the permission request. Try again, or turn notifications on in the system settings.': 'Android không trả lời yêu cầu quyền. Thử lại, hoặc bật thông báo trong cài đặt hệ thống.',
  'This phone would not open its settings screen.': 'Máy này không mở được màn hình cài đặt.',
  'Wake me at my unlock': 'Đánh thức tôi khi tới lúc mở khoá',
  'Connect your wallet on the Me screen and this switch becomes live.': 'Kết nối ví ở thẻ Tôi thì công tắc này mới hoạt động.',
  'One hour before, and again the moment the cooldown ends. Scheduled by this phone from the exact on-chain time.': 'Một giờ trước, và một lần nữa đúng lúc thời gian nguội kết thúc. Do chính máy này đặt theo giờ chính xác trên chuỗi.',
  'Nothing of yours is unlocking, so there is nothing to wake you for yet.': 'Bạn không có gì đang mở khoá, nên chưa có lý do để đánh thức bạn.',
  'Large moves while you were away': 'Biến động lớn trong lúc bạn vắng mặt',
  'Anything above the threshold below is summed up at the top of Flow when you come back to it, and lands with a chime and a buzz while you are watching.': 'Mọi thứ vượt ngưỡng bên dưới sẽ được gộp lại ở đầu thẻ Dòng khi bạn quay lại, còn lúc bạn đang xem thì nó tới kèm tiếng chuông và rung.',
  "Waking the phone for someone else's large move while the app is closed needs a background check that Android schedules on its own terms. That is the next version — promising it here before it exists would be the same lie this screen just removed.": 'Muốn đánh thức máy vì biến động lớn của người khác khi ứng dụng đã đóng thì cần một lượt kiểm tra nền, mà Android tự quyết định lịch chạy. Đó là việc của phiên bản sau: hứa ở đây trước khi làm được thì đúng là lời nói dối mà màn hình này vừa gỡ bỏ.',
  'What counts as large in Flow': 'Thế nào là lớn trong thẻ Dòng',
  'Built-in thresholds, used by the chime and the buzz on the Flow screen, until the server publishes its own.': 'Ngưỡng cài sẵn, dùng cho tiếng chuông và rung ở thẻ Dòng, cho tới khi máy chủ công bố ngưỡng của nó.',
  'These come from the server, move with real traffic, and drive the chime and the buzz on the Flow screen.': 'Những ngưỡng này tới từ máy chủ, thay đổi theo lưu lượng thật, và quyết định tiếng chuông cùng rung ở thẻ Dòng.',
  'Send a test notification': 'Gửi một thông báo thử',
  'A test notification will arrive in a few seconds.': 'Thông báo thử sẽ tới sau vài giây.',
  'The test notification could not be scheduled': 'Không đặt được thông báo thử',
  '1 reminder set on this phone for your unlock.': 'Đã đặt 1 lời nhắc trên máy này cho lần mở khoá của bạn.',
  '{count} reminders set on this phone for your unlock.': 'Đã đặt {count} lời nhắc trên máy này cho lần mở khoá của bạn.',
  'The reminders for your unlock were cancelled.': 'Các lời nhắc mở khoá đã bị huỷ.',
  'The alert could not be changed.': 'Không đổi được lời nhắc.',
  'Language': 'Ngôn ngữ',
  'The app follows your phone until you choose here. The card you share stays in English, so it reads the same to everyone who sees it.': 'Ứng dụng đi theo ngôn ngữ của máy cho tới khi bạn chọn ở đây. Thẻ bạn chia sẻ vẫn giữ tiếng Anh, để ai nhìn thấy cũng đọc được như nhau.',

  // Chính các thông báo
  'This wallet has no pending SKR unlock.': 'Ví này không có SKR nào đang chờ mở khoá.',
  'SKR unlocks in 1 hour': 'SKR mở khoá sau 1 giờ',
  'Your pending SKR is approaching its withdrawable time.': 'Số SKR đang chờ của bạn sắp tới lúc rút được.',
  'Your SKR is now withdrawable': 'SKR của bạn đã có thể rút',
  'Open SKR Eyes to verify the finalized position and evidence.': 'Mở SKR Eyes để kiểm tra vị thế đã chốt và bằng chứng.',
  'SKR Eyes alerts are ready': 'Nhắc của SKR Eyes đã sẵn sàng',
  'Test complete. Real unlock alerts will use finalized on-chain time.': 'Đã thử xong. Nhắc thật sẽ dùng giờ đã chốt trên chuỗi.',

  // Cửa sổ stake
  'Add to your position': 'Thêm vào vị thế của bạn',
  'Amount per transaction': 'Số tiền mỗi giao dịch',
  'SKR has six decimal places. Shorten the amount — the extra digits cannot be staked.': 'SKR có sáu chữ số thập phân. Hãy rút ngắn số tiền, phần dư không stake được.',
  'A single transaction cannot stake less than 1 SKR.': 'Một giao dịch không thể stake ít hơn 1 SKR.',
  'This is what one transaction stakes. The total is this amount times the count below.': 'Đây là mức một giao dịch stake. Tổng bằng số này nhân với số lần bên dưới.',
  'How many transactions': 'Bao nhiêu giao dịch',
  'One transaction, one wallet approval.': 'Một giao dịch, một lần xác nhận trong ví.',
  '{count} identical transactions from one approval, sent one after another. Each one is a separate on-chain stake.': '{count} giao dịch giống nhau từ một lần xác nhận, gửi lần lượt. Mỗi giao dịch là một lần stake riêng trên chuỗi.',
  'This needs {needed} SKR and you hold {held}. ': 'Cần {needed} SKR mà bạn đang có {held}. ',
  'At this amount you can send 1 part.': 'Với số này bạn gửi được 1 phần.',
  'At this amount you can send {count} parts.': 'Với số này bạn gửi được {count} phần.',
  'Lower the amount to stake what you have.': 'Giảm số tiền để stake đúng phần bạn đang có.',
  'You hold {held} SKR.': 'Bạn đang có {held} SKR.',
  'Before you sign': 'Trước khi ký',
  'sent as': 'gửi dưới dạng',
  'you stake in total': 'tổng bạn stake',
  'position account rent': 'phí giữ tài khoản vị thế',
  'already paid': 'đã trả',
  '{sol} SOL, once': '{sol} SOL, một lần',
  'Your position account already exists, so only the network fee applies — a few thousand lamports per transaction.': 'Tài khoản vị thế của bạn đã có sẵn nên chỉ tính phí mạng: vài nghìn lamport mỗi giao dịch.',
  'The first stake creates your position account and its rent stays with the account. Network fees are a few thousand lamports per transaction.': 'Lần stake đầu tiên tạo tài khoản vị thế và khoản phí giữ nằm lại trong tài khoản đó. Phí mạng là vài nghìn lamport mỗi giao dịch.',
  'Working…': 'Đang xử lý…',
  'At least 1 SKR per transaction': 'Ít nhất 1 SKR mỗi giao dịch',
  'Sign and stake {amount} SKR': 'Ký và stake {amount} SKR',
  'Sign and stake': 'Ký và stake',
  'All parts landed': 'Tất cả các phần đã lên chuỗi',
  'Stopped': 'Đã dừng',
  'Approve in your wallet': 'Xác nhận trong ví của bạn',
  'Preparing transactions': 'Đang chuẩn bị giao dịch',
  'A run from before': 'Một lượt gửi từ trước',
  'Landing on chain': 'Đang lên chuỗi',
  'pending': 'đang chờ',
  'sending': 'đang gửi',
  'sent': 'đã gửi',
  'confirmed': 'đã xác nhận',
  'unknown': 'không rõ',
  'failed': 'thất bại',
  'We do not know yet': 'Chúng tôi chưa biết',
  'What happened': 'Chuyện gì đã xảy ra',
  'Ask the chain again': 'Hỏi lại chuỗi',
  'Stake again': 'Stake lần nữa',
  'Discard and start over': 'Bỏ và làm lại từ đầu',
  'Start over': 'Làm lại từ đầu',
  'Close': 'Đóng',
};
