// Tiếng Việt. Khoá tra cứu chính là câu tiếng Anh nằm trong mã nguồn.
//
// Quy tắc của bảng này: nói giản dị, không dùng từ quảng cáo, không dùng dấu
// chấm than, xưng hô "bạn". Mã token (SKR, SOL), tên ví (Seed Vault) và tên ứng
// dụng giữ nguyên. Các con số đã được định dạng sẵn: dấu ngoặc nhọn có thể đổi
// chỗ nhưng không đổi tên. "Thẻ" là tấm thẻ chia sẻ, các màn hình chính gọi là "mục".

export const vi: Record<string, string> = {
  'Vault': 'Kho',
  'over the last 7 days': 'trong 7 ngày qua',
  'over the last 30 days': 'trong 30 ngày qua',
  '{percent}% of all SKR is staked': '{percent}% toàn bộ SKR đang được stake',
  'over the last 24 hours': 'trong 24 giờ qua',
  'net': 'ròng',
  'wallets': 'ví',
  // Các mục và huy hiệu độ mới
  'Flow': 'Dòng',
  'Me': 'Tôi',
  'Queue': 'Hàng chờ',
  'Alerts': 'Nhắc',
  'fresh': 'mới',
  'aging': 'hơi cũ',
  'stale': 'cũ',
  'unavailable': 'không có',
  'syncing': 'đang đồng bộ',
  'every number has a receipt': 'mỗi con số đều có bằng chứng',

  // Kho
  'Waiting for a finalized answer': 'Đang chờ kết quả đã chốt',
  'Reading the vault': 'Đang đọc kho',
  'Network unavailable': 'Không có mạng',
  'Last 24 hours': '24 giờ qua',
  'Last 7 days': '7 ngày qua',
  'Last 30 days': '30 ngày qua',
  'staked': 'đã stake',
  'asked out': 'xin rút',
  'in': 'vào',
  'staked minus requested out': 'đã stake trừ đi xin rút',
  '24h': '24h',
  'history covers {days}d': 'lịch sử {days} ngày',
  'In cooldown': 'Đang chờ',
  '{count} positions waiting out the 48 hours': '{count} vị thế đang chờ hết 48 giờ',
  'Ready to exit': 'Sẵn sàng rời kho',
  'Cooldown finished, not yet withdrawn': 'Hết thời gian chờ, chưa rút',
  'When the queue matures': 'Khi nào hàng chờ tới hạn',
  'ready': 'sẵn sàng',
  'ready to withdraw': 'sẵn sàng rút',
  'cooling down': 'đang chờ',

  // Chuyển động của cảnh kho
  'Motion': 'Chuyển động',
  'The vault stands still.': 'Kho đứng yên.',
  'One gentle frame a second.': 'Một khung hình nhẹ nhàng mỗi giây.',
  'Live while you watch. Calm after 90 seconds without a touch.': 'Sống động khi bạn đang xem. Dịu lại sau 90 giây không chạm.',
  'Receipt': 'Biên lai',
  'Open on Solscan': 'Mở trên Solscan',

  // Hàng chờ
  'Exits in flight, soonest first': 'Các lệnh rời kho đang chờ, gần hạn nhất lên trước',
  '{count} shown': 'hiện {count}',
  'Show all {count}': 'Hiện tất cả {count}',
  'Show fewer': 'Thu gọn',
  'Nothing is queued to leave right now.': 'Hiện chưa có gì xếp hàng rời kho.',

  // Dòng
  'Live from the vault': 'Trực tiếp từ kho',
  'Reconnecting': 'Đang kết nối lại',
  'BUZZ ON': 'RUNG BẬT',
  'BUZZ OFF': 'RUNG TẮT',
  'SOUND ON': 'TIẾNG BẬT',
  'SOUND OFF': 'TIẾNG TẮT',
  'Biggest seen today': 'Lớn nhất hôm nay',
  'Biggest stake today': 'Stake lớn nhất hôm nay',
  'Biggest exit today': 'Lệnh xin rút lớn nhất hôm nay',
  'Biggest withdrawal today': 'Lệnh rút lớn nhất hôm nay',
  'Last big move': 'Biến động lớn gần nhất',
  '{age} ago': '{age} trước',
  'slot {slot}': 'slot {slot}',
  'amount unavailable': 'không đọc được số lượng',
  'withdrew': 'đã rút',
  'cancelled exit': 'huỷ xin rút',
  'stake': 'stake',
  'unstake': 'xin rút',
  'withdraw': 'rút',
  'Fold the older large moves': 'Thu gọn các biến động lớn cũ hơn',
  '1 more large move': 'thêm 1 biến động lớn',
  '{count} more large moves': 'thêm {count} biến động lớn',
  '{count} landed while you watched': '{count} giao dịch tới trong lúc bạn xem',
  'Watching the chain': 'Đang theo dõi chuỗi',
  'ALL': 'TẤT CẢ',
  'only {amount} SKR and up': 'chỉ từ {amount} SKR trở lên',
  'everything, dust included': 'tất cả, kể cả khoản lẻ',
  'Waiting for the next finalized event of this size.': 'Đang chờ giao dịch đã chốt tiếp theo ở mức này.',

  // Tôi: hồ sơ và thẻ
  'Leaving': 'Đang rời kho',
  '1 position in cooldown': '1 vị thế đang chờ',
  '{count} positions in cooldown': '{count} vị thế đang chờ',
  'Ready now': 'Sẵn sàng ngay',
  'Next unlock': 'Lần mở khoá tới',
  'Cooldown finished': 'Hết thời gian chờ',
  'Until this position is free': 'Tới khi vị thế này được mở',
  'Nothing queued': 'Không có gì trong hàng chờ',
  'Your weight in the vault': 'Tỷ trọng của bạn trong kho',
  'First stake {days} days ago, read from the oldest signature on your position account.': 'Lần stake đầu cách đây {days} ngày, đọc từ chữ ký cũ nhất trên tài khoản vị thế của bạn.',
  'Held at least {days} days. Your position has a long signature history, so the walk back is still going.': 'Đã giữ ít nhất {days} ngày. Vị thế của bạn có lịch sử chữ ký dài nên việc lần ngược vẫn đang chạy.',
  'Reading the age of your position from the chain…': 'Đang đọc tuổi vị thế của bạn từ chuỗi…',
  'Stake SKR': 'Stake SKR',
  'Drawing your card…': 'Đang vẽ thẻ của bạn…',
  'Share your card': 'Chia sẻ thẻ của bạn',
  'Alerts armed': 'Đã đặt nhắc',
  'Wake me at unlock': 'Đánh thức khi mở khoá',
  'Refresh': 'Làm mới',
  'Disconnect': 'Ngắt kết nối',
  'This address holds no SKR position right now.': 'Địa chỉ này hiện không có vị thế SKR nào.',
  'This wallet holds no SKR position yet. The first stake opens one; the position account costs a little rent once.': 'Ví này chưa có vị thế SKR nào. Lần stake đầu tiên sẽ mở một vị thế; tài khoản vị thế tốn một chút tiền thuê, chỉ một lần.',
  'This position is being looked at, not signed for. Connect the wallet that holds it to stake from it.': 'Vị thế này chỉ đang được xem, không ký được. Hãy kết nối ví đang giữ nó để stake từ đó.',
  'Connect the wallet that holds your stake, or paste any public address. Nothing is signed.': 'Kết nối ví đang giữ phần stake của bạn, hoặc dán bất kỳ địa chỉ công khai nào. Không ký gì cả.',
  'Connect Solana Mobile': 'Kết nối Solana Mobile',
  'OR': 'HOẶC',
  'Paste a Solana address': 'Dán một địa chỉ Solana',
  'Look up': 'Tra cứu',
  'WEIGHT': 'TỶ TRỌNG',
  'POSITIONS': 'VỊ THẾ',
  'READ FROM': 'ĐỌC TỪ',
  '1 unlock alert armed on this phone.': 'Đã đặt 1 nhắc mở khoá trên máy này.',
  '{count} unlock alerts armed on this phone.': 'Đã đặt {count} nhắc mở khoá trên máy này.',
  'Nothing left to wait for — the cooldown is already over.': 'Không còn gì để chờ, thời gian chờ đã hết.',
  'Caption copied. Paste it next to the picture.': 'Đã chép phần chữ. Dán nó cạnh ảnh.',
  'This phone would not take the caption — type it yourself.': 'Máy này không nhận phần chữ, bạn tự gõ nhé.',
  'Your SKR staker card': 'Thẻ staker SKR của bạn',
  'This phone has nothing to share with.': 'Máy này không có ứng dụng nào để chia sẻ.',

  // Riêng tư trên thẻ chia sẻ
  'Hide my name on the card': 'Ẩn tên tôi trên thẻ',
  'The eye in the ring closes and the card says A Seeker.': 'Con mắt trong vòng nhắm lại và thẻ chỉ ghi "Một người dùng Seeker".',
  'Hide my amount on the card': 'Ẩn số lượng trên thẻ',
  'Days, since and one-of stay; the position line goes.': 'Số ngày, ngày bắt đầu và dòng "một trong số" vẫn giữ; dòng số lượng bị bỏ.',
  'An exact amount next to a start date is close to a fingerprint. Your choice, said plainly.': 'Một con số chính xác đặt cạnh ngày bắt đầu gần như là dấu vân tay. Nói thẳng, quyền chọn là của bạn.',

  // Mười sáu phần mỗi ngày
  'Sixteen': 'Mười sáu',
  'The daily sixteen': 'Mười sáu phần mỗi ngày',
  '16 parts of 1 SKR, one approval. A small daily habit that keeps your position moving.': '16 phần của 1 SKR, một lần xác nhận. Một thói quen nhỏ mỗi ngày giúp vị thế của bạn luôn chuyển động.',

  // Ủng hộ ứng dụng
  'Support SKR Eyes': 'Ủng hộ SKR Eyes',
  'Send a tip': 'Gửi tip',
  'A tip in SKR': 'Tip bằng SKR',
  'How much': 'Bao nhiêu',
  'Any amount you like. Goes to {name}, the wallet behind this app.': 'Bao nhiêu tuỳ bạn. Gửi tới {name}, ví đứng sau ứng dụng này.',
  'Send {amount} SKR to {name}': 'Gửi {amount} SKR tới {name}',
  '{amount} SKR on its way to {name}': '{amount} SKR đang trên đường tới {name}',
  'Thank you': 'Cảm ơn bạn',
  'Done': 'Xong',
  'Landing on chain…': 'Đang lên chuỗi…',
  'Your wallet signs and sends it. The app only fetches a blockhash before and reads the status after.': 'Ví của bạn ký và gửi. Ứng dụng chỉ lấy blockhash trước đó và đọc trạng thái sau đó.',
  'A tip changes nothing about your position and nothing about any airdrop. It is a thank you, not a fee.': 'Tip không đổi gì ở vị thế của bạn, cũng không đổi gì ở bất kỳ airdrop nào. Đó là lời cảm ơn, không phải phí.',
  'Free and open source, built by one Seeker. Tips in SKR go to kosa.skr and are staked right away, all of them.': 'Miễn phí và mã nguồn mở, do một người dùng Seeker làm ra. Tip bằng SKR đi tới kosa.skr và được stake ngay, toàn bộ.',
  'This app is free, open source, and built by one Seeker. If it saved you a moment, a tip is welcome. Every SKR that arrives is staked right away, all of it.': 'Ứng dụng này miễn phí, mã nguồn mở, do một người dùng Seeker làm ra. Nếu nó giúp bạn đỡ mất chút thời gian, một khoản tip là rất quý. Mỗi SKR nhận được đều được stake ngay, toàn bộ.',
  'This is {name} itself. A tip to your own wallet moves nothing; try from another wallet.': 'Đây chính là {name}. Tip vào ví của chính mình thì không chuyển gì cả; hãy thử từ một ví khác.',
  'The chain rejected the transfer.': 'Chuỗi đã từ chối giao dịch chuyển.',
  'The wallet declined. Nothing was sent.': 'Ví đã từ chối. Chưa gửi gì cả.',
  'The wallet returned no signature.': 'Ví không trả về chữ ký nào.',
  'SKR has six decimal places. Shorten the amount.': 'SKR có sáu chữ số thập phân. Hãy rút ngắn số lượng.',

  // Những lỗi người dùng thật sự nhìn thấy
  'The finalized snapshot is still warming up. Try again in a moment.': 'Bản chốt vẫn đang chuẩn bị. Thử lại sau giây lát.',
  'This position could not be read': 'Không đọc được vị thế này',
  'The wallet request was cancelled': 'Yêu cầu gửi tới ví đã bị huỷ',
  'The wallet did not return an account.': 'Ví không trả về tài khoản nào.',
  'The wallet that answered is not the one on screen. Connect the wallet that holds this position, then stake. Nothing was sent.': 'Ví vừa trả lời không phải ví đang hiện trên màn hình. Hãy kết nối ví đang giữ vị thế này rồi stake. Chưa gửi gì cả.',
  'The app was closed while the wallet had this stake. Check your position before staking again, then clear this.': 'Ứng dụng đã bị đóng trong lúc ví đang xử lý khoản stake này. Kiểm tra vị thế của bạn trước khi stake lại, rồi xoá thông báo này.',
  'Alerts could not be scheduled': 'Không đặt được nhắc',
  'The card is not ready yet': 'Thẻ chưa sẵn sàng',
  'The card could not be drawn': 'Không vẽ được thẻ',
  'the chain returned no signatures': 'chuỗi không trả về chữ ký nào',
  'age lookup failed': 'không tra cứu được tuổi',
  'SKR Eyes API returned {status}': 'API của SKR Eyes trả về {status}',
  'The age service answered {status}': 'Dịch vụ tra tuổi trả về {status}',

  // Màn hình nhắc
  'Notifications allowed': 'Đã cho phép thông báo',
  'Notifications off': 'Thông báo đang tắt',
  'Alerts are scheduled on the phone itself. Nothing about you leaves the device.': 'Nhắc do chính điện thoại đặt. Không có thông tin nào của bạn rời khỏi máy.',
  'Allow notifications and this app can wake you exactly when your cooldown ends.': 'Cho phép thông báo để ứng dụng đánh thức bạn đúng lúc hết thời gian chờ.',
  'Allow notifications': 'Cho phép thông báo',
  'Open settings': 'Mở cài đặt',
  'This phone can now wake you.': 'Giờ máy này có thể đánh thức bạn.',
  'Android will not ask again. Turn notifications on for SKR Eyes in the system settings.': 'Android sẽ không hỏi lại. Hãy bật thông báo cho SKR Eyes trong cài đặt hệ thống.',
  'Android is holding notifications back for this app.': 'Android đang chặn thông báo của ứng dụng này.',
  'Android did not answer the permission request. Try again, or turn notifications on in the system settings.': 'Android không trả lời yêu cầu quyền. Thử lại, hoặc bật thông báo trong cài đặt hệ thống.',
  'This phone would not open its settings screen.': 'Máy này không mở được màn hình cài đặt.',
  'Wake me at my unlock': 'Đánh thức tôi khi mở khoá',
  'Connect your wallet on the Me screen and this switch becomes live.': 'Kết nối ví ở mục Tôi thì công tắc này mới hoạt động.',
  'One hour before, and again the moment the cooldown ends. Scheduled by this phone from the exact on-chain time.': 'Một giờ trước, và một lần nữa đúng lúc hết thời gian chờ. Do chính máy này đặt theo giờ chính xác trên chuỗi.',
  'Nothing of yours is unlocking, so there is nothing to wake you for yet.': 'Bạn không có gì đang mở khoá, nên chưa có lý do để đánh thức bạn.',
  'Large moves, heard and felt': 'Biến động lớn, nghe thấy và cảm thấy',
  'A stake of 10K SKR or more rings like a glass coin, a stake of 100K rings the vault bell, an exit of 100K lands with a low boom. On every screen while the app is open, each with a short buzz.': 'Khoản stake từ 10K SKR trở lên kêu như một đồng xu thuỷ tinh, stake 100K rung chuông kho, lệnh xin rút 100K dội một tiếng trầm. Ở mọi màn hình khi ứng dụng đang mở, mỗi lần kèm một nhịp rung ngắn.',
  "Other people's moves do not wake the phone while the app is closed. Only your own unlock does.": 'Biến động của người khác không đánh thức máy khi ứng dụng đã đóng. Chỉ lần mở khoá của chính bạn mới làm vậy.',
  'What counts as large': 'Thế nào là lớn',
  'Built-in thresholds behind the bell and the boom, until the server publishes its own.': 'Ngưỡng cài sẵn đứng sau tiếng chuông và tiếng trầm, cho tới khi máy chủ công bố ngưỡng của mình.',
  'These come from the server, move with real traffic, and drive the bell and the boom.': 'Những ngưỡng này tới từ máy chủ, thay đổi theo lưu lượng thật, và quyết định tiếng chuông cùng tiếng trầm.',
  'Send a test notification': 'Gửi thông báo thử',
  'A test notification will arrive in a few seconds.': 'Thông báo thử sẽ tới sau vài giây.',
  'The test notification could not be scheduled': 'Không đặt được thông báo thử',
  '1 reminder set on this phone for your unlock.': 'Đã đặt 1 lời nhắc trên máy này cho lần mở khoá của bạn.',
  '{count} reminders set on this phone for your unlock.': 'Đã đặt {count} lời nhắc trên máy này cho lần mở khoá của bạn.',
  'The reminders for your unlock were cancelled.': 'Đã huỷ các lời nhắc mở khoá của bạn.',
  'The alert could not be changed.': 'Không đổi được lời nhắc.',
  'Language': 'Ngôn ngữ',
  'The app follows your phone until you choose here. The card you share stays in English, so it reads the same to everyone who sees it.': 'Ứng dụng đi theo ngôn ngữ của máy cho tới khi bạn chọn ở đây. Thẻ bạn chia sẻ vẫn giữ tiếng Anh, để ai nhìn thấy cũng đọc được như nhau.',

  // Chính các thông báo
  'This wallet has no pending SKR unlock.': 'Ví này không có SKR nào đang chờ mở khoá.',
  'SKR unlocks in 1 hour': 'SKR mở khoá sau 1 giờ',
  'Your pending SKR is approaching its withdrawable time.': 'Số SKR đang chờ của bạn sắp tới lúc rút được.',
  'Your SKR is now withdrawable': 'SKR của bạn đã có thể rút',
  'Open SKR Eyes to verify the finalized position and evidence.': 'Mở SKR Eyes để kiểm tra vị thế đã chốt và bằng chứng.',
  'SKR Eyes alerts are ready': 'Nhắc của SKR Eyes đã sẵn sàng',
  'Test complete. Real unlock alerts will use finalized on-chain time.': 'Đã thử xong. Nhắc thật sẽ dùng giờ đã chốt trên chuỗi.',

  // Cửa sổ stake
  'Add to your position': 'Thêm vào vị thế của bạn',
  'Amount per transaction': 'Số SKR mỗi giao dịch',
  'SKR has six decimal places. Shorten the amount — the extra digits cannot be staked.': 'SKR có sáu chữ số thập phân. Hãy rút ngắn số lượng, phần lẻ dư không stake được.',
  'A single transaction cannot stake less than 1 SKR.': 'Một giao dịch không thể stake ít hơn 1 SKR.',
  'This is what one transaction stakes. The total is this amount times the count below.': 'Đây là mức một giao dịch stake. Tổng bằng số này nhân với số lần bên dưới.',
  'How many transactions': 'Bao nhiêu giao dịch',
  'One transaction, one wallet approval.': 'Một giao dịch, một lần xác nhận trong ví.',
  '{count} identical transactions from one approval, sent one after another. Each one is a separate on-chain stake.': '{count} giao dịch giống nhau từ một lần xác nhận, gửi lần lượt. Mỗi giao dịch là một lần stake riêng trên chuỗi.',
  'This needs {needed} SKR and you hold {held}. ': 'Cần {needed} SKR mà bạn chỉ có {held}. ',
  'At this amount you can send 1 part.': 'Với số này bạn gửi được 1 phần.',
  'At this amount you can send {count} parts.': 'Với số này bạn gửi được {count} phần.',
  'Lower the amount to stake what you have.': 'Giảm số lượng để stake đúng phần bạn đang có.',
  'You hold {held} SKR.': 'Bạn đang có {held} SKR.',
  'Before you sign': 'Trước khi ký',
  'sent as': 'gửi dưới dạng',
  'you stake in total': 'tổng cộng bạn stake',
  'position account rent': 'tiền thuê tài khoản vị thế',
  'already paid': 'đã trả',
  '{sol} SOL, once': '{sol} SOL, một lần',
  'Your position account already exists, so only the network fee applies — a few thousand lamports per transaction.': 'Tài khoản vị thế của bạn đã có sẵn nên chỉ tính phí mạng: vài nghìn lamport mỗi giao dịch.',
  'The first stake creates your position account and its rent stays with the account. Network fees are a few thousand lamports per transaction.': 'Lần stake đầu tiên tạo tài khoản vị thế, tiền thuê nằm lại trong tài khoản đó. Phí mạng là vài nghìn lamport mỗi giao dịch.',
  'Working…': 'Đang xử lý…',
  'At least 1 SKR per transaction': 'Ít nhất 1 SKR mỗi giao dịch',
  'Sign and stake {amount} SKR': 'Ký và stake {amount} SKR',
  'Sign and stake': 'Ký và stake',
  'All parts landed': 'Mọi phần đã lên chuỗi',
  'Stopped': 'Đã dừng',
  'Approve in your wallet': 'Xác nhận trong ví của bạn',
  'Preparing transactions': 'Đang chuẩn bị giao dịch',
  'A run from before': 'Một lượt gửi từ trước',
  'Landing on chain': 'Đang lên chuỗi',
  'pending': 'đang chờ',
  'sending': 'đang gửi',
  'sent': 'đã gửi',
  'confirmed': 'đã xác nhận',
  'unknown': 'không rõ',
  'failed': 'thất bại',
  'We do not know yet': 'Chưa biết',
  'What happened': 'Chuyện gì đã xảy ra',
  'Ask the chain again': 'Hỏi lại chuỗi',
  'Stake again': 'Stake lần nữa',
  'Discard and start over': 'Bỏ và làm lại từ đầu',
  'Start over': 'Làm lại từ đầu',
  'Close': 'Đóng',
};
