// Simplified Chinese. The key is the English sentence as it stands in the code.
//
// House rules for this file, so a second translator keeps the same voice:
// plain speech, no marketing words, no exclamation marks. Token tickers (SKR,
// SOL), the wallet's own name (Seed Vault) and the app's name stay in Latin
// script, they are printed that way everywhere else the person will see them.
// Full-width Chinese punctuation (，。；“”) inside values; a thin ASCII space
// separates Latin tokens and numbers from Chinese characters.
// Numbers arrive already formatted, so the braces only move, never change.

export const zh: Record<string, string> = {
  'over the last 7 days': '最近 7 天',
  'over the last 30 days': '最近 30 天',
  '{percent}% of all SKR is staked': '全部 SKR 的 {percent}% 已质押',
  'over the last 24 hours': '最近 24 小时',
  'net': '净额',
  'wallets': '钱包',
  // Tabs and the freshness badge
  'Pulse': '脉搏',
  'Flow': '流水',
  'Me': '我的',
  'Queue': '队列',
  'Alerts': '提醒',
  'fresh': '最新',
  'aging': '稍旧',
  'stale': '过时',
  'unavailable': '不可用',
  'syncing': '同步中',
  'every number has a receipt': '每个数字都有凭证',

  // Pulse / Vault scene
  'Waiting for a finalized answer': '等待最终确认的结果',
  'Reading the vault': '正在读取金库',
  'Network unavailable': '网络不可用',
  'Last 24 hours': '最近 24 小时',
  'Last 7 days': '最近 7 天',
  'Last 30 days': '最近 30 天',
  '24h': '24h',
  'staked': '已质押',
  'in': '进入',
  'asked out': '申请退出',
  'staked minus requested out': '已质押减去申请退出',
  'history covers {days}d': '历史覆盖 {days} 天',
  'In cooldown': '冷却中',
  'cooling down': '冷却中',
  '{count} positions waiting out the 48 hours': '{count} 个仓位正在等 48 小时结束',
  'Ready to exit': '可以退出',
  'Cooldown finished, not yet withdrawn': '冷却已结束，尚未提取',
  'When the queue matures': '队列何时到期',
  'ready': '可提取',
  'ready to withdraw': '可提取',
  'Motion': '动效',
  'The vault stands still.': '金库静止不动。',
  'One gentle frame a second.': '每秒轻轻一帧。',
  'Live while you watch. Calm after 90 seconds without a touch.': '你看的时候实时。90 秒没有触碰后转为平静。',
  'Receipt': '凭证',
  'Open on Solscan': '在 Solscan 打开',

  // Queue
  'Ready to withdraw': '可提取',
  '{amount} SKR is still cooling down across {count} positions': '还有 {amount} SKR 在 {count} 个仓位中冷却',
  'Reading the queue': '正在读取队列',
  'Time to maturity': '距离到期',
  'Exits in flight, soonest first': '进行中的退出，最快到期的在前',
  '{count} shown': '显示 {count} 条',
  'Show all {count}': '显示全部 {count} 条',
  'Show fewer': '收起',
  'Nothing is queued to leave right now.': '目前没有排队退出的仓位。',

  // Flow
  'Live from the vault': '金库实时动态',
  'Reconnecting': '正在重新连接',
  'BUZZ ON': '震动开',
  'BUZZ OFF': '震动关',
  'SOUND ON': '声音开',
  'SOUND OFF': '声音关',
  'Biggest seen today': '今日最大一笔',
  'Biggest stake today': '今日最大质押',
  'Biggest exit today': '今日最大退出',
  'Biggest withdrawal today': '今日最大提取',
  'Last big move': '上一笔大额',
  '{age} ago': '{age}前',
  'slot {slot}': '槽位 {slot}',
  'amount unavailable': '金额不可用',
  'withdrew': '已提取',
  'cancelled exit': '已取消退出',
  'stake': '质押',
  'unstake': '解除质押',
  'withdraw': '提取',
  'Fold the older large moves': '收起较早的大额',
  '1 more large move': '还有 1 笔大额',
  '{count} more large moves': '还有 {count} 笔大额',
  '{count} landed while you watched': '你看的这会儿到了 {count} 笔',
  'Watching the chain': '正在监听链上',
  'ALL': '全部',
  'only {amount} SKR and up': '只看 {amount} SKR 以上',
  'everything, dust included': '全部，包括零星小额',
  'Waiting for the next finalized event of this size.': '等待下一笔达到这个额度并最终确认的交易。',

  // Me — profile and card
  'Leaving': '退出中',
  '1 position in cooldown': '1 个仓位在冷却',
  '{count} positions in cooldown': '{count} 个仓位在冷却',
  'Ready now': '现在可提取',
  'Next unlock': '下次解锁',
  'Cooldown finished': '冷却已结束',
  'Until this position is free': '距离该仓位解冻',
  'Nothing queued': '没有排队',
  'Your weight in the vault': '你在金库中的占比',
  'First stake {days} days ago, read from the oldest signature on your position account.': '首次质押在 {days} 天前，取自你仓位账户上最早的一条签名。',
  'Held at least {days} days. Your position has a long signature history, so the walk back is still going.': '至少已持有 {days} 天。你的仓位签名记录很长，仍在往前回溯。',
  'Reading the age of your position from the chain…': '正在从链上读取你的仓位年龄…',
  'Stake SKR': '质押 SKR',
  'Drawing your card…': '正在生成卡片…',
  'Share your card': '分享你的卡片',
  'Alerts armed': '提醒已设置',
  'Wake me at unlock': '解锁时叫醒我',
  'Refresh': '刷新',
  'Disconnect': '断开连接',
  'This address holds no SKR position right now.': '该地址目前没有 SKR 仓位。',
  'This wallet holds no SKR position yet. The first stake opens one; the position account costs a little rent once.': '这个钱包还没有 SKR 仓位。首次质押会开一个；仓位账户需一次性付少量租金。',
  'This position is being looked at, not signed for. Connect the wallet that holds it to stake from it.': '这个仓位只是在查看，没有签名权限。要从它质押，请连接持有它的钱包。',
  'Connect the wallet that holds your stake, or paste any public address. Nothing is signed.': '连接持有你质押的钱包，或粘贴任意公开地址。不会进行任何签名。',
  'Connect Solana Mobile': '连接 Solana Mobile',
  'OR': '或',
  'Paste a Solana address': '粘贴 Solana 地址',
  'Look up': '查询',
  'WEIGHT': '占比',
  'POSITIONS': '仓位数',
  'READ FROM': '读取自',
  '1 unlock alert armed on this phone.': '已在这台手机上设置 1 条解锁提醒。',
  '{count} unlock alerts armed on this phone.': '已在这台手机上设置 {count} 条解锁提醒。',
  'Nothing left to wait for — the cooldown is already over.': '没有什么可等的了，冷却期已经结束。',
  'Caption copied. Paste it next to the picture.': '文案已复制，发图时粘贴即可。',
  'This phone would not take the caption — type it yourself.': '这台手机没能接收文案，请自己输入。',
  'Your SKR staker card': '你的 SKR 质押卡片',
  'This phone has nothing to share with.': '这台手机没有可用来分享的应用。',
  'Hide my name on the card': '卡片上隐藏我的名字',
  'The eye in the ring closes and the card says A Seeker.': '环中的眼睛闭上，卡片上显示“一位 Seeker”。',
  'Hide my amount on the card': '卡片上隐藏我的金额',
  'Days, since and one-of stay; the position line goes.': '保留天数、起始日期和“之一”，去掉仓位金额那一行。',
  'An exact amount next to a start date is close to a fingerprint. Your choice, said plainly.': '精确金额配上开始日期，几乎就是一枚指纹。直说了，怎么选由你。',

  // Tip sheet
  'Support SKR Eyes': '支持 SKR Eyes',
  'Send a tip': '打赏',
  'A tip in SKR': '用 SKR 打赏',
  'How much': '多少',
  'Any amount you like. Goes to {name}, the wallet behind this app.': '金额随意。会发给 {name}，也就是这个应用背后的钱包。',
  'Send {amount} SKR to {name}': '向 {name} 发送 {amount} SKR',
  '{amount} SKR on its way to {name}': '{amount} SKR 正在发往 {name}',
  'Thank you': '谢谢',
  'Done': '完成',
  'Landing on chain…': '正在上链…',
  'Your wallet signs and sends it. The app only fetches a blockhash before and reads the status after.': '由你的钱包签名并发送。应用只在之前获取一个区块哈希，之后读取状态。',
  'A tip changes nothing about your position and nothing about any airdrop. It is a thank you, not a fee.': '打赏不会改变你的仓位，也不会影响任何空投。这是一份心意，不是费用。',
  'Free and open source, built by one Seeker. Tips in SKR go to kosa.skr and are staked right away, all of them.': '免费开源，由一位 Seeker 独立打造。SKR 打赏发往 kosa.skr，并会全部立即质押。',
  'This app is free, open source, and built by one Seeker. If it saved you a moment, a tip is welcome. Every SKR that arrives is staked right away, all of it.': '这个应用免费开源，由一位 Seeker 独立打造。如果它帮你省了点时间，欢迎打赏。收到的每一枚 SKR 都会立即全部质押。',
  'This is {name} itself. A tip to your own wallet moves nothing; try from another wallet.': '这就是 {name} 本人。给自己的钱包打赏什么都不会动；请换一个钱包试试。',
  'The chain rejected the transfer.': '链上拒绝了这笔转账。',
  'The wallet declined. Nothing was sent.': '钱包拒绝了。什么都没有发出。',
  'The wallet returned no signature.': '钱包没有返回签名。',
  'SKR has six decimal places. Shorten the amount.': 'SKR 有六位小数。请缩短金额。',

  // Errors the person can actually see
  'The finalized snapshot is still warming up. Try again in a moment.': '最终确认的快照还在准备中，请稍后再试。',
  'This position could not be read': '无法读取该仓位',
  'The wallet request was cancelled': '钱包请求已取消',
  'The wallet did not return an account.': '钱包没有返回账户。',
  'The wallet that answered is not the one on screen. Connect the wallet that holds this position, then stake. Nothing was sent.': '响应的钱包不是屏幕上显示的这个。请连接持有该仓位的钱包再质押。什么都没有发出。',
  'The app was closed while the wallet had this stake. Check your position before staking again, then clear this.': '这笔质押进行中时应用被关闭了。再次质押前请先核对你的仓位，然后清除这条记录。',
  'Alerts could not be scheduled': '无法设置提醒',
  'The card is not ready yet': '卡片还没准备好',
  'The card could not be drawn': '无法生成卡片',
  'the chain returned no signatures': '链上没有返回签名',
  'age lookup failed': '年龄查询失败',
  'SKR Eyes API returned {status}': 'SKR Eyes 接口返回 {status}',
  'The age service answered {status}': '年龄服务返回 {status}',

  // Alerts screen
  'Notifications allowed': '通知已允许',
  'Notifications off': '通知已关闭',
  'Alerts are scheduled on the phone itself. Nothing about you leaves the device.': '提醒由手机自己安排。你的任何信息都不会离开这台设备。',
  'Allow notifications and this app can wake you exactly when your cooldown ends.': '允许通知后，冷却结束的那一刻应用就能叫醒你。',
  'Allow notifications': '允许通知',
  'Open settings': '打开设置',
  'This phone can now wake you.': '这台手机现在可以叫醒你了。',
  'Android will not ask again. Turn notifications on for SKR Eyes in the system settings.': 'Android 不会再询问了。请在系统设置里为 SKR Eyes 打开通知。',
  'Android is holding notifications back for this app.': 'Android 正在拦截本应用的通知。',
  'Android did not answer the permission request. Try again, or turn notifications on in the system settings.': 'Android 没有响应权限请求。请重试，或在系统设置里打开通知。',
  'This phone would not open its settings screen.': '这台手机没能打开系统设置界面。',
  'Wake me at my unlock': '解锁时叫醒我',
  'Connect your wallet on the Me screen and this switch becomes live.': '在“我的”页面连接钱包后，这个开关才会生效。',
  'One hour before, and again the moment the cooldown ends. Scheduled by this phone from the exact on-chain time.': '提前一小时提醒一次，冷却结束时再提醒一次。由这台手机按链上的准确时间安排。',
  'Nothing of yours is unlocking, so there is nothing to wake you for yet.': '你没有正在解锁的仓位，暂时没有需要叫醒你的事。',
  'Large moves, heard and felt': '大额变动，听得到也感受得到',
  'A stake of 1K SKR or more rings like a glass coin, a stake of 100K rings the vault bell, an exit of 100K lands with a low boom. On every screen while the app is open, each with a short buzz.': '1K SKR 以上的质押像玻璃硬币一样清脆作响，100K 的质押会敲响金库的钟，100K 的退出则伴随一声低沉的轰鸣。应用打开时在每个页面都会响，并伴有短促的震动。',
  'Other people\'s moves do not wake the phone while the app is closed. Only your own unlock does.': '应用关闭时，别人的变动不会唤醒手机。只有你自己的解锁会。',
  'What counts as large': '多大算大额',
  'Built-in thresholds behind the bell and the boom, until the server publishes its own.': '钟声和轰鸣背后的内置阈值，在服务器给出自己的阈值之前使用。',
  'These come from the server, move with real traffic, and drive the bell and the boom.': '这些来自服务器，随真实交易量变化，决定钟声和轰鸣。',
  'Send a test notification': '发送一条测试通知',
  'A test notification will arrive in a few seconds.': '测试通知会在几秒内到达。',
  'The test notification could not be scheduled': '无法安排测试通知',
  '1 reminder set on this phone for your unlock.': '已在这台手机上为你的解锁设置 1 条提醒。',
  '{count} reminders set on this phone for your unlock.': '已在这台手机上为你的解锁设置 {count} 条提醒。',
  'The reminders for your unlock were cancelled.': '解锁提醒已取消。',
  'The alert could not be changed.': '无法更改该提醒。',
  'Language': '语言',
  'The app follows your phone until you choose here. The card you share stays in English, so it reads the same to everyone who sees it.': '在你这里选择之前，应用跟随手机的语言。分享出去的卡片始终是英文，这样每个看到它的人读到的都一样。',

  // Notifications themselves
  'This wallet has no pending SKR unlock.': '该钱包没有待解锁的 SKR。',
  'SKR unlocks in 1 hour': 'SKR 将在 1 小时后解锁',
  'Your pending SKR is approaching its withdrawable time.': '你冷却中的 SKR 快到可提取时间了。',
  'Your SKR is now withdrawable': '你的 SKR 现在可以提取了',
  'Open SKR Eyes to verify the finalized position and evidence.': '打开 SKR Eyes 查看最终确认的仓位和凭证。',
  'SKR Eyes alerts are ready': 'SKR Eyes 提醒已就绪',
  'Test complete. Real unlock alerts will use finalized on-chain time.': '测试完成。真正的解锁提醒会使用链上最终确认的时间。',

  // Staking sheet
  'Add to your position': '追加到你的仓位',
  'Sixteen': '十六',
  'The daily sixteen': '每日十六份',
  '16 parts of 1 SKR, one approval. A small daily habit that keeps your position moving.': '把 1 SKR 分成 16 份，只需确认一次。一个小小的每日习惯，让你的仓位保持活跃。',
  'Amount per transaction': '每笔金额',
  'SKR has six decimal places. Shorten the amount — the extra digits cannot be staked.': 'SKR 有六位小数。请缩短金额，多出的位数无法质押。',
  'A single transaction cannot stake less than 1 SKR.': '单笔质押不能少于 1 SKR。',
  'This is what one transaction stakes. The total is this amount times the count below.': '这是单笔质押的金额。总额等于它乘以下面的笔数。',
  'How many transactions': '分几笔',
  'One transaction, one wallet approval.': '一笔交易，钱包确认一次。',
  '{count} identical transactions from one approval, sent one after another. Each one is a separate on-chain stake.': '一次确认发出 {count} 笔相同的交易，依次发送。每一笔都是链上独立的质押。',
  'This needs {needed} SKR and you hold {held}. ': '这需要 {needed} SKR，而你持有 {held}。',
  'At this amount you can send 1 part.': '按这个金额你可以发送 1 笔。',
  'At this amount you can send {count} parts.': '按这个金额你可以发送 {count} 笔。',
  'Lower the amount to stake what you have.': '调低金额，用你现有的余额质押。',
  'You hold {held} SKR.': '你持有 {held} SKR。',
  'Before you sign': '签名之前',
  'sent as': '发送方式',
  'you stake in total': '总共质押',
  'position account rent': '仓位账户租金',
  'already paid': '已支付',
  '{sol} SOL, once': '{sol} SOL，一次性',
  'Your position account already exists, so only the network fee applies — a few thousand lamports per transaction.': '你的仓位账户已经存在，因此只需网络手续费，每笔几千 lamports。',
  'The first stake creates your position account and its rent stays with the account. Network fees are a few thousand lamports per transaction.': '首次质押会创建你的仓位账户，租金留在该账户里。网络手续费每笔几千 lamports。',
  'Working…': '处理中…',
  'At least 1 SKR per transaction': '每笔至少 1 SKR',
  'Sign and stake {amount} SKR': '签名并质押 {amount} SKR',
  'Sign and stake': '签名并质押',
  'All parts landed': '每一笔都已上链',
  'Stopped': '已停止',
  'Approve in your wallet': '请在钱包中确认',
  'Preparing transactions': '正在准备交易',
  'A run from before': '上一次未完成的操作',
  'Landing on chain': '正在上链',
  'pending': '等待中',
  'sending': '发送中',
  'sent': '已发送',
  'confirmed': '已确认',
  'unknown': '未知',
  'failed': '失败',
  'We do not know yet': '还不确定',
  'What happened': '发生了什么',
  'Ask the chain again': '再向链上查一次',
  'Stake again': '再质押一次',
  'Discard and start over': '放弃并重新开始',
  'Start over': '重新开始',
  'Close': '关闭',

};
