// Simplified Chinese. The key is the English sentence as it stands in the code.
//
// House rules for this file, so a second translator keeps the same voice:
// plain speech, no marketing words, no exclamation marks. Token tickers (SKR,
// SOL), the wallet's own name (Seed Vault) and the app's name stay in Latin
// script — they are printed that way everywhere else the person will see them.
// Numbers arrive already formatted, so the braces only move, never change.

export const zh: Record<string, string> = {
  // Tabs and the freshness badge
  'Pulse': '脉搏',
  'Flow': '流水',
  'Me': '我的',
  'Queue': '队列',
  'Alerts': '提醒',
  'fresh': '最新',
  'aging': '稍旧',
  'stale': '过期',
  'unavailable': '不可用',
  'syncing': '同步中',
  'every number has a receipt': '每个数字都有凭证',

  // Pulse
  'Staked of total supply': '已质押占总量',
  '{percent}% of the {supply} SKR total supply · {positions} positions': '占 {supply} SKR 总量的 {percent}% · {positions} 个仓位',
  'Waiting for a finalized answer': '等待最终确认的结果',
  'Reading the vault': '正在读取金库',
  'Network unavailable': '网络不可用',
  'Last 24 hours': '最近 24 小时',
  'Last 7 days': '最近 7 天',
  'Last 30 days': '最近 30 天',
  '{amount} staked': '质押 {amount}',
  '{amount} asked out': '申请退出 {amount}',
  'staked': '已质押',
  'asked out': '申请退出',
  '{count} wallets': '{count} 个钱包',
  'one bar per hour': '每小时一根',
  '{range} as one total · daily bars need a server pass': '{range}合计为一根 · 按天分柱需要服务端另行计算',
  '{sign}{amount} net': '净额 {sign}{amount}',
  'history covers {days}d': '历史覆盖 {days} 天',
  'In cooldown': '冷却中',
  '{count} positions waiting out the 48 hours': '{count} 个仓位正在等待 48 小时',
  'Ready to exit': '可以退出',
  'Cooldown finished, not yet withdrawn': '冷却已结束，尚未提取',
  'When the queue matures': '队列何时到期',
  'ready': '可提取',

  // Queue
  'Ready to withdraw': '可提取',
  '{amount} SKR is still cooling down across {count} positions': '还有 {amount} SKR 在 {count} 个仓位中冷却',
  'Reading the queue': '正在读取队列',
  'Time to maturity': '距离到期',
  'Exits in flight, soonest first': '进行中的退出，最近的在前',
  '{count} shown': '显示 {count} 条',
  'Nothing is queued to leave right now.': '目前没有排队退出的仓位。',

  // Flow
  'Live from the vault': '来自金库的实时数据',
  'Reconnecting': '正在重新连接',
  'BUZZ ON': '震动开',
  'BUZZ OFF': '震动关',
  'SOUND ON': '声音开',
  'SOUND OFF': '声音关',
  'Biggest seen today': '今日最大一笔',
  'Last big move': '上一笔大额',
  '{age} ago': '{age}前',
  'slot {slot}': '槽位 {slot}',
  'amount unavailable': '金额不可用',
  'withdrew': '已提取',
  'cancelled exit': '取消退出',
  'stake': '质押',
  'unstake': '解除质押',
  'withdraw': '提取',
  'Fold the older large moves': '收起较早的大额',
  '1 more large move': '还有 1 笔大额',
  '{count} more large moves': '还有 {count} 笔大额',
  '{count} landed while you watched': '你看着的时候到账 {count} 笔',
  'Watching the chain': '正在盯着链上',
  'While you were away': '你离开的时候',
  'One large move landed': '有 1 笔大额到账',
  '{count} large moves landed': '有 {count} 笔大额到账',
  ', the biggest {amount} SKR {verb}': '，最大的一笔 {amount} SKR {verb}',
  'ALL': '全部',
  'only {amount} SKR and up': '只看 {amount} SKR 以上',
  'everything, dust included': '全部，包括零星小额',
  'Waiting for the next finalized event of this size.': '等待下一笔达到这个额度并最终确认的交易。',

  // Me — profile and card
  'Leaving': '退出中',
  '{count} position(s) in cooldown': '{count} 个仓位在冷却',
  'Ready now': '现在可提取',
  'Next unlock': '下次解锁',
  'Cooldown finished': '冷却已结束',
  'Until this position is free': '距离该仓位解冻',
  'Nothing queued': '没有排队',
  'Your weight in the vault': '你在金库中的占比',
  'First stake {days} days ago, read from the oldest signature on your position account.': '首次质押在 {days} 天前，取自你仓位账户上最早的一条签名。',
  'Held at least {days} days. Your position has a long signature history, so the walk back is still going.': '至少已持有 {days} 天。你的仓位签名很多，回溯仍在进行。',
  'Reading the age of your position from the chain…': '正在从链上读取你的仓位年龄…',
  'Stake SKR': '质押 SKR',
  'Drawing your card…': '正在生成卡片…',
  'Share your card': '分享你的卡片',
  'Alerts armed': '提醒已设置',
  'Wake me at unlock': '解锁时叫醒我',
  'Refresh': '刷新',
  'Disconnect': '断开连接',
  'This address holds no SKR position right now.': '该地址目前没有 SKR 仓位。',
  'Connect the wallet that holds your stake, or paste any public address. Nothing is signed.': '连接持有你质押的钱包，或粘贴任意公开地址。不会进行任何签名。',
  'Connect Solana Mobile': '连接 Solana Mobile',
  'OR': '或',
  'Paste a Solana address': '粘贴 Solana 地址',
  'Look up': '查询',
  'WEIGHT': '占比',
  'POSITIONS': '仓位数',
  'READ FROM': '读取自',
  'Connect the wallet that holds your stake to fill this card in.': '连接持有你质押的钱包，卡片就会填上你的数据。',
  '1 unlock alert armed on this phone.': '已在这台手机上设置 1 条解锁提醒。',
  '{count} unlock alerts armed on this phone.': '已在这台手机上设置 {count} 条解锁提醒。',
  'Nothing left to wait for — the cooldown is already over.': '没有什么可等的了，冷却期已经结束。',
  'Caption copied. Paste it next to the picture.': '文案已复制，发图时粘贴即可。',
  'This phone would not take the caption — type it yourself.': '这台手机没能接收文案，请自己输入。',
  'Your SKR staker card': '你的 SKR 质押卡片',
  'This phone has nothing to share with.': '这台手机没有可用来分享的应用。',

  // Errors the person can actually see
  'The finalized snapshot is still warming up. Try again in a moment.': '最终确认的快照还在准备中，请稍后再试。',
  'This position could not be read': '无法读取该仓位',
  'The wallet request was cancelled': '钱包请求已取消',
  'The wallet did not return an account.': '钱包没有返回账户。',
  'Alerts could not be scheduled': '无法设置提醒',
  'The card is not ready yet': '卡片还没准备好',
  'The card could not be drawn': '无法生成卡片',
  'the chain returned no signatures': '链上没有返回签名',
  'age lookup failed': '年龄查询失败',
  'SKR Eyes API returned {status}': 'SKR Eyes 接口返回 {status}',
  'The age service answered {status}': '年龄服务返回 {status}',

  // Alerts screen
  'Notifications allowed': '通知已允许',
  'Notifications off': '通知已关闭',
  'Alerts are scheduled on the phone itself. Nothing about you leaves the device.': '提醒由手机自己安排。你的任何信息都不会离开这台设备。',
  'Allow notifications and this app can wake you exactly when your cooldown ends.': '允许通知后，冷却结束的那一刻应用就能叫醒你。',
  'Allow notifications': '允许通知',
  'Open settings': '打开设置',
  'This phone can now wake you.': '这台手机现在可以叫醒你了。',
  'Android will not ask again. Turn notifications on for SKR Eyes in the system settings.': 'Android 不会再询问了。请在系统设置里为 SKR Eyes 打开通知。',
  'Android is holding notifications back for this app.': 'Android 正在拦截本应用的通知。',
  'Android did not answer the permission request. Try again, or turn notifications on in the system settings.': 'Android 没有响应权限请求。请重试，或在系统设置里打开通知。',
  'This phone would not open its settings screen.': '这台手机没能打开系统设置界面。',
  'Wake me at my unlock': '解锁时叫醒我',
  'Connect your wallet on the Me screen and this switch becomes live.': '在“我的”页面连接钱包后，这个开关才会生效。',
  'One hour before, and again the moment the cooldown ends. Scheduled by this phone from the exact on-chain time.': '提前一小时提醒一次，冷却结束时再提醒一次。由这台手机按链上的准确时间安排。',
  'Nothing of yours is unlocking, so there is nothing to wake you for yet.': '你没有正在解锁的仓位，暂时没有需要叫醒你的事。',
  'Large moves while you were away': '你离开时的大额变动',
  'Anything above the threshold below is summed up at the top of Flow when you come back to it, and lands with a chime and a buzz while you are watching.': '超过下方阈值的变动，会在你回到“流水”页时汇总在顶部；你正在看的时候则伴随提示音和震动出现。',
  "Waking the phone for someone else's large move while the app is closed needs a background check that Android schedules on its own terms. That is the next version — promising it here before it exists would be the same lie this screen just removed.": '在应用关闭时为别人的大额变动唤醒手机，需要一项由 Android 自行安排的后台检查。那是下一个版本的事；在做出来之前就在这里承诺，就成了这个页面刚刚删掉的那种谎话。',
  'What counts as large in Flow': '“流水”里多大算大额',
  'Built-in thresholds, used by the chime and the buzz on the Flow screen, until the server publishes its own.': '内置阈值，在服务器给出自己的阈值之前，用于“流水”页的提示音和震动。',
  'These come from the server, move with real traffic, and drive the chime and the buzz on the Flow screen.': '这些来自服务器，随真实交易量变化，决定“流水”页的提示音和震动。',
  'Send a test notification': '发送一条测试通知',
  'A test notification will arrive in a few seconds.': '测试通知会在几秒内到达。',
  'The test notification could not be scheduled': '无法安排测试通知',
  '1 reminder set on this phone for your unlock.': '已在这台手机上为你的解锁设置 1 条提醒。',
  '{count} reminders set on this phone for your unlock.': '已在这台手机上为你的解锁设置 {count} 条提醒。',
  'The reminders for your unlock were cancelled.': '解锁提醒已取消。',
  'The alert could not be changed.': '无法更改该提醒。',
  'Language': '语言',
  'The app follows your phone until you choose here. The card you share stays in English, so it reads the same to everyone who sees it.': '在你这里选择之前，应用跟随手机的语言。分享出去的卡片始终是英文，这样每个看到它的人读到的都一样。',

  // Notifications themselves
  'This wallet has no pending SKR unlock.': '该钱包没有待解锁的 SKR。',
  'SKR unlocks in 1 hour': 'SKR 将在 1 小时后解锁',
  'Your pending SKR is approaching its withdrawable time.': '你待处理的 SKR 快到可提取时间了。',
  'Your SKR is now withdrawable': '你的 SKR 现在可以提取了',
  'Open SKR Eyes to verify the finalized position and evidence.': '打开 SKR Eyes 查看最终确认的仓位和凭证。',
  'SKR Eyes alerts are ready': 'SKR Eyes 提醒已就绪',
  'Test complete. Real unlock alerts will use finalized on-chain time.': '测试完成。真正的解锁提醒会使用链上最终确认的时间。',

  // Staking sheet
  'Add to your position': '追加到你的仓位',
  'Amount per transaction': '每笔金额',
  'SKR has six decimal places. Shorten the amount — the extra digits cannot be staked.': 'SKR 有六位小数。请缩短金额，多出的位数无法质押。',
  'A single transaction cannot stake less than 1 SKR.': '单笔质押不能少于 1 SKR。',
  'This is what one transaction stakes. The total is this amount times the count below.': '这是单笔质押的金额。总额等于它乘以下面的笔数。',
  'How many transactions': '分几笔',
  'One transaction, one wallet approval.': '一笔交易，钱包确认一次。',
  '{count} identical transactions from one approval, sent one after another. Each one is a separate on-chain stake.': '一次确认发出 {count} 笔相同的交易，依次发送。每一笔都是链上独立的质押。',
  'This needs {needed} SKR and you hold {held}. ': '这需要 {needed} SKR，而你持有 {held}。',
  'At this amount you can send 1 part.': '按这个金额你可以发送 1 笔。',
  'At this amount you can send {count} parts.': '按这个金额你可以发送 {count} 笔。',
  'Lower the amount to stake what you have.': '调低金额，用你现有的余额质押。',
  'You hold {held} SKR.': '你持有 {held} SKR。',
  'Before you sign': '签名之前',
  'sent as': '发送方式',
  'you stake in total': '总共质押',
  'position account rent': '仓位账户租金',
  'already paid': '已支付',
  '{sol} SOL, once': '{sol} SOL，一次性',
  'Your position account already exists, so only the network fee applies — a few thousand lamports per transaction.': '你的仓位账户已经存在，因此只需网络手续费，每笔几千 lamports。',
  'The first stake creates your position account and its rent stays with the account. Network fees are a few thousand lamports per transaction.': '首次质押会创建你的仓位账户，租金留在该账户里。网络手续费每笔几千 lamports。',
  'Working…': '处理中…',
  'At least 1 SKR per transaction': '每笔至少 1 SKR',
  'Sign and stake {amount} SKR': '签名并质押 {amount} SKR',
  'Sign and stake': '签名并质押',
  'All parts landed': '所有部分都已上链',
  'Stopped': '已停止',
  'Approve in your wallet': '请在钱包中确认',
  'Preparing transactions': '正在准备交易',
  'A run from before': '上一次未完成的执行',
  'Landing on chain': '正在上链',
  'pending': '等待中',
  'sending': '发送中',
  'sent': '已发送',
  'confirmed': '已确认',
  'unknown': '未知',
  'failed': '失败',
  'We do not know yet': '我们还不确定',
  'What happened': '发生了什么',
  'Ask the chain again': '再问一次链上',
  'Stake again': '再质押一次',
  'Discard and start over': '放弃并重新开始',
  'Start over': '重新开始',
  'Close': '关闭',

};
